// Semantic checks and explicit reviewed fixtures; this module never writes one.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {gunzipSync} from 'node:zlib';
import vm from 'node:vm';
import {geometryDigest} from './check-hakurei.mjs';
import {fallsBlocked} from './check-waterfall-cave.mjs';
import {verticalHits} from './check-wind-cave.mjs';
import {checkForestCanopy,checkForestCanopyGround} from './check-forest-canopy.mjs';
const hash=x=>createHash('sha256').update(x).digest('hex');
const raw=a=>Buffer.from(a.buffer,a.byteOffset,a.byteLength);
export function forestDigest(pack){const h=createHash('sha256');for(const m of pack.meshes){h.update(JSON.stringify([m.id,m.material,m.component,m.forestPart,m.overview,m.globalSurface,m.center,m.radius,m.lodDistance,m.maxDetailDistance]));if(m.partRanges)h.update(JSON.stringify([m.partRanges,!!m.forestHomeBatch,m.locationId]));if(m.terrainSource)h.update(JSON.stringify([m.terrainSource,m.terrainCenter,m.terrainLodRadius,m.terrainTile,m.globalNear,m.globalFar]));for(const key of['vertices','farVertices','instances','instanceColors','index'])if(m[key]){h.update(key);h.update(raw(m[key]));}}return h.digest('hex');}
function stats(F,p){return{meshes:p.meshes.length,triangles:p.meshes.reduce((s,m)=>s+m.vertices.length/27,0),farTriangles:p.meshes.reduce((s,m)=>s+(m.farVertices?.length||0)/27,0),bytes:F.bytes(p.meshes)};}
function valid(G,p){assert.equal(new Set(p.meshes.map(m=>m.id)).size,p.meshes.length);for(const m of p.meshes){assert.equal(m.basis,'P');assert(m.center.every(Number.isFinite)&&m.radius>0);for(const a of[m.vertices,m.farVertices].filter(Boolean)){assert(a.length>0&&a.length%27===0&&a.every(Number.isFinite));for(let i=0;i<a.length;i+=9){assert(Math.abs(Math.hypot(a[i+3],a[i+4],a[i+5])-1)<1e-5,m.id+' normal');assert(G.length(G.sub([a[i],a[i+1],a[i+2]],m.center))<m.radius+.02,m.id+' bounds');}for(let i=0;i<a.length;i+=27)assert(G.length(G.cross([a[i+9]-a[i],a[i+10]-a[i+1],a[i+11]-a[i+2]],[a[i+18]-a[i],a[i+19]-a[i+1],a[i+20]-a[i+2]]))>1e-7,m.id+' degenerate');}}}
function rendererProbe(G,read,meshes){const scope=vm.createContext({GA:{...G}}),project=JSON.parse(read('project.json'));vm.runInContext(read('src/renderer.js').toString(),scope);for(const file of project.extensionRenderers)vm.runInContext(read(file).toString(),scope,{filename:file});const renderer=Object.create(scope.GA.DioramaRenderer.prototype);renderer.packs=new Map();renderer.timeUniform={value:0};renderer.recordMap=new Map(meshes.map(data=>[data.id,{data,level:-1}]));return renderer;}
function homeParts(pack){const out={};for(const m of pack.meshes){assert(m.partRanges&&m.locationId===m.component);let near=0,far=0;for(const [part,r]of Object.entries(m.partRanges)){assert(Array.isArray(r)&&r.length===4&&r.every(v=>Number.isInteger(v)&&v>=0&&v%27===0),'Part ranges must contain only numeric triangle offsets');assert.equal(r[0],near);assert.equal(r[2],far);near+=r[1];far+=r[3];out[m.material+':'+part]={vertices:hash(raw(m.vertices.subarray(r[0],r[0]+r[1]))),...(r[3]?{farVertices:hash(raw(m.farVertices.subarray(r[2],r[2]+r[3])))}:{})};}assert.equal(near,m.vertices.length);assert.equal(far,m.farVertices?.length||0);if(m.forestPart==='props')assert(!m.forestHomeBatch&&m.lod==='props'&&m.maxDetailDistance===120);else assert(m.forestHomeBatch);}
 return out;
}
function homeLods(G,read,packs){const meshes=['aliceNear','marisaNear'].flatMap(k=>packs[k].meshes),renderer=rendererProbe(G,read,meshes);renderer.packs.set('forest',{});renderer.mats=Object.fromEntries(['WoodX','WoodY','WoodZ','Roof','Stone','Plaster','Paper','Recess','Iron','Clay','Bark','Grass'].map(kind=>['kourindou'+kind,{kind}]));for(const m of meshes)assert.equal(renderer.material(m),renderer.mats['kourindou'+m.material.slice(6)],'Wood axis or finish was changed during batching');let cases=0,propSelections=0;
 for(const quality of['low','balanced','high'])for(const id of['alice','marisa'])for(const history of[0,1]){renderer.quality=quality;renderer.forestHomeLods=new Map([[id,history]]);const records=packs[id+'Near'].meshes.map(data=>renderer.recordMap.get(data.id)),home=records.filter(r=>r.data.forestHomeBatch),centre=home[0].data.center;assert(home.every(r=>JSON.stringify(r.data.center)===JSON.stringify(centre)&&r.data.radius===home[0].data.radius));const factor=quality==='high'?1.3:quality==='low'?.68:1;
  for(const d of[100,165*factor*.88-.001,165*factor*.88+.001,165*factor*1.12-.001,165*factor*1.12+.001,250]){const rig={eye:[centre[0]+d,centre[1],centre[2]],target:centre,planes:[]},opts={space:'surface',displayMode:'diorama',focus:'forest',vegetation:true},levels=[];for(const r of [...records].reverse()){r.level=levels.length%2;const yes=renderer.wanted(r,rig,opts,d);if(r.data.forestHomeBatch){assert(yes);const level=quality==='low'?1:renderer.levelFor(r,r.distance);levels.push(level);r.level=level;}else{const m=r.data,dist=G.length(G.sub(rig.eye,m.center));assert.equal(yes,dist-m.radius<=Math.min(120,{low:55,balanced:120,high:210}[quality]),'Props lost their independent distance cutoff');propSelections++;}}assert.equal(new Set(levels).size,1,'One house uses mixed structural LODs');cases++;}
 }
 return{cases,propSelections,nearRecords:meshes.length,structuralRecords:meshes.filter(m=>m.forestHomeBatch).length,propRecords:meshes.filter(m=>m.forestPart==='props').length};
}
function boardwalkLods(G,data,read,overview,additions,walks){
 // Use the production wanted chain without acquiring a canvas/GPU. The source
 // is evaluated again for each call, including deliberately stale wanted flags.
 const renderer=rendererProbe(G,read,[...overview.meshes,...additions]);
 const sources=data.forestBoardwalkTerrain,ground={near:G.SurfaceContact.sampler(data,G.FOREST_UPGRADE.scopes.boardwalk.id,'near'),far:G.SurfaceContact.sampler(data,G.FOREST_UPGRADE.scopes.boardwalk.id,'far')},cameras=[];
 for(const m of sources)for(const e of[-.03,.03])cameras.push({eye:[m.center[0]+m.radius+700+e,m.center[1],m.center[2]],distance:300});
 for(const e of[-.001,.001])cameras.push({eye:[-950,120,70],distance:1550+e});
 cameras.push({eye:[-75,70,-128],distance:300},{eye:[-896,70,930],distance:300},{eye:[-994,68,-16],distance:250});
 let selections=0,surfaceChecks=0,mixedCases=0,minGap=Infinity,maxGap=-Infinity;
 for(const quality of['low','balanced','high'])for(const c of cameras)for(const mode of['diorama','atlas']){
  renderer.quality=quality;const rig={eye:c.eye,target:[c.eye[0],c.eye[1],c.eye[2]-c.distance],planes:[]},opts={space:'surface',displayMode:mode,focus:'forest',vegetation:true},selected=new Set();
  for(const m of sources){const r=renderer.recordMap.get(m.id);r.wanted=false;if(renderer.wanted(r,rig,opts,c.distance))selected.add(m.id);}
  for(const m of additions){const r=renderer.recordMap.get(m.id),source=renderer.recordMap.get(m.terrainSource);source.wanted=!selected.has(m.terrainSource);assert.equal(renderer.wanted(r,rig,opts,c.distance),selected.has(m.terrainSource),'Boardwalk and actual tile choose different LOD: '+quality+'/'+mode+'/'+m.id);assert(!m.farVertices,'Low quality can independently change deck precision');selections++;}
  const actual=new Set(additions.filter(m=>selected.has(m.terrainSource)).map(m=>m.globalNear?'near':'far'));if(actual.size===2)mixedCases++;
  const deck=additions.filter(m=>m.material==='forestWoodZ'&&selected.has(m.terrainSource));for(const w of walks)for(const face of w.surfaceTriangles)if(selected.has(face.terrainSource))for(const weights of[[1/3,1/3,1/3],[.8,.1,.1],[.1,.8,.1],[.1,.1,.8]]){const p=[0,1,2].map(k=>face.points.reduce((s,v,i)=>s+v[k]*weights[i],0)),drawnGround=sources.filter(m=>selected.has(m.id)&&p[0]>=m.tile[0]&&p[0]<=m.tile[0]+m.tile[2]&&p[2]>=m.tile[1]&&p[2]<=m.tile[1]+m.tile[2]);assert(drawnGround.length,'Selected deck has no rendered ground');
   // Source spheres can overlap slightly at their own LOD boundary. If the
   // renderer selects both terrains, depth displays the upper surface; compare
   // the actual upper deck to it, rather than comparing to the hidden terrain.
   const h=Math.max(...drawnGround.map(m=>ground[m.far?'far':'near'].height(p[0],p[2]))),hits=verticalHits(deck,p[0],p[2],h-.5,h+.9);assert(hits.length,'Tile-bound deck has a hole');const gap=Math.max(...hits)-h;assert(gap>.075&&gap<.70,'Selected deck intersects or floats above selected terrain: '+JSON.stringify({quality,mode,camera:c,source:face.terrainSource,p,gap,hits}));minGap=Math.min(minGap,gap);maxGap=Math.max(maxGap,gap);surfaceChecks++;}
 }
 assert(mixedCases>0,'Mixed near/far terrain cameras were not exercised');
 for(const space of['mausoleum','senkai','section','asama']){const rig={eye:[-994,68,-16],target:[-994,68,-266],planes:[]},opts={space,displayMode:'diorama',focus:'forest'};for(const m of additions)assert(!renderer.wanted(renderer.recordMap.get(m.id),rig,opts,250),'Surface boardwalk is visible in another space');}
 let seamChecks=0;const nearDeck=walks[0].meshes.filter(m=>m.material==='forestWoodZ'),farDeck=walks[1].meshes.filter(m=>m.material==='forestWoodZ');for(const face of walks[0].surfaceTriangles)for(const [axis,value]of[[0,-1024],[2,0]])for(let i=0;i<3;i++){const a=face.points[i],b=face.points[(i+1)%3];if(Math.abs(a[axis]-value)>1e-6||Math.abs(b[axis]-value)>1e-6||Math.hypot(a[0]-b[0],a[2]-b[2])<1e-6)continue;for(const u of[.1,.5,.9]){const p=a.map((v,k)=>v+(b[k]-v)*u),h=ground.near.height(p[0],p[2]);assert(Math.abs(h-ground.far.height(p[0],p[2]))<.0001,'Inherited terrain LOD boundary differs');const n=verticalHits(nearDeck,p[0],p[2],h,h+.7),f=verticalHits(farDeck,p[0],p[2],h,h+.7);assert(n.length&&f.length,'Mixed LOD deck edge has a gap');assert(Math.abs(Math.max(...n)-Math.max(...f))<.003,'Near/far deck edges do not meet');seamChecks++;}}
 assert(seamChecks>0,'Tile boundary deck seams were not checked');return{selections,surfaceChecks,mixedCases,seamChecks,minGap,maxGap};
}
export async function inspectForest(G,data,read,options={}){
 const F=G.FOREST_UPGRADE,t=new G.Terrain(data),original=G.buildForest(t),padsBefore=JSON.stringify(G.FOREST.pads),pathsBefore=JSON.stringify(G.FOREST.paths),z=gunzipSync(read('assets/packs/overview.pack.gz')),overview=G.decodePack(z.buffer.slice(z.byteOffset,z.byteOffset+z.byteLength));G.LANDSCAPE.apply(overview,t);G.applyHighlandGround(overview,t);
 // Match production order without constructing other regional detail packs.
 overview.meshes.push(...G.KOURINDOU_UPGRADE.publicEnvironment(data,overview),...G.KOURINDOU_UPGRADE.architecture(true).meshes);
 const before=overview.meshes.slice(),arrayHashes=new Map();for(const m of before)for(const k of['vertices','farVertices','instances','instanceColors','index'])if(m[k]&&!arrayHashes.has(m[k]))arrayHashes.set(m[k],hash(raw(m[k])));
 const oldHomes=before.filter(m=>m.owner==='forest'&&F.ids.includes(m.component)),oldTrees=before.filter(m=>m.owner==='forest'&&m.component==='trees');assert.equal(oldHomes.length,8);assert.equal(oldTrees.length,1);assert.equal(oldTrees[0].instances.length/16,304);
 const additions=F.publicEnvironment(data,overview),publicPack={meshes:additions};valid(G,publicPack);assert(additions.length<=12);assert(additions.every(m=>m.globalSurface&&m.overview&&!m.farVertices&&m.terrainSource));
 for(const m of additions){const source=overview.meshes.find(q=>q.id===m.terrainSource);assert(source&&source.component==='island-terrain');assert.equal(!!m.globalNear,!!source.globalNear);assert.equal(!!m.globalFar,!!source.globalFar);assert.equal(JSON.stringify(m.terrainCenter),JSON.stringify(source.center));assert.equal(m.terrainLodRadius,source.radius);assert.equal(JSON.stringify(m.terrainTile),JSON.stringify(source.tile));const[x,z,s]=source.tile;for(let i=0;i<m.vertices.length;i+=9)assert(m.vertices[i]>=x-.0001&&m.vertices[i]<=x+s+.0001&&m.vertices[i+2]>=z-.0001&&m.vertices[i+2]<=z+s+.0001,'Boardwalk face crosses its terrain LOD tile');}
 assert(JSON.stringify(data.forestBoardwalkTerrain).length<3000,'Tile metadata contains excess terrain data');assert(data.forestBoardwalkTerrain.every(m=>Object.keys(m).sort().join(',')==='center,far,id,radius,tile'));
 for(const m of before)if(!oldHomes.includes(m))assert(overview.meshes.includes(m),'Unrelated overview record was removed');for(const [a,digest]of arrayHashes)assert.equal(hash(raw(a)),digest,'Original overview buffer mutated');assert(!overview.meshes.some(m=>m.owner==='forest'&&F.ids.includes(m.component)));
 const packs={},geometry={public:forestDigest(publicPack)},partGeometry={},result={public:stats(F,publicPack),contacts:0,openings:0,roofChecks:0,boardwalkContacts:0,boardwalkSurfaceChecks:0};let nearTris=0,farTris=0,sourceBytes=0;
 for(const id of F.ids)for(const far of[false,true]){const key=id+(far?'Far':'Near'),p=F.architecture(id,far,data),pad=G.FOREST.pads.find(q=>q.id===id),ground=G.SurfaceContact.sampler(data,F.scopes[id].id,far?'far':'near');valid(G,p);assert(!p.meta.fullInterior&&!p.meta.terrainMutation);assert.equal(JSON.stringify(p.meta.footprint),JSON.stringify(pad));assert.equal(F.bytes(p.meshes),p.bytes);assert.equal(forestDigest(F.architecture(id,far,data)),forestDigest(p),'Nondeterministic house');packs[key]=p;geometry[key]=forestDigest(p);partGeometry[key]=homeParts(p);result[key]=stats(F,p);if(far)farTris+=result[key].triangles;else{nearTris+=result[key].triangles;sourceBytes+=p.bytes;}
  const plaster=p.meshes.filter(m=>m.material==='forestPlaster'),paper=p.meshes.filter(m=>m.material==='forestPaper'),front=pad.z+(id==='alice'?7.7:7.3),windows=id==='alice'?[[-6.1,2.15],[6.1,2.15],[0,6.25]]:[[-5.8,2.15],[5.8,2.15],[-5.8,5.05],[5.8,5.05]];
  for(const [x,y]of windows)for(const offset of[-.28,.28]){const a=[pad.x+x+offset,pad.y+y,front+.50],b=[a[0],a[1],front-.11];assert.equal(fallsBlocked(G,plaster,a,b),null,'Window still has a solid wall behind it');assert(fallsBlocked(G,paper,b,[b[0],b[1],front-.25]),'Missing actual recessed window pane');result.openings++;}
  for(const x of[.18,.45])assert.equal(fallsBlocked(G,p.meshes.filter(m=>m.forestPart!=='props'),[pad.x+x,pad.y+2,front+.7],[pad.x+x,pad.y+2,front-.50]),null,'Entrance is a closed panel');
  for(const q of p.meta.contacts){const h=ground.height(q.x,q.z);assert(q.bottom<h&&q.top>q.bottom,'Foundation must be buried');const hits=verticalHits(F.partMeshes(p.meshes,['foundation']),q.x,q.z,q.bottom-.25,q.top+.25);assert(hits.some(y=>Math.abs(y-q.top)<.025),'Foundation has no bearing top');assert(hits.some(y=>y<=h+.025),'Foundation is detached from ground');result.contacts++;}
  const roof=F.partMeshes(p.meshes,['roof','roofUnder']),posts=F.partMeshes(p.meshes,['structure']).filter(m=>m.material==='forestWoodY');for(const [x,z,y0,y1]of id==='alice'?[[-3,11.4,88,90],[3,11.4,88,90]]:[[-7.3,11.8,73,75],[7.3,11.8,73,75],[12,-4,72,74],[21,4,72,74]]){const hs=verticalHits(posts,pad.x+x,pad.z+z,y0,y1),hr=verticalHits(roof,pad.x+x,pad.z+z,y0,y1);assert(hs.length&&hr.length,'Missing roof or actual support');assert(Math.max(...hs)>=Math.min(...hr)-.04,'Post is detached from roof');result.roofChecks++;}
  if(id==='marisa')for(const [dx,dy]of[[.20,-.5],[-.20,-.5],[.35,.2],[-.35,.2]]){const a=[pad.x-3.3+dx,pad.y+10.65+dy,pad.z+8.2],b=[a[0],a[1],pad.z+5.90];assert.equal(fallsBlocked(G,roof,a,b),null,'Main roof still crosses the dormer window');result.roofChecks++;}
 }
 for(const id of F.ids){assert.equal(packs[id+'Near'].meshes.length,id==='alice'?11:13);for(const [part,digest]of Object.entries(partGeometry[id+'Near']))assert.equal(digest.farVertices,partGeometry[id+'Far'][part].vertices,'Detail far part differs from overview part');}result.homeLods=homeLods(G,read,packs);
 assert(nearTris<=25576,'Two-home near triangle budget');assert(farTris<=5491,'Two-home proxy triangle budget');assert(sourceBytes<=3.5*1048576,'Two-home near/far source budget');
 assert.throws(()=>F.boardwalk({surfaceContacts:data.surfaceContacts}),/terrain tiles not prepared/,'Missing Worker tile preparation silently fell back');
 const walks=[];for(const far of[false,true]){const p=F.boardwalk(data,far),ground=G.SurfaceContact.sampler(data,F.scopes.boardwalk.id,far?'far':'near'),deck=p.meshes.filter(m=>m.material==='forestWoodZ'),feet=p.meshes.filter(m=>m.material==='forestStone');assert.equal(forestDigest(F.boardwalk(structuredClone(data),far)),forestDigest(p),'Worker clone changes boardwalk geometry');walks.push(p);valid(G,p);const n=stats(F,p);result[far?'publicFar':'publicNear']=n;assert(n.triangles<=(far?600:1080),'Boardwalk budget');for(let i=1;i<p.sections.length;i++){const prev=p.sections[i-1].corners,next=p.sections[i].corners;assert.deepEqual(Array.from(prev[2]),Array.from(next[1]),'Boardwalk turn gap');assert.deepEqual(Array.from(prev[3]),Array.from(next[0]),'Boardwalk turn gap');}
  for(const section of p.sections){const [A,D,E,H]=section.corners;for(const u of[.05,.5,.95])for(const v of[.05,.5,.95]){const x=(A[0]*(1-v)+D[0]*v)*(1-u)+(H[0]*(1-v)+E[0]*v)*u,z=(A[2]*(1-v)+D[2]*v)*(1-u)+(H[2]*(1-v)+E[2]*v)*u,h=ground.height(x,z),hits=verticalHits(deck,x,z,h-.5,h+.9);assert(hits.length,'Deck has a hole');const top=Math.max(...hits);assert(top>=h+.075&&top<h+.70,'Deck intersects or floats above terrain');result.boardwalkSurfaceChecks++;}}
  for(const q of p.contacts){const h=ground.height(q.x,q.z),support=verticalHits(feet,q.x,q.z,q.bottom-.2,q.top+.2);assert(q.bottom<h&&q.bottom>h-.2);assert(support.some(y=>Math.abs(y-q.top)<.01),'Missing bearing foot');const hits=verticalHits(deck,q.x,q.z,h,h+.8);assert(hits.length&&Math.min(...hits)<=q.top+.025,'Foot does not reach actual deck');result.boardwalkContacts++;}
  for(const p0 of G.FOREST.paths.find(p=>p.id==='forest-boardwalk').samples.filter((_,i,a)=>i===0||i===a.length-1)){const h=ground.height(...p0),hits=verticalHits(feet,p0[0],p0[1],h-.2,h+.4);assert(hits.some(y=>y>h+.12&&y<h+.29),'Missing supported path landing');}
 }
 result.boardwalkLods=boardwalkLods(G,data,read,overview,additions,walks);
 const current=await G.buildRegion(data,'forest'),retained=current.meshes.find(m=>m.id==='forest:understorey'),old=original.meshes.find(m=>m.id==='forest:understorey'),prefix=F.legacyBoardwalk(t);assert.equal(prefix.length/27,1080);assert.equal(hash(raw(retained.vertices)),hash(raw(old.vertices.subarray(prefix.length))));assert.equal(retained.vertices.byteOffset,0);assert.equal(retained.vertices.byteLength,retained.vertices.buffer.byteLength,'Removed prefix is still retained in buffer');
 const canopyGroundIDs=new Set([-1280,-1024].flatMap(x=>['near','far'].map(lod=>'forest:canopy-ground:'+x+':0:'+lod)));
 const keep=m=>!['alice','marisa','kourindou'].includes(m.component)&&m.id!=='forest:understorey'&&!G.FOREST_CANOPY.targets.has(m.id)&&!canopyGroundIDs.has(m.id);
 assert.equal(geometryDigest({meshes:current.meshes.filter(keep)}),geometryDigest({meshes:original.meshes.filter(keep)}),'Untouched forest trees, route, fungi or ancient oak changed');
 assert(options.overviewBefore&&options.overviewAfter,'Actual production overview snapshots required for canopy checks');
 result.canopy=checkForestCanopy(G,original,current,read,options);
 result.canopyGround=checkForestCanopyGround(G,original,options.overviewBefore,read,{currentDetail:current});
 assert.equal(JSON.stringify(current.signs),JSON.stringify(original.signs));assert.equal(current.meta.treeCount,755);assert.equal(F.bytes(current.meshes),current.bytes);assert.equal(JSON.stringify(G.FOREST.pads),padsBefore);assert.equal(JSON.stringify(G.FOREST.paths),pathsBefore);
 let resourceConstructions=0;const scope=vm.createContext({GA:{DioramaRenderer:class{constructor(){resourceConstructions++;}},FOREST:{paths:G.FOREST.paths}}});vm.runInContext(read('src/forest-renderer.js').toString(),scope);const lanes=scope.GA.DioramaRenderer.yardSegments();assert(lanes.length>0&&lanes.length<=64&&lanes.every(Number.isFinite));scope.GA.FOREST.paths=[];assert.throws(()=>new scope.GA.DioramaRenderer(),/Missing forest-home route/);assert.equal(resourceConstructions,0,'Missing route acquired renderer resources');
 const contactBytes=Object.values(F.scopes).reduce((n,s)=>n+data.surfaceContacts[s.id].near.byteLength+data.surfaceContacts[s.id].far.byteLength,0);assert(contactBytes<100000,'Contact transfer budget');return{...result,totalHomeNearTriangles:nearTris,totalHomeFarTriangles:farTris,contactBytes,terrainMetadataBytes:Buffer.byteLength(JSON.stringify(data.forestBoardwalkTerrain)),laneSegments:lanes.length/4,laneBytes:lanes.byteLength,originalForest:geometryDigest(original),geometry,partGeometry,currentForest:geometryDigest(current),overviewTreeMatrices:hash(raw(oldTrees[0].instances)),sourceBytes,treeCount:755,overviewTreeCount:304};
}
export async function checkForest(G,atlas,characters,read,options={}){const fixture=JSON.parse(read('tools/forest-baseline.json')),report=await inspectForest(G,atlas,read,options);assert.equal(report.originalForest,fixture.originalForest,'Original v0.14 source changed');for(const [key,digest]of Object.entries(fixture.geometry))assert.equal(report.geometry[key],digest,'Forest geometry needs explicit review: '+key);assert.deepEqual(report.partGeometry,fixture.partGeometry,'Original house-part bytes need explicit review');assert.equal(report.overviewTreeMatrices,fixture.overviewTreeMatrices,'Overview tree matrices changed');for(const [file,digest]of Object.entries(fixture.protectedFiles||{}))assert.equal(hash(read(file)),digest,'Inherited source changed: '+file);assert.equal(characters.characters.length,85);const audit=G.auditLandmarks(atlas);assert.equal(audit.total,179);assert.equal(audit.navigable,109);assert.equal(audit.pending,70);return report;}
