// Read-only village refinement checks. Draft mode is explicit; normal checks
// require a separately reviewed fixture and never generate or rewrite it.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {gunzipSync} from 'node:zlib';
import vm from 'node:vm';
import * as THREE from '../vendor/three/three.module.js';
import {geometryDigest} from './check-hakurei.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');
const raw=a=>Buffer.from(a.buffer,a.byteOffset,a.byteLength);
function replay(source,target){
 const a=new Uint32Array(source.vertices.buffer,source.vertices.byteOffset,source.vertices.length),b=new Uint32Array(target.vertices.buffer,target.vertices.byteOffset,target.vertices.length),oldIndex=source.index,index=target.index,n=oldIndex?oldIndex.length:a.length/9;
 assert.equal(index?index.length:b.length/9,n,'Near triangle order/count changed: '+source.id);
 for(let i=0;i<n;i++){const old=(oldIndex?oldIndex[i]:i)*9,now=(index?index[i]:i)*9;for(let j=0;j<9;j++)if(b[now+j]!==a[old+j])assert.fail('Float32 triangle attribute changed: '+source.id+'/'+i+'/'+j);}
 return n/3;
}
function stats(V,meshes){let triangles=0,farTriangles=0,channelBytes=0;const seen=new Set(),sourceSeen=new Set(),sourceFields={vertices:0,index:0,farVertices:0,instances:0,instanceColors:0,villageFinish:0,villageFarFinish:0};for(const m of meshes){triangles+=V.triangles(m);farTriangles+=V.triangles(m,true);if(m.material==='villageSurface')for(const a of[m.vertices,m.farVertices].filter(Boolean))if(!seen.has(a)){seen.add(a);channelBytes+=a.length/9*2;}for(const k of Object.keys(sourceFields)){const a=m[k];if(a&&!sourceSeen.has(a)){sourceSeen.add(a);sourceFields[k]+=a.byteLength;}}}
 const uploaded=far=>{const arrays=new Set(),finish=new Set();let bytes=0;const add=a=>{if(a&&!arrays.has(a)){arrays.add(a);bytes+=a.byteLength;}};for(const m of meshes){const a=far&&m.farVertices?m.farVertices:m.vertices;add(a);if(a===m.vertices)add(m.index);add(m.instances);add(m.instanceColors);if(m.material==='villageSurface'&&!finish.has(a)){finish.add(a);bytes+=a.length/9*2;}}return bytes;};
 return{meshes:meshes.length,indexedMeshes:meshes.filter(m=>m.index).length,sourceBytes:V.bytes(meshes),sourceViewBytes:Object.values(sourceFields).reduce((a,b)=>a+b,0),sourceFields,expandedTriangles:triangles,farExpandedTriangles:farTriangles,allFinishAttributeBytes:channelBytes,nearUploadAttributeBytes:uploaded(false),farUploadAttributeBytes:uploaded(true)};
}
function cpuRenderer(V,read){
 const scope=vm.createContext({GA:{VILLAGE_UPGRADE:V},performance});
 vm.runInContext(String(read('src/renderer.js')),scope);vm.runInContext(String(read('src/village-renderer.js')),scope);
 const Renderer=scope.GA.DioramaRenderer;return Object.assign(Object.create(Renderer.prototype),{T:THREE,scene:new THREE.Scene(),mats:{villageSurface:new THREE.MeshStandardMaterial()},cache:new Map(),geometryRefs:new Map(),indexByArray:new Map(),recordMap:new Map(),packs:new Map(),records:[],objects:[],signObjects:[],residentBytes:0,uploads:0,evictions:0,engine:{shadowMap:{},renderLists:{dispose(){}}}});
}
// Reuse the required finish audit as the first real CPU acquire of each array.
// No extra region generation or second full attribute construction is needed.
function detailAttributes(V,read,meshes,reference){
 const r=cpuRenderer(V,read),seen=new Set(),timings={near:{arrays:0,finishBytes:0,acquireMs:0},far:{arrays:0,finishBytes:0,acquireMs:0}},hashes={near:createHash('sha256'),far:createHash('sha256')},originalChannels=V.channels;let group=null,attributeTriangles=0,referenceArrays=0,mainThreadChannelCalls=0;
 r.addRecords(meshes.filter(m=>m.material==='villageSurface'),'village-attribute-audit');
 V.channels=()=>{mainThreadChannelCalls++;throw Error('Main-thread acquire recomputed village channels');};
 try{for(const m of meshes)if(m.material==='villageSurface')for(const a of[m.vertices,m.farVertices].filter(Boolean)){
  if(seen.has(a))continue;seen.add(a);const lod=a===m.vertices?'near':'far';group=timings[lod];const start=performance.now(),geo=r.acquire(a);group.acquireMs+=performance.now()-start;
  try{const c=geo.getAttribute('villageFinish').array,ix=a===m.vertices?m.index:null,n=ix?ix.length:a.length/9;group.arrays++;group.finishBytes+=c.byteLength;assert.equal(c.byteLength,a.length/9*2);assert.equal(c,a===m.vertices?m.villageFinish:m.villageFarFinish,'Acquire cloned the Worker finish');assert.equal(geo.index?.array||null,ix||null,'Attribute audit reused wrong geometry index');
   if(reference){assert(raw(c).equals(raw(reference.channels(m,a))),'Scalar finish/axis differs from v1: '+m.id+'/'+lod);referenceArrays++;}
   const drawn=new Uint8Array(n*2);for(let i=0;i<n;i++){const from=(ix?ix[i]:i)*2;drawn[i*2]=c[from];drawn[i*2+1]=c[from+1];}hashes[lod].update(JSON.stringify([m.id,n]));hashes[lod].update(raw(drawn));
   for(let i=0;i<n;i+=3){const ids=[0,1,2].map(k=>(ix?ix[i+k]:i+k)*2);for(let k=1;k<3;k++){assert.equal(c[ids[k]],c[ids[0]],'Interpolated surface finish: '+m.id);assert.equal(c[ids[k]+1],c[ids[0]+1],'Interpolated structural axis: '+m.id);}attributeTriangles++;}
  }finally{r.release(a);}
 }}finally{V.channels=originalChannels;for(const a of r.geometryRefs.keys())r.release(a);r.mats.villageSurface.dispose();}
 assert.equal(r.residentBytes,0);assert.equal(r.geometryRefs.size,0);assert.equal(r.cache.size,0);
 return{attributeTriangles,finishDigests:{near:hashes.near.digest('hex'),far:hashes.far.digest('hex')},coldAcquire:{...timings,acquireMs:timings.near.acquireMs+timings.far.acquireMs,mainThreadChannelCalls,referenceArrays,finalResidentBytes:0,gpuUploadIncluded:false,scope:'All unique detail near/far villageSurface arrays; CPU bounds/index setup and direct Worker-finish upload descriptors, excludes validation/reference checks and GPU upload'}};
}
export function rendererResources(G,read){
 const V=G.VILLAGE_UPGRADE,g=new G.Geometry();g.box(0,0,0,1,5,.25,G.C.wood);
 const original=g.mesh('resource-box').vertices,near=V.indexed(original,V.channels({vertices:original})),farRaw=original.slice(0,27),far=V.withFinish(farRaw,V.channels({vertices:farRaw})),m={id:'test:grain',group:'town',owner:'village',material:'villageSurface',...near,farVertices:far.vertices,villageFarFinish:far.villageFinish},r=cpuRenderer(V,read),channels=V.channels;
 assert(near.index,'Authored Geometry.box did not exercise indexed near/far isolation');
 V.channels=()=>{throw Error('CPU acquire recomputed Worker finish');};try{
 const records=[m,{...m,id:'test:shared'}];r.attachPack({id:'village',meshes:records,signs:[]});const first=r.recordMap.get(m.id),second=r.recordMap.get('test:shared'),geo=r.ensure(first,0).geometry;
 const finishBytes=geo.getAttribute('villageFinish').array.byteLength,nearBytes=near.vertices.byteLength+(near.index?.byteLength||0)+finishBytes;
 assert.equal(r.residentBytes,nearBytes,'Finish attribute omitted from residency');r.ensure(second,0);assert.equal(r.residentBytes,nearBytes,'Shared finish attribute counted twice');
 assert.equal(geo.index?.array,near.index,'Near source index not uploaded');r.evict(second);assert.equal(r.residentBytes,nearBytes);
 let faults=0;const savedFar=m.villageFarFinish;for(const bad of[null,m.villageFinish]){for(const source of records)source.villageFarFinish=bad;assert(!r.geometryRefs.has(m.farVertices),'Invalid finish case was not a cold acquire');assert.throws(()=>r.ensure(first,1),/invalid Worker village finish/);faults++;assert.equal(first.item.mesh.geometry,geo);assert.equal(first.level,0);assert.equal(r.residentBytes,nearBytes);}for(const source of records)source.villageFarFinish=savedFar;
 const realT=r.T;r.T={...THREE,BufferAttribute:class extends THREE.BufferAttribute{constructor(array,size){if(size===2)throw Error('injected finish allocation failure');super(array,size);}}};
 assert.throws(()=>r.ensure(first,1),/injected finish/);faults++;assert.equal(first.item.mesh.geometry,geo);assert.equal(first.level,0);assert.equal(r.residentBytes,nearBytes,'Failed far upload changed old residency');
 r.T=realT;const farGeo=r.ensure(first,1).geometry;assert.equal(farGeo.index,null,'Far vertices reused the near index');assert.equal(r.residentBytes,far.vertices.byteLength+far.villageFinish.byteLength);assert.equal(farGeo.getAttribute('villageFinish').array,m.villageFarFinish);
 r.dropPack('village');assert.equal(r.residentBytes,0);for(const k of ['cache','geometryRefs','indexByArray','recordMap','packs'])assert.equal(r[k].size,0,'Resource retained: '+k);assert.equal(r.objects.length,0);assert.equal(r.records.length,0);assert.equal(r.scene.children.length,0);
 assert(!r.villageArrays.has(m.vertices)&&!r.villageArrays.has(m.farVertices),'Dropped finish metadata retained');
 const expected={near:hash(raw(m.vertices)),far:hash(raw(m.farVertices)),nearFinish:hash(raw(m.villageFinish)),farFinish:hash(raw(m.villageFarFinish)),nearLength:m.vertices.length,farLength:m.farVertices.length,nearOffset:m.villageFinish.byteOffset,farOffset:m.villageFarFinish.byteOffset,sourceBytes:V.bytes(records)},buffers=new Set();for(const mesh of records)for(const k of['vertices','farVertices','instances','instanceColors','index'])if(mesh[k])buffers.add(mesh[k].buffer);
 assert.equal(buffers.size,3,'Finish required a separate/untracked transfer');const clone=structuredClone({id:'village',meshes:records,signs:[],bytes:expected.sourceBytes},{transfer:[...buffers]}),received=clone.meshes[0];for(const buffer of buffers)assert.equal(buffer.byteLength,0,'Sender buffer did not detach');
 assert.equal(received.vertices,clone.meshes[1].vertices);assert.equal(received.villageFinish,clone.meshes[1].villageFinish);assert.equal(received.vertices.length,expected.nearLength);assert.equal(received.farVertices.length,expected.farLength);
 assert.equal(received.villageFinish.buffer,received.vertices.buffer);assert.equal(received.villageFarFinish.buffer,received.farVertices.buffer);assert.notEqual(received.vertices.buffer,received.farVertices.buffer);assert.equal(received.villageFinish.byteOffset,expected.nearOffset);assert.equal(received.villageFarFinish.byteOffset,expected.farOffset);
 assert.equal(hash(raw(received.vertices)),expected.near);assert.equal(hash(raw(received.farVertices)),expected.far);assert.equal(hash(raw(received.villageFinish)),expected.nearFinish);assert.equal(hash(raw(received.villageFarFinish)),expected.farFinish);assert.equal(V.bytes(clone.meshes),expected.sourceBytes);assert.equal(received.farVertices.buffer.byteLength,116,'Odd vertex tail alignment/padding changed');
 for(let cycle=0;cycle<3;cycle++){r.attachPack(clone);const record=r.recordMap.get(received.id),item=r.ensure(record,0);assert.equal(item.geometry.getAttribute('villageFinish').array,received.villageFinish);assert.equal(r.residentBytes,nearBytes);r.dropPack('village');assert.equal(r.residentBytes,0);assert(!r.villageArrays.has(received.vertices));}
 const freshNear=V.withFinish(received.vertices,received.villageFinish),freshFar=V.withFinish(received.farVertices,received.villageFarFinish),fresh={...received,...freshNear,farVertices:freshFar.vertices,villageFarFinish:freshFar.villageFinish};r.attachPack({id:'village',meshes:[fresh],signs:[]});assert(!r.villageArrays.has(received.vertices));const item=r.ensure(r.recordMap.get(fresh.id),0);assert.equal(item.geometry.getAttribute('villageFinish').array,fresh.villageFinish);r.dropPack('village');assert.equal(r.residentBytes,0);
 return{sharedFinishBytes:finishBytes,allocationFailureRollback:faults,farIndexIsolated:true,transferBuffers:buffers.size,senderDetached:true,finishTransferredWithVertices:true,sharedViewsPreserved:true,oddVertexBufferBytes:116,reentryCycles:3,freshWorkerReentry:true,mainThreadChannelsRequired:false,finalResidentBytes:0};
 }finally{V.channels=channels;r.dropPack('village');r.mats.villageSurface.dispose();}
}
export function shaderComposition(G,read){
 class Base{constructor(){this.mats={matte:new THREE.MeshStandardMaterial(),paving:new THREE.MeshStandardMaterial(),ground:new THREE.MeshStandardMaterial(),hakureiRecess:new THREE.MeshStandardMaterial()};this.studioEnv={texture:new THREE.Texture()};this.scene=new THREE.Scene();this.scene.environment=this.studioEnv.texture;this.hakureiCardMaterials={hakureiLeaf:new THREE.MeshStandardMaterial()};this.hakureiCardDepth={hakureiLeaf:new THREE.MeshDepthMaterial()};}lighting(){this.mats.matte.envMapIntensity=this.nightActive?.035:.21;this.mats.hakureiRecess.envMapIntensity=this.nightActive?.006:.03;}}
 const scope=vm.createContext({GA:{...G,DioramaRenderer:Base}});vm.runInContext(String(read('src/kourindou-renderer.js')),scope);const Original=scope.GA.DioramaRenderer,source=new Original(THREE,null,{});
 vm.runInContext(String(read('src/village-renderer.js')),scope);const Renderer=scope.GA.DioramaRenderer,mat=Renderer.mixedMaterial(source.mats.kourindouWoodY),make=()=>({vertexShader:THREE.ShaderLib.standard.vertexShader,fragmentShader:THREE.ShaderLib.standard.fragmentShader,uniforms:{}}),before=make(),after=make();
 source.mats.kourindouWoodY.onBeforeCompile(before);mat.onBeforeCompile(after);
 assert(before.fragmentShader.includes('vec3(-560.,45.,0.)'),'Inherited material pivot changed');assert(after.fragmentShader.includes('vec3(0.,30.,0.)'));assert(after.vertexShader.includes('attribute vec2 villageFinish;'));
 assert(!after.fragmentShader.includes('uKourSurface'));assert(after.fragmentShader.includes('vVillageFinish.x'));assert(after.fragmentShader.includes('villageRoofUV'));assert(after.fragmentShader.includes('kRough'));assert(after.fragmentShader.includes('iblIrradiance*=uVillageRecessEnvRatio'));assert(after.fragmentShader.includes('reflectedLight.indirectDiffuse*=.64;'),'Inherited recess diffuse adjustment changed');assert.equal(after.uniforms.uVillageRecessEnvRatio.value,.03);assert.equal(mat.envMap,null,'Ordinary village surfaces inherited the explicit Kourindou map');assert.equal(source.mats.kourindouWoodY.envMap,source.studioEnv.texture,'Cloning changed the source environment');assert.equal(source.mats.kourindouWoodY.envMapIntensity,.12);assert.notEqual(mat.customProgramCacheKey(),source.mats.kourindouWoodY.customProgramCacheKey());
 const sourceAfter=make();source.mats.kourindouWoodY.onBeforeCompile(sourceAfter);assert.equal(sourceAfter.vertexShader,before.vertexShader);assert.equal(sourceAfter.fragmentShader,before.fragmentShader);assert.deepEqual(sourceAfter.uniforms,before.uniforms,'Village shader changed source Kourindou uniforms');
 const pavement=Renderer.pavingMaterial(source.mats.paving),road=Renderer.roadMaterial(source.mats.ground,G.VILLAGE_UPGRADE.routeSegments(),false),shoulder=Renderer.roadMaterial(source.mats.ground,G.VILLAGE_UPGRADE.routeSegments(),true);
 for(const m of[pavement,road,shoulder])m.onBeforeCompile(make());assert.equal(road.customProgramCacheKey(),shoulder.customProgramCacheKey(),'Road shoulder compiled an extra program');
 assert.notEqual(road.onBeforeCompile,shoulder.onBeforeCompile);
 const r=new Renderer(THREE,null,{}),initialEnvironment=r.studioEnv.texture,replacementScene=new THREE.Texture(),recoveredEnvironment=new THREE.Texture(),phases=[];let lightingChecks=0;
 const checkLighting=(night,intensity,explicit=r.mats.kourindouWoodY.envMap)=>{r.nightActive=night;r.scene.environmentIntensity=intensity;const environment=r.scene.environment;r.lighting({}, {},100);const target=night?.006:.03,expected=intensity>1e-9?Math.max(0,Math.min(1,target/intensity)):0,ratio=r.mats.villageSurface.userData.villageRecessEnvRatio.value;
  assert.equal(r.mats.villageSurface.envMap,null,'Lighting rebound the ordinary surface to the Kourindou map');assert.equal(r.scene.environment,environment,'Village lighting changed the scene environment');assert.equal(r.scene.environmentIntensity,intensity,'Village lighting changed the scene environment intensity');assert.equal(r.mats.kourindouWoodY.envMap,explicit,'Village lighting changed the Kourindou map');assert.equal(r.mats.kourindouWoodY.envMapIntensity,night?.035:.12);assert.equal(r.mats.kourindouRecess.envMapIntensity,target);assert.equal(r.mats.villageStone.envMap,explicit);assert.equal(r.mats.villageStone.envMapIntensity,night?.035:.12);assert(Math.abs(ratio-expected)<1e-12,'Recess IBL ratio did not use the actual scene intensity');assert(Number.isFinite(ratio)&&ratio>=0&&ratio<=1);if(intensity>=target)assert(Math.abs(ratio*intensity-target)<1e-12,'Recess environment target changed');lightingChecks++;return ratio;
 };
 for(const night of [false,true,false]){const intensity=night?.045:1,ratio=checkLighting(night,intensity);phases.push({night,sceneIntensity:intensity,recessTarget:night?.006:.03,recessRatio:ratio});}
 // A scene-only replacement must not borrow the still-valid explicit source map.
 r.scene.environment=replacementScene;checkLighting(false,1,initialEnvironment);assert.notEqual(r.scene.environment,r.mats.kourindouWoodY.envMap);
 // Exercise the production recovery method without a WebGL environment generator.
 vm.runInContext(String(read('src/render-recovery.js')),scope);const Recovery=scope.GA.DioramaRenderer;let oldEnvironmentDisposals=0;r.studioEnv.dispose=()=>oldEnvironmentDisposals++;r.makeStudioEnvironment=()=>{r.studioEnv={texture:recoveredEnvironment};r.scene.environment=recoveredEnvironment;};r.engine={shadowMap:{needsUpdate:false}};r.recovery={pending:true,rebuilt:0,lastError:'pending'};Recovery.prototype.rebuildContextCaches.call(r);
 assert.equal(oldEnvironmentDisposals,1);assert.equal(r.scene.environment,recoveredEnvironment);assert.equal(r.mats.villageSurface.envMap,null,'Recovery rebound an inherited surface');assert.equal(r.mats.kourindouWoodY.envMap,recoveredEnvironment);assert.equal(r.mats.villageStone.envMap,recoveredEnvironment);assert.equal(r.engine.shadowMap.needsUpdate,true);assert.equal(r.recovery.pending,false);assert.equal(r.recovery.rebuilt,1);assert.equal(r.recovery.lastError,null);
 checkLighting(true,.045,recoveredEnvironment);checkLighting(false,1,recoveredEnvironment);
 for(const night of [false,true])for(const intensity of [0,1e-10,1e-8,(night?.006:.03)/2,2])checkLighting(night,intensity,recoveredEnvironment);
 for(const m of[mat,pavement,road,shoulder,...Object.values(source.mats),...Object.values(source.hakureiCardMaterials),...Object.values(source.hakureiCardDepth),source.kourindouLeafDepth,...Object.values(r.mats),...Object.values(r.hakureiCardMaterials),...Object.values(r.hakureiCardDepth),r.kourindouLeafDepth])m.dispose();for(const t of[source.studioEnv.texture,initialEnvironment,replacementScene,recoveredEnvironment])t.dispose();return{newProgramKeys:3,roadProgramShared:true,kourindouSourceUnchanged:true,ordinarySurfaceSceneEnvironmentInherited:true,environmentRecoverySynced:true,productionRecoveryMethodChecked:true,lightingChecks,phases,recessZeroGuardAndClamp:true,recessDayIntensity:.03,recessNightIntensity:.006,webGLCompiled:false};
}
export function terrainSelection(G,read,meshes,pack){
 const scope=vm.createContext({GA:{...G},performance});vm.runInContext(String(read('src/renderer.js')),scope);const Base=scope.GA.DioramaRenderer;vm.runInContext(String(read('src/village-renderer.js')),scope);
 const sources=new Map(pack.meshes.map(m=>[m.id,m])),sourceRecords=new Map(pack.meshes.map(m=>[m.id,{data:m}])),renderer=Object.assign(Object.create(scope.GA.DioramaRenderer.prototype),{packs:new Map(),recordMap:sourceRecords}),records=meshes.map(m=>({data:m})),cached=new Map(),pairs=new Set();let checks=0,visible=0,choices=0,cacheChecks=0;
 for(const quality of ['low','balanced','high'])for(const displayMode of ['continuous','atlas'])for(const focus of ['village','forest'])for(const neighbors of [[],['village']])for(const ready of [false,true])for(const distance of [100,1549,1550,1551,1899,1900,1901])for(const cutaway of [false,true]){renderer.quality=quality;if(ready)renderer.packs.set('village',{id:'village'});else renderer.packs.delete('village');
  const opts={space:'surface',displayMode,focus,detailNeighbors:neighbors,cutaway},rig={eye:[0,44,32],planes:[]},physical=new Set();let count=0;
  for(const record of records){const m=record.data,source=sources.get(m.terrainSource),sourceRecord=sourceRecords.get(m.terrainSource);assert(source&&source.component==='island-terrain');assert.deepEqual(Array.from(m.terrainLodCenter),Array.from(source.center));assert.equal(m.terrainLodRadius,source.radius);assert.equal(!!m.globalNear,!!source.globalNear);assert.equal(!!m.globalFar,!!source.globalFar);
   const probe={data:{...m,owner:'village',region:'village',globalSurface:false,globalNear:false,globalFar:false,overview:m.bridgeRepresentation==='proxy'}},expected=Base.prototype.wanted.call(renderer,sourceRecord,rig,opts,distance)&&Base.prototype.wanted.call(renderer,probe,rig,opts,distance),actual=renderer.wanted(record,rig,opts,distance);
   assert.equal(actual,expected,'Footing chose different terrain/bridge representation: '+m.id);assert.equal(renderer.levelFor(record,999),0,'Footing used independent geometry LOD');checks++;
   if(record.villageBridgeProbe){if(cached.has(record))assert.equal(record.villageBridgeProbe,cached.get(record),'Cached ready replaced probe object');else cached.set(record,record.villageBridgeProbe);cacheChecks++;}
   if(actual){const key=m.bridgeZ+':'+m.bridgeSide;assert(!physical.has(key),'Two footings at one physical bridge end');physical.add(key);count++;pairs.add(m.bridgeRepresentation+':'+(m.globalNear?'near':'far'));assert.equal(record.distance,probe.distance);assert.equal(record.displayCenter,m.center);assert.equal(record.xf,record.villageBridgeProbe.xf);}
  }assert.equal(count,6,'Expected one visible footing per bridge head');visible+=count;choices++;
 }
 assert.deepEqual([...pairs].sort(),['native:far','native:near','proxy:far','proxy:near']);
 for(const record of records){const m=record.data,source=sources.get(m.terrainSource),saved=sourceRecords.get(m.terrainSource);sourceRecords.delete(m.terrainSource);assert(!renderer.wanted(record,{eye:[0,44,32],planes:[]},{space:'surface',focus:'village'},100),'Missing terrain retained a footing');sourceRecords.set(m.terrainSource,saved);checks++;
  for(const offset of [-.01,0,.01]){const rig={eye:[source.center[0]+source.radius+700+offset,source.center[1],source.center[2]],planes:[]},opts={space:'surface',displayMode:'continuous',focus:'village'},close=G.length(G.sub(rig.eye,source.center))-source.radius<700,actual=renderer.wanted(record,rig,opts,100);assert(!actual||!!m.globalNear===close);checks++;}}
 return{selectionChecks:checks,stateChoices:choices,visibleRecordsPerChoice:6,qualityIndependent:true,unreachableMixedTerrainLods:2,bridgeTerrainPairs:[...pairs].sort(),cachedProbeChecks:cacheChecks,readyValueCached:false,missingTerrainHidden:true,selectedRecords:visible};
}
function meshHeight(a,x,z,up){let found=null;for(let i=0;i<a.length;i+=27){if(up?a[i+4]<=0:a[i+4]>=0)continue;const x0=a[i],z0=a[i+2],x1=a[i+9],z1=a[i+11],x2=a[i+18],z2=a[i+20],d=(z1-z2)*(x0-x2)+(x2-x1)*(z0-z2);if(Math.abs(d)<1e-8)continue;const u=((z1-z2)*(x-x2)+(x2-x1)*(z-z2))/d,v=((z2-z0)*(x-x2)+(x0-x2)*(z-z2))/d,w=1-u-v;if(u>=-1e-5&&v>=-1e-5&&w>=-1e-5){const h=u*a[i+1]+v*a[i+10]+w*a[i+19];found=found===null?h:up?Math.max(found,h):Math.min(found,h);}}return found;}
function insidePlan(points,x,z){let area=0;for(let i=0;i<4;i++){const a=points[i],b=points[(i+1)%4];area+=a[0]*b[1]-b[0]*a[1];}const sign=Math.sign(area);return points.every((a,i)=>{const b=points[(i+1)%4];return sign*((b[0]-a[0])*(z-a[1])-(b[1]-a[1])*(x-a[0]))>=-1e-7;});}
export function publicBridgeContacts(G,atlas,meshes,{nativeEdges=null,nativeReference=null}={}){
 const V=G.VILLAGE_UPGRADE,models=new Map(meshes.map(m=>[m.id,m])),contacts=atlas.villageUpgrade.approachContacts,old=nativeReference&&new Map(nativeReference.map(m=>[m.id,m])),terrain=new G.Terrain(atlas);let contactChecks=0,meshGroundChecks=0,cornerChecks=0,nativeReplayRecords=0;const mixedLodFailures=[];
 assert.equal(models.size,24);assert.equal(meshes.reduce((n,m)=>n+V.triangles(m),0),288);assert.equal(V.bytes(meshes),31104);
 for(const lod of ['near','far']){const sampler=G.SurfaceContact.sampler(atlas,V.contactId,lod);assert.equal(contacts[lod].length,12);
  for(const c of contacts[lod]){const m=models.get(c.id);assert(m);assert(m.globalSurface&&m.overview&&m.owner==='island');assert(!m.farVertices);assert.equal(m.bridgeRepresentation,c.bridgeRepresentation);assert.equal(m.bridgeSourceId,c.bridgeSourceId);assert.deepEqual(Array.from(m.innerZRange),Array.from(c.innerZRange));assert.deepEqual(Array.from(m.outerZRange),Array.from(c.outerZRange));
   const native=c.bridgeRepresentation==='native',edge=nativeEdges?.get(c.z+':'+c.side);if(native&&edge){assert(Object.is(c.edge.x,edge.x)&&Object.is(c.edge.y,edge.y),'Authored bridge edge changed');}assert(Math.abs((c.inner-c.edge.x)*c.side-.003)<1e-6,'Bridge seam changed');assert.equal(c.top[0],c.edge.y);assert.equal(c.top[3],c.edge.y);
   if(native){assert.deepEqual(Array.from(c.innerZRange),Array.from(c.outerZRange));if(old){const original=old.get(c.id.replace(/:native$/,''));assert(original&&raw(original.vertices).equals(raw(m.vertices)),'Native public cap geometry changed');nativeReplayRecords++;}}
   else{assert(c.innerZRange[0]>=c.edge.zMin&&c.innerZRange[1]<=c.edge.zMax,'Proxy cap exceeds actual endpoint width');assert.equal(c.edge.yMin,c.edge.yMax);assert.deepEqual(Array.from(c.innerZRange),[Math.max(c.outerZRange[0],c.edge.zMin),Math.min(c.outerZRange[1],c.edge.zMax)]);}
   for(const i of [0,3]){const [x,z]=c.points[i],height=meshHeight(m.vertices,x,z,true);assert(height!==null&&Math.abs(height-c.edge.y)<4e-6,'Rendered inner corner has a bridge step');assert(Math.abs((Math.fround(x)-c.edge.x)*c.side-.003)<4e-6,'Rendered inner corner gap changed');cornerChecks++;}
   for(const p of c.samples){const [x,,z]=p;assert(insidePlan(c.points,x,z),'Contact lies outside actual convex footprint');const ground=sampler.height(x,z),t=(x-c.inner)/(c.outer-c.inner),top=c.top[0]+(c.top[1]-c.top[0])*t;assert(!terrain.water(x,z),'Footing entered water');assert(Math.abs(ground-p[1])<1e-5);assert(c.bottom<=ground-.10&&top>=ground-.03,'Footing is not grounded on selected terrain');contactChecks++;const actualTop=meshHeight(m.vertices,x,z,true),actualBottom=meshHeight(m.vertices,x,z,false);assert(actualTop!==null&&actualBottom!==null,'Clipped terrain point outside rendered cap');assert(actualTop>=ground-.030005&&actualBottom<=ground-.099995,'Rendered cap does not enclose its terrain contact');meshGroundChecks++;}
   for(let i=0;i<m.vertices.length;i+=9)assert(Math.hypot(m.vertices[i]-m.center[0],m.vertices[i+1]-m.center[1],m.vertices[i+2]-m.center[2])<=m.radius+.001,'Contact outside bounds');
  }
 }
 for(const geometryLod of ['near','far'])for(const terrainLod of ['near','far'])if(geometryLod!==terrainLod){const sampler=G.SurfaceContact.sampler(atlas,V.contactId,terrainLod);let failed=0;for(const c of contacts[geometryLod])for(const p of c.samples){const ground=sampler.height(p[0],p[2]),t=(p[0]-c.inner)/(c.outer-c.inner),top=c.top[0]+(c.top[1]-c.top[0])*t;if(!(c.bottom<=ground-.10&&top>=ground-.03))failed++;}mixedLodFailures.push({geometryLod,terrainLod,failedContacts:failed});}
 return{contactChecks,meshGroundChecks,cornerChecks,nativeReplayRecords,mixedLodFailures,fullWidthConnections:true,visualAccepted:false};
}
function detailSelection(G,read){
 const scope=vm.createContext({GA:{...G},performance});vm.runInContext(String(read('src/renderer.js')),scope);const Base=scope.GA.DioramaRenderer;Base.prototype.ensure=(record,level)=>level;vm.runInContext(String(read('src/village-renderer.js')),scope);
 const r=Object.create(scope.GA.DioramaRenderer.prototype),m={radius:70,farVertices:new Float32Array(27),villageMicro:'roof',lodDistance:125},record={data:m,level:0,distance:120};let checks=0;
 for(const quality of ['low','balanced','high']){r.quality=quality;record.distance=m.radius+50;assert.equal(r.ensure(record,1),0,'Low preset discarded close roof geometry');checks++;record.distance=m.radius+230;assert.equal(r.ensure(record,0),1,'Distant roof geometry never simplified');checks++;}
 return{decisionChecks:checks,distanceUsesClosestBatchBound:true,closeLowGeometryRetained:true,thresholdMetres:125,visualThresholdAccepted:false};
}
function authoredBridgeEdges(G,pack){
 const definitions=[-158,32,164].map(z=>({z,wood:z!==32,cx:G.canalCenter(z),half:G.canalWidth(z)+(z!==32?5:4.4),width:z!==32?6.2:9.2,col:z!==32?G.C.timber:G.C.stoneLight})),edges=new Map();
 for(const m of pack.meshes){if(m.material!=='matte'||m.instances)continue;const a=m.vertices,ix=m.index,n=ix?ix.length:a.length/9;for(let i=0;i<n;i+=3){const q=[0,1,2].map(k=>(ix?ix[i+k]:i+k)*9);if(a[q[0]+4]<.5||a[q[0]+1]<30.15||a[q[0]+1]>32.6)continue;const zs=q.map(k=>a[k+2]),lo=Math.min(...zs),hi=Math.max(...zs);
  for(const d of definitions){if(a[q[0]+4]<(d.wood?.9999:.5)||Math.abs(lo-(d.z-d.width/2))>1e-4||Math.abs(hi-(d.z+d.width/2))>1e-4||q.some(k=>Math.abs(a[k]-d.cx)>d.half+.24)||[0,1,2].some(k=>Math.abs(a[q[0]+6+k]-d.col[k])>2e-6))continue;
   for(const side of [-1,1])for(const k of q){const key=d.z+':'+side,edge=edges.get(key);if(!edge||side*a[k]>side*edge.x+1e-6)edges.set(key,{x:a[k],y:a[k+1]});}
  }
 }}assert.equal(edges.size,6,'Original authored bridge top edges missing');return edges;
}
export async function checkVillage(G,atlas,characters,read,{draft=false,reference=null,onProgress=null,onExport=null}={}){
 const V=G.VILLAGE_UPGRADE;assert(V&&V.version===3);let fixture=null;try{fixture=JSON.parse(read('tools/village-baseline.json'));}catch(e){if(!draft||e.code!=='ENOENT')throw e;}
 if(fixture)for(const [name,digest]of Object.entries(fixture.protectedFiles||{}))assert.equal(hash(read(name)),digest,'Protected source changed: '+name);
 const layout=JSON.stringify([G.PRESETS.riverside,G.PRESETS.street,G.PRESETS.bridge,G.ISLAND.allRoutes,atlas.placements]),old=await V.originalBuildRegion(atlas,'village',''),current=await G.buildRegion(atlas,'village','');
 const build={...current.meta.villageUpgrade.timings,workerFinishMs:current.meta.villageUpgrade.workerFinishMs,totalMs:current.builtMs,originalStandaloneMs:old.builtMs};onProgress?.({stage:'build',cpuCost:{build},sourceBytes:current.bytes});
 assert.equal(geometryDigest(old),'2875880afaab25b7a49f7845ac6e7be50496a4485839399f5e1b7fe145a6993c','Original village baseline changed');
 assert.equal(JSON.stringify(current.meta.houses),JSON.stringify(old.meta.houses));assert.equal(JSON.stringify(current.meta.gardens),JSON.stringify(old.meta.gardens));assert.equal(JSON.stringify(current.meta.refinement),JSON.stringify(old.meta.refinement));assert.equal(current.meta.houses.length,226);assert.equal(current.meta.gardens.length,140);
 assert.equal(current.meshes.length,old.meshes.length);const originals=new Map(old.meshes.map(m=>[m.id,m])),seen=new Set();let replayed=0;
 for(const m of current.meshes){assert(!seen.has(m.id),'Duplicate village record');seen.add(m.id);const original=originals.get(m.id);assert(original,'Unexpected detail record: '+m.id);replayed+=replay(original,m);
  for(const k of ['instances','instanceColors'])if(original[k])assert(raw(original[k]).equals(raw(m[k])),'Instance placement/colour changed: '+m.id);
  for(const k of ['vertices','farVertices','instances','instanceColors'])if(m[k])assert(m[k].every(Number.isFinite),'Non-finite '+m.id+'/'+k);
  if(m.index)assert(m.index.every(i=>i<m.vertices.length/9),'Out-of-range source index');if(m.farVertices)assert(m.farVertices.length%27===0);
  if(reference&&m.villageMicro)assert(raw(m.farVertices).equals(raw(reference.microFar(original.vertices))),'Far triangle bits/order changed: '+m.id);
 }
 const detail=stats(V,current.meshes);assert.equal(current.bytes,detail.sourceBytes);assert(detail.sourceBytes<=170737688,'Source budget exceeded');assert.equal(detail.expandedTriangles,2623234,'Near triangle geometry changed');assert(detail.farExpandedTriangles<detail.expandedTriangles,'No actual distant simplification');assert.equal(current.meshes.filter(m=>m.villageMicro).length,32);
 const {attributeTriangles,coldAcquire,finishDigests}=detailAttributes(V,read,current.meshes,reference);assert(build.originalBuildMs>=0&&build.upgradeMs>=0);assert(Math.abs(build.originalBuildMs+build.upgradeMs-build.totalMs)<1e-6,'Production builtMs omitted upgrade time');onProgress?.({stage:'attributes',cpuCost:{build,coldAcquire},finishDigests,detail});
 // Both endpoints of a long beam/post use its structural grain axis.
 for(const [axis,dim]of [[0,[5,.2,.2]],[1,[.2,5,.2]],[2,[.2,.2,5]]]){const g=new G.Geometry();g.box(0,0,0,...dim,G.C.wood);const a=g.mesh('grain-test').vertices,m={...V.indexed(a)};const c=V.channels(m);for(let i=0;i<c.length;i+=2){assert.equal(c[i],0);assert.equal(c[i+1],axis);}}
 const z=gunzipSync(read('assets/packs/overview.pack.gz')),pack=G.decodePack(z.buffer.slice(z.byteOffset,z.byteOffset+z.byteLength));G.LANDSCAPE.apply(pack,new G.Terrain(atlas));G.applyHighlandGround(pack,new G.Terrain(atlas));
 const other=pack.meshes.filter(m=>!V.targetProxyIds.includes(m.id)),before=geometryDigest({meshes:other}),targets=pack.meshes.filter(m=>V.targetProxyIds.includes(m.id)),targetArrays=targets.map(m=>({...m})),overviewMeshes=pack.meshes,overviewBackingBefore=V.bytes(pack.meshes),publicStart=performance.now(),additions=V.publicEnvironment(atlas,pack),publicEnvironmentMs=performance.now()-publicStart;
 assert.equal(pack.meshes,overviewMeshes,'Overview mesh array replaced');assert.equal(V.bytes(pack.meshes),overviewBackingBefore,'Overview gained new proxy backing');
 assert.equal(geometryDigest({meshes:pack.meshes.filter(m=>!V.targetProxyIds.includes(m.id))}),before,'Non-target overview geometry changed');
 let proxyReplayTriangles=0;for(const m of targetArrays){const now=pack.meshes.find(n=>n.id===m.id);proxyReplayTriangles+=replay(m,now);assert.equal(now,targets.find(n=>n.id===m.id),'Original overview record replaced');assert.equal(now.material,m.material,'Original overview material changed');for(const k of ['vertices','farVertices','instances','instanceColors','index'])assert.equal(now[k],m[k],'Original overview view changed: '+k);}
 assert.equal(additions.length,24);const bridgeChecks=publicBridgeContacts(G,atlas,additions,{nativeEdges:authoredBridgeEdges(G,old)}),contactChecks=bridgeChecks.contactChecks,mixedLodFailures=bridgeChecks.mixedLodFailures;
 const publicStats=stats(V,additions);assert.equal(publicStats.expandedTriangles,288);assert(publicStats.sourceBytes+atlas.villageUpgrade.contactBytes<=100*1024,'Public bridge/contact budget exceeded');const afterMeshes=pack.meshes;assert.equal(V.publicEnvironment(atlas,pack).length,0);assert.equal(pack.meshes,afterMeshes,'Repeated upgrade changed source');
 const selection=terrainSelection(G,read,additions,pack),segments=V.routeSegments();assert(segments.length<=32);let routeSamples=0,maxRouteError=0;
 for(const id of [...new Set(segments.map(p=>p.id))]){const group=segments.filter(p=>p.id===id),route=G.ISLAND.allRoutes.find(p=>p.id===id),origin=group[0].origin;for(const p of route.samples){if(Math.hypot(p[0]-origin[0],p[1]-origin[1])>group[0].range)continue;let nearest=Infinity;for(const s of group){const dx=s.b[0]-s.a[0],dz=s.b[1]-s.a[1],u=Math.max(0,Math.min(1,((p[0]-s.a[0])*dx+(p[1]-s.a[1])*dz)/(dx*dx+dz*dz||1)));nearest=Math.min(nearest,Math.hypot(p[0]-s.a[0]-u*dx,p[1]-s.a[1]-u*dz));}assert(nearest<=.2,'Village route shader missed retained path');maxRouteError=Math.max(maxRouteError,nearest);routeSamples++;}}
 assert.equal(JSON.stringify([G.PRESETS.riverside,G.PRESETS.street,G.PRESETS.bridge,G.ISLAND.allRoutes,atlas.placements]),layout,'Camera, route or placement changed');
 const audit=G.auditLandmarks(atlas);assert.equal(audit.navigable,109);assert.equal(audit.pending,70);assert.equal(characters.characters.length,85);
 const digests={near:geometryDigest(current),public:geometryDigest({meshes:additions}),overviewTargets:geometryDigest({meshes:pack.meshes.filter(m=>V.targetProxyIds.includes(m.id))})};if(fixture)for(const [key,digest]of Object.entries(digests))assert.equal(digest,fixture.geometry[key],'Reviewed village fixture changed: '+key);
 if(fixture){assert(fixture.finishDigests,'Explicit Worker finish fixture missing');assert.deepEqual(finishDigests,fixture.finishDigests,'Reviewed finish/axis stream changed');}
 onProgress?.({stage:'before-resources',cpuCost:{build,coldAcquire,publicEnvironmentMs,controlledBenchmark:false,performanceAccepted:false},digests,finishDigests,detail,attributeTriangles,replayedTriangles:replayed,contactChecks,proxyConnections:atlas.villageUpgrade.proxyConnections});
 const resources=rendererResources(G,read);
 const result={fixtureFrozen:!!fixture,detail:{...detail,lod:detailSelection(G,read)},overviewTargets:{...stats(V,pack.meshes.filter(m=>V.targetProxyIds.includes(m.id))),originalSourceBytes:atlas.villageUpgrade.proxySourceBytes,replayedTriangles:proxyReplayTriangles,originalRecordsAndViewsPreserved:true,additionalProxyBackingBytes:0},public:{...publicStats,...bridgeChecks,contactBytes:atlas.villageUpgrade.contactBytes,overviewBackingDeltaBytes:V.bytes([...pack.meshes,...additions])-overviewBackingBefore,selection,mixedLodFailures,proxyConnections:atlas.villageUpgrade.proxyConnections},replayedTriangles:replayed,attributeTriangles,contactChecks,routeSamples,maxRouteError,resources,shader:shaderComposition(G,read),cpuCost:{build,coldAcquire,publicEnvironmentMs,controlledBenchmark:false,performanceAccepted:false},digests,finishDigests,visualAcceptance:false};
 onExport?.({original:old,candidate:current,overview:pack,addedRecords:additions});return result;
}
