// Bounded structural checks. CPU/Three.js rays only, never WebGL or fixture writes.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {gunzipSync} from 'node:zlib';
import {performance} from 'node:perf_hooks';
import vm from 'node:vm';
import fs from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import * as T from '../vendor/three/three.module.js';
import {geometryDigest} from './check-hakurei.mjs';

const hash=b=>createHash('sha256').update(b).digest('hex');
const raw=a=>Buffer.from(a.buffer,a.byteOffset,a.byteLength);
const unchanged={
 'src/world-builder.js':'d724340f60e9b759d68803ddfe1c4e16048272e6f8e2bb81bfa6e273ffe7378e',
 'assets/packs/overview.pack.gz':'7398a263bf02d560fd0c9265d9e297ec3b22357f2429c4732ee3488f2d097742',
 'assets/packs/legacy.pack.gz':'46e874f6bcdff56d4772e531fd19bf8a71ba5f272aa39b14a91e5ed65082ab88',
 'data/atlas.json':'74b17d519eb23f9d6d26f7ca76e2d02a87978a7c0761b4bd22719d286c73e37a',
 'data/characters.json':'b87604e876804b5b9469657adf653451eccd561cddecdbb578f8966745beacc9'
};
const routePoints=[[220,32],[280,32],[420,48],[575,91],[710,113],[820,170],[912,208],[1040,245],[1170,255],[1300,284],[1380,252],[1428,194],[1458,160]];
function geometry(m){const g=new T.BufferGeometry(),b=new T.InterleavedBuffer(m.vertices,9);g.setAttribute('position',new T.InterleavedBufferAttribute(b,3,0));if(m.index)g.setIndex(new T.BufferAttribute(m.index,1));g.computeBoundingSphere();return g;}
function object(m){const mesh=new T.Mesh(geometry(m),new T.MeshBasicMaterial({side:T.DoubleSide}));mesh.updateMatrixWorld();return mesh;}
function closeObject(m){m.geometry.dispose();m.material.dispose();}
const ray=new T.Raycaster();
function hits(mesh,from,direction){ray.set(new T.Vector3(...from),new T.Vector3(...direction));return ray.intersectObject(mesh,false);}
let boundaryRayNudges=0;
function yAt(mesh,x,z,expected=null){const probe=(dx,dz)=>hits(mesh,[x+dx,200,z+dz],[0,-1,0]).filter(h=>expected===null||Math.abs(h.point.y-expected)<.002);let q=probe(0,0);
 // Float32 boundary rays may miss by micrometres. Record the controlled move;
 // its upper bound is not a bound on the physical gap between two objects.
 if(!q.length)for(const [dx,dz]of [[.00006,0],[-.00006,0],[0,.00006],[0,-.00006],[.00006,.00006],[.00006,-.00006],[-.00006,.00006],[-.00006,-.00006]]){q=probe(dx,dz);if(q.length){boundaryRayNudges++;break;}}
 assert(q.length,'Ray missed actual triangle at '+x+','+z);return q[0].point.y;}
function triangles(m,start=0,length=null){const out=[],a=m.vertices,ix=m.index,end=ix?ix.length:length===null?a.length/9:(start+length)/9;for(let i=start/9;i<end;i+=3)out.push([0,1,2].map(j=>{const k=(ix?ix[i+j]:i+j)*9;return[a[k],a[k+1],a[k+2]];}));return out;}
function contains(p,tri){const a=tri.map(q=>new T.Vector3(q[0],0,q[2])),v=T.Triangle.getBarycoord(new T.Vector3(p[0],0,p[1]),...a,new T.Vector3());return !!v&&Math.min(v.x,v.y,v.z)>-1e-6;}
function planeY(p,tri){const a=tri.map(q=>new T.Vector3(q[0],0,q[2])),v=T.Triangle.getBarycoord(new T.Vector3(p[0],0,p[1]),...a,new T.Vector3());return v.x*tri[0][1]+v.y*tri[1][1]+v.z*tri[2][1];}
function crossing(a,b,c,d){const u=[b[0]-a[0],b[1]-a[1]],v=[d[0]-c[0],d[1]-c[1]],den=u[0]*v[1]-u[1]*v[0];if(Math.abs(den)<1e-9)return null;const w=[c[0]-a[0],c[1]-a[1]],s=(w[0]*v[1]-w[1]*v[0])/den,t=(w[0]*u[1]-w[1]*u[0])/den;return s>=-1e-7&&s<=1+1e-7&&t>=-1e-7&&t<=1+1e-7?[a[0]+s*u[0],a[1]+s*u[1]]:null;}
// Extrema of two piecewise affine surfaces occur at their overlay vertices.
// This independently intersects real terrain triangles and every ramp-top tri.
function overlay(a,b){const p=a.map(q=>[q[0],q[2]]),q=b.map(q=>[q[0],q[2]]),out=[...p.filter(v=>contains(v,b)),...q.filter(v=>contains(v,a))];for(let i=0;i<3;i++)for(let j=0;j<3;j++){const v=crossing(p[i],p[(i+1)%3],q[j],q[(j+1)%3]);if(v)out.push(v);}return out;}
function replaySegments(before,after,patches){let source=0,dest=0,retained=0;for(const p of patches){const n=p.start-source;assert(raw(before.subarray(source,p.start)).equals(raw(after.subarray(dest,dest+n))),'Retained mixed-batch prefix changed');retained+=n;dest+=n+p.newFloats;source=p.end;}assert(raw(before.subarray(source)).equals(raw(after.subarray(dest))),'Retained mixed-batch suffix changed');return(retained+before.length-source)/27;}
function actualPatch(m,name){let delta=0;for(const p of m.trailRepairs){if(p.name===name)return m.vertices.subarray(p.start+delta,p.start+delta+p.newFloats);delta+=p.newFloats-(p.end-p.start);}throw Error('Missing candidate patch '+name);}
function outwardNormals(a,center,start,count){let minimum=Infinity;for(let i=start;i<start+count;i+=27){const p=[0,1,2].map(k=>(a[i+k]+a[i+9+k]+a[i+18+k])/3),normal=new T.Vector3(a[i+3],a[i+4],a[i+5]);assert(Math.abs(normal.length()-1)<.00001);const dot=normal.x*(p[0]-center[0])+normal.z*(p[2]-center[1]);minimum=Math.min(minimum,dot);assert(dot>.00001,'New closed-shell normal faces inward');}return{triangles:count/27,minimumOutwardDot:minimum};}
function bridgeHeadSelection(U,data,overview,caps){const p=data.trailUpgrade.bridge,road=overview.meshes.find(m=>m.id===U.roadId),candidates=[];
 // Independent selection proof from actual indexed road edges, rather than
 // replaying the route-sample search used by the author module.
 for(let i=0;i<road.index.length;i+=6){const points=[road.index[i],road.index[i+1]].map(k=>Array.from(road.vertices.subarray(k*9,k*9+3)));if(!points.every(q=>q[0]>=U.bounds[0]&&q[0]<p.left&&q[2]>=U.bounds[1]&&q[2]<=U.bounds[3]))continue;const center=points[0].map((v,k)=>(v+points[1][k])*.5),width=Math.hypot(points[1][0]-points[0][0],points[1][2]-points[0][2]);assert(Math.abs(width-5)<.00005);candidates.push({indexOffset:i,points,center,planDistance:Math.hypot(center[0]-p.left,center[2]-p.z)});}
 candidates.sort((a,b)=>a.planDistance-b.planDistance);assert(candidates.length);const west=data.trailUpgrade.sections.find(s=>s.side===-1),east=data.trailUpgrade.sections.find(s=>s.side===1);assert.equal(west.indexOffset,candidates[0].indexOffset,'West did not use the nearest complete original road section');assert.equal(west.indexOffset,744,'Reviewed west source section changed');assert.deepEqual(JSON.parse(JSON.stringify(west.points)),candidates[0].points);assert.deepEqual(JSON.parse(JSON.stringify(east.points)),[[878.5128173828125,36.58187484741211,193.10243225097656],[876.6771240234375,37.00434494018555,197.75326538085938]],'Original east contact changed');
 for(const cap of caps)for(const head of cap.trailHeads)assert.deepEqual(JSON.parse(JSON.stringify(head.outer)),JSON.parse(JSON.stringify((head.side<0?west:east).points)));
 const previous=candidates.find(s=>s.indexOffset===738);assert(previous);assert(candidates[0].planDistance<previous.planDistance-2,'West bridge head was not shortened');return{originalCompleteCandidates:candidates.length,selectedWestIndex:west.indexOffset,selectedWestPlanDistance:candidates[0].planDistance,previousWestPlanDistance:previous.planDistance,westPlanReduction:previous.planDistance-candidates[0].planDistance,eastContactPreserved:true,sourceEdgesUnchanged:true};
}
function bridgeHeadFinish(G,caps){const rows=[];let sideVertices=0,bearingVertices=0;for(const cap of caps)for(const head of cap.trailHeads){const a=cap.vertices,colors=[];for(let r=0;r<head.rows;r++){const start=head.topFloatOffset+r*head.cols*54,color=Array.from(a.subarray(start+6,start+9));for(let i=start;i<start+head.cols*54;i+=9)for(let k=0;k<3;k++)assert.equal(a[i+6+k],color[k],'One transverse band varies across width');const factors=color.map((v,k)=>v/G.C.timber[k]);assert(factors.every(v=>v>.95&&v<1.05));if(r)assert.notDeepEqual(color,colors[r-1],'Bridge head still has one flat top color');colors.push(color);}const extrema=colors.flatMap(c=>c.map((v,k)=>v/G.C.timber[k]));assert(Math.max(...extrema)/Math.min(...extrema)-1<.065,'Bridge-head band contrast exceeds the bounded finish');rows.push({lod:cap.globalFar?'far':'near',side:head.side,bands:colors.length,minTimberFactor:Math.min(...extrema),maxTimberFactor:Math.max(...extrema)});
  for(const [start,count,part]of [[head.bottomFloatOffset+head.topFloats,head.rows*8*27,'side'],[head.footingFloatOffset,head.footings.length*12*27,'bearing']])for(let i=start;i<start+count;i+=9){for(let k=0;k<3;k++)assert.equal(a[i+6+k],Math.fround(G.C.wood[k]),'Bridge-head '+part+' is not the inherited mid wood color');if(part==='side')sideVertices++;else bearingVertices++;}}
 return{rows,sideVertices,bearingVertices,additionalTriangles:0,additionalAttributes:0,additionalMaterials:0};
}
function retainedBeamClearance(native,caps){const results=[];for(const cap of caps){const head=cap.trailHeads.find(h=>h.side===-1),tops=triangles(cap,head.topFloatOffset,head.topFloats),bottoms=triangles(cap,head.bottomFloatOffset,head.topFloats);for(const start of [300,402]){const beam=triangles(native,(start+8)*27,2*27);let topMinimum=Infinity,bottomMinimum=Infinity,topPoints=0,bottomPoints=0;for(const original of beam){for(const actual of tops)for(const point of overlay(original,actual)){topMinimum=Math.min(topMinimum,planeY(point,actual)-planeY(point,original));topPoints++;}for(const actual of bottoms)for(const point of overlay(original,actual)){bottomMinimum=Math.min(bottomMinimum,planeY(point,actual)-planeY(point,original));bottomPoints++;}}
  assert(topPoints>0&&bottomPoints>0&&Number.isFinite(topMinimum)&&Number.isFinite(bottomMinimum),'No real retained-beam/cap overlay checked');assert(topMinimum>=.19995,'Retained longitudinal beam crosses new cap top');assert(bottomMinimum>=.01995,'Retained longitudinal beam crosses new shell underside');results.push({lod:cap.globalFar?'far':'near',originalBeamTriangles:[start+8,start+9],topOverlayPoints:topPoints,bottomOverlayPoints:bottomPoints,minimumTopClearance:topMinimum,minimumUndersideClearance:bottomMinimum,designedUndersideMargin:.02,allowedFloat32Error:.00005});}}
 const cap=caps.find(m=>!m.globalFar),nativeMesh=object(native),capMesh=object(cap),camera=new T.PerspectiveCamera(49,1280/720,.1,5000),pixels=[];camera.position.set(852,43.2,203);camera.lookAt(870,37.3,191);camera.updateMatrixWorld();try{for(const [x,y]of [[225,507],[225,505],[225,510],[218,509],[232,507],[225,515]]){ray.setFromCamera(new T.Vector2((x+.5)/1280*2-1,1-(y+.5)/720*2),camera);const first=ray.intersectObjects([nativeMesh,capMesh],false)[0],head=cap.trailHeads.find(h=>h.side===-1);assert(first&&first.object===capMesh,'Blocked bridge-head pixel still exposes original beam');assert(first.faceIndex>=head.topFloatOffset/27&&first.faceIndex<(head.topFloatOffset+head.topFloats)/27,'Blocked pixel hit a side/footing instead of cap top');pixels.push({pixel:[x,y],firstRecord:cap.id,faceIndex:first.faceIndex,worldPoint:first.point.toArray()});}}finally{closeObject(nativeMesh);closeObject(capMesh);}return{results,pixels,scope:'Original beam top faces against independent actual cap top/underside triangles; bounded CPU pixel replay, no WebGL'};
}
const plasterReference=[[0,.52,-2.8,13.4,.98,5.2],[0,3.15,-2.8,13.4,1.77,5.2],[0,1.5,-3.075,12.3,1.65,4.65],...[-1,1].flatMap(s=>[[s*6.425,1.5,-4.65,.55,1.65,1.5],[s*6.425,1.5,-1.125,.55,1.65,.75],[s*6.5,1.5,-.475,.4,1.65,.55]])];
function kitchenShell(G,house,position){const a=actualPatch(house,'kitchen'),plaster=triangles({vertices:a.subarray(0,60*27)}),inside=p=>plasterReference.some(([x,y,z,w,h,d])=>p[0]>x-w/2&&p[0]<x+w/2&&p[1]>y&&p[1]<y+h&&p[2]>z-d/2&&p[2]<z+d/2),local=p=>[position[0]-p[0],p[1]-position[1],position[2]-p[2]],rearZ=Math.fround(position[2]+5.4),rear=[];
 assert.equal(a.length,17172);assert.equal(hash(raw(a.subarray(60*27))),'e98869ed3921750e8bd349c7f458ac17e3d77b54e39ec6de1551b463bced0f7c','Kitchen window/wood geometry changed');
 let minimumArea=Infinity,internalLidsAtRear=0;for(let i=0;i<plaster.length;i++){const tri=plaster[i],normal=[-a[i*27+3],a[i*27+4],-a[i*27+5]],center=local(tri.reduce((n,p)=>n.map((v,k)=>v+p[k]/3),[0,0,0]));for(let j=0;j<27;j+=9)for(let k=0;k<3;k++)assert.equal(a[i*27+j+6+k],Math.fround(G.C.plaster[k]));assert(Math.abs(Math.hypot(...normal)-1)<.00001);assert(inside(center.map((v,k)=>v-normal[k]*.001))&&!inside(center.map((v,k)=>v+normal[k]*.001)),'Kitchen shell contains an interior face or inward normal');const area=new T.Triangle(...tri.map(p=>new T.Vector3(...p))).getArea();assert(area>.000001);minimumArea=Math.min(minimumArea,area);if(tri.every(p=>p[2]===rearZ))rear.push(tri);if(Math.abs(normal[1])>.9&&[1.5,3.15].some(y=>tri.every(p=>p[1]===Math.fround(position[1]+y)))&&tri.some(p=>p[2]===rearZ))internalLidsAtRear++;}
 assert.equal(rear.length,2,'Rear wall must be one continuous quad');assert.equal(internalLidsAtRear,0,'An internal contact lid still reaches the rear wall');const expected=new Set([-6.7,6.7].flatMap(x=>[.52,4.92].map(y=>JSON.stringify([Math.fround(position[0]-x),Math.fround(position[1]+y),rearZ])))),actual=new Set(rear.flat().map(p=>JSON.stringify(p)));assert.deepEqual(actual,expected,'Original plaster outer boundary changed');
 const mesh=object({vertices:a});let rearRays=0;try{for(const x of [-4,0,4])for(const y of [1.498,1.5,1.502,3.148,3.15,3.152]){const q=hits(mesh,[position[0]-x,position[1]+y,rearZ+1],[0,0,-1]);assert(q.length&&Math.abs(q[0].point.z-rearZ)<.00001,'Rear wall has a gap at a former split level');assert(q[0].face.normal.z>.99,'Former split ray exposes a contact lid');rearRays++;}}finally{closeObject(mesh);}return{plasterTriangles:plaster.length,originalPlasterTriangles:108,minimumTriangleArea:minimumArea,externalBoundaryChecks:plaster.length,rearWallTriangles:rear.length,rearRays,internalLidsAtRear,windowWoodFloatsPreserved:a.length-60*27,testedFaceCentersMatchOriginalVolume:true};
}
function kitchenWindowRays(sourceHouse,house,position){const [x,y,z]=position,place=q=>[x-q[0],y+q[1],z-q[2]],old=object(sourceHouse),now=object(house),windows=[];try{for(const [name,from,direction]of [['front-right',[1.6,2.1,1],[0,0,1]],['front-left',[-1.6,2.1,1],[0,0,1]],['left-centre',[-8,2.35,-2.7],[-1,0,0]],['right-centre',[8,2.35,-2.7],[1,0,0]],['left-bay',[-8,2.35,-2.86],[-1,0,0]],['right-bay',[8,2.35,-2.86],[1,0,0]]]){const a=hits(old,place(from),direction),b=hits(now,place(from),direction);assert(a.length&&b.length,'Window lacks an opaque backing: '+name);assert(b[0].distance-a[0].distance>.45,'Window remains a surface patch: '+name);assert(b[0].distance-a[0].distance<.8,'Window became a full interior: '+name);windows.push({name,originalDepth:a[0].distance,repairedDepth:b[0].distance,actualRecess:b[0].distance-a[0].distance});}}finally{closeObject(old);closeObject(now);}return windows;}
function structuralRays(G,U,original,candidate,caps,overview){
 const p=U.profile(new G.Terrain(original.atlas)),native=candidate.meshes.find(m=>m.id===U.bridgeId),proxy=overview.meshes.find(m=>m.id===U.proxyId),road=overview.meshes.find(m=>m.id===U.roadId),near=object(native),far=object(proxy),roadObject=object(road);let endpointRays=0,roadWidthRays=0,terrainOverlayPoints=0,footingRays=0;
 const margins=[],joins=[],roadEdges=[],shells=[],normals=[outwardNormals(proxy.vertices,[p.x,p.z],4*27,8*27)];let maximumMetadataRounding=0;
 try{
  for(const cap of caps){const mesh=object(cap),source=overview.meshes.find(m=>m.id===cap.terrainSource),terrain=object(source),terrainTris=triangles(source).filter(tri=>Math.max(...tri.map(q=>q[0]))>=U.bounds[0]&&Math.min(...tri.map(q=>q[0]))<=U.bounds[2]&&Math.max(...tri.map(q=>q[2]))>=U.bounds[1]&&Math.min(...tri.map(q=>q[2]))<=U.bounds[3]);try{
   for(const head of cap.trailHeads){
    for(let i=0;i<=8;i++){const v=i/8,inner=head.inner[0].map((x,k)=>x+(head.inner[1][k]-x)*v),outer=head.outer[0].map((x,k)=>x+(head.outer[1][k]-x)*v);assert(Math.abs(yAt(mesh,...[inner[0],inner[2]])-p.deckY)<.00002);assert(Math.abs(yAt(near,inner[0],inner[2],p.deckY)-p.deckY)<.00002);assert(Math.abs(yAt(far,inner[0],inner[2],p.deckY)-p.deckY)<.00002);endpointRays+=3;assert(Math.abs(yAt(mesh,outer[0],outer[2])-outer[1])<.0002);assert(Math.abs(yAt(roadObject,outer[0],outer[2])-outer[1])<.0002);roadWidthRays+=2;}
    const capTris=triangles(cap,head.topFloatOffset,head.topFloats);let minimum=Infinity,headOverlay=0;
    const edge=[],a=head.outer[0],b=head.outer[1],dx=b[0]-a[0],dz=b[2]-a[2],length=dx*dx+dz*dz;let planDeviation=0,heightDeviation=0;
    for(const tri of capTris)for(const q of tri){const u=((q[0]-a[0])*dx+(q[2]-a[2])*dz)/length,d=Math.hypot(q[0]-a[0]-u*dx,q[2]-a[2]-u*dz);if(u>=-1e-6&&u<=1+1e-6&&d<.001&&!edge.some(v=>v.every((x,k)=>x===q[k]))){edge.push(q);planDeviation=Math.max(planDeviation,d);heightDeviation=Math.max(heightDeviation,Math.abs(q[1]-a[1]-(b[1]-a[1])*u));}}
    assert.equal(edge.length,head.cols+1,'Real ramp edge does not span the complete road section');assert(planDeviation<.00004&&heightDeviation<.00002);for(const endpoint of head.outer)assert(edge.some(q=>q.every((v,k)=>v===endpoint[k])),'Road endpoint Float32 changed');roadEdges.push({lod:cap.globalFar?'far':'near',side:head.side,actualBoundaryPlanDeviation:planDeviation,actualBoundaryHeightDeviation:heightDeviation});
    for(const a of capTris)for(const b of terrainTris)for(const point of overlay(a,b)){minimum=Math.min(minimum,planeY(point,a)-planeY(point,b));terrainOverlayPoints++;headOverlay++;}
    assert(headOverlay>0&&Number.isFinite(minimum),'No real terrain/ramp overlay was checked');assert(minimum>.05,'Actual terrain penetrates a bridge head');margins.push({lod:cap.globalFar?'far':'near',side:head.side,minimumTopClearance:minimum,minimumUndersideClearance:minimum-.18,overlayPoints:headOverlay});
    let maxThicknessError=0;for(let i=0;i<head.topFloats;i+=27)for(const [t,b]of [[0,0],[9,18],[18,9]]){const top=head.topFloatOffset+i+t,bottom=head.bottomFloatOffset+i+b;assert.equal(cap.vertices[top],cap.vertices[bottom]);assert.equal(cap.vertices[top+2],cap.vertices[bottom+2]);maxThicknessError=Math.max(maxThicknessError,Math.abs(cap.vertices[top+1]-cap.vertices[bottom+1]-.18));}assert(maxThicknessError<.000006);shells.push({lod:cap.globalFar?'far':'near',side:head.side,mirrorTriangles:head.topFloats/27,maxThicknessError,allowedThicknessError:.000006});
    const center=head.points.reduce((n,q)=>[n[0]+q[0]/4,n[1]+q[2]/4],[0,0]);normals.push(outwardNormals(cap.vertices,center,head.bottomFloatOffset+head.topFloats,head.rows*8*27));
    const underside=object({vertices:cap.vertices.subarray(head.bottomFloatOffset,head.bottomFloatOffset+head.topFloats)});
    try{for(let f=0;f<head.footings.length;f++){const foot=head.footings[f],start=head.footingFloatOffset+f*12*27,bearingArray=cap.vertices.subarray(start,start+12*27),bearingObject=object({vertices:bearingArray}),points=[];for(let i=0;i<bearingArray.length;i+=9){const point=[bearingArray[i],bearingArray[i+2]];if(!points.some(q=>q[0]===point[0]&&q[1]===point[1]))points.push(point);}assert.equal(points.length,4);for(const point of foot.points)maximumMetadataRounding=Math.max(maximumMetadataRounding,Math.hypot(point[0]-Math.fround(point[0]),point[1]-Math.fround(point[1])));const center=points.reduce((n,q)=>[n[0]+q[0]/4,n[1]+q[1]/4],[0,0]);normals.push(outwardNormals(bearingArray,center,4*27,8*27));let minRoofGap=Infinity,maxRoofGap=-Infinity;try{for(const point of [...points,center]){const ground=yAt(terrain,...point);assert(foot.bottom<=ground-.075,'Bearing floats above actual terrain');const bottom=yAt(underside,...point),bearing=yAt(bearingObject,...point),gap=bottom-bearing;minRoofGap=Math.min(minRoofGap,gap);maxRoofGap=Math.max(maxRoofGap,gap);footingRays++;}}finally{closeObject(bearingObject);}assert(maxRoofGap<.00005&&minRoofGap>-.00005,'Bearing fails to join the real shell');assert.equal(capTris.filter(tri=>points.every(point=>contains(point,tri))).length,1,'Bearing crosses a real ramp fold');const v=f===0?.18:.82,u=head.collar?head.collar.u*.25*head.rows:.25,target=head.inner[0].map((n,k)=>G.mix(G.mix(n,head.inner[1][k],v),G.mix(head.outer[0][k],head.outer[1][k],v),u));joins.push({lod:cap.globalFar?'far':'near',side:head.side,footing:f,actualWidth:Math.max(...points.map(q=>q[0]))-Math.min(...points.map(q=>q[0])),actualDepth:Math.max(...points.map(q=>q[1]))-Math.min(...points.map(q=>q[1])),actualCenterShift:Math.hypot(center[0]-target[0],center[1]-target[2]),rampTriangle:foot.rampTriangle,minRoofGap,maxRoofGap,allowedRoofGap:.00005});}}finally{closeObject(underside);}
   }
  }finally{closeObject(mesh);closeObject(terrain);}}
 }finally{closeObject(near);closeObject(far);closeObject(roadObject);}
 const sourceHouse=original.meshes.find(m=>m.id===U.houseId),house=candidate.meshes.find(m=>m.id===U.houseId),position=original.meta.mystia.position,[x,y,z]=position,windows=kitchenWindowRays(sourceHouse,house,position);
 const a=actualPatch(house,'awning'),under=a.subarray(98*27,100*27),roof=object({vertices:under}),plane=new T.Plane().setFromCoplanarPoints(...triangles({vertices:under})[0].map(p=>new T.Vector3(...p)));if(plane.normal.y<0)plane.negate();let postRays=0;const struts=[];
 try{for(let i=0;i<4;i++){const columnArray=a.subarray(i*24*27,(i*24+12)*27),column=object({vertices:columnArray}),points=[];for(let j=0;j<columnArray.length;j+=9){const point=[columnArray[j],columnArray[j+2]];if(!points.some(q=>q[0]===point[0]&&q[1]===point[1]))points.push(point);}assert.equal(points.length,4);const center=points.reduce((n,q)=>[n[0]+q[0]/4,n[1]+q[1]/4],[0,0]);normals.push(outwardNormals(columnArray,center,4*27,8*27));try{for(const point of [...points,center]){const top=yAt(column,...point),bottom=yAt(roof,...point);assert(Math.abs(top-bottom)<.00004,'Actual column top misses actual canopy underside');postRays++;}}finally{closeObject(column);}
   const start=(i*24+12)*27,tube=a.subarray(start,start+12*27);let minimum=Infinity,maximum=-Infinity;for(let k=0;k<tube.length;k+=9){const distance=plane.distanceToPoint(new T.Vector3(...tube.subarray(k,k+3)));minimum=Math.min(minimum,distance);maximum=Math.max(maximum,distance);}assert(minimum<-.02&&maximum>.02,'Actual strut tube never intersects canopy underside');assert(maximum<.09,'Strut protrudes too deeply through canopy');struts.push({minimumDistance:minimum,maximumDistance:maximum});
  }}finally{closeObject(roof);}
 normals.push(outwardNormals(a,[x,z-4.75],100*27,8*27));
 return{endpointRays,roadWidthRays,roadEdges,shells,terrainOverlayPoints,margins,footingRays,joins,windowRays:windows,postRays,struts,outwardNormals:normals,maximumMetadataRounding,boundaryRayNudges,boundaryRayMaximumMoveMeters:Math.SQRT2*.00006};
}

function rendererChecks(G,U,caps,overview,native,read){
 const scope=vm.createContext({GA:{...G},performance});vm.runInContext(String(read('src/renderer.js')),scope);vm.runInContext(String(read('src/trail-renderer.js')),scope);const R=scope.GA.DioramaRenderer,Base=scope.GA.TRAIL_RENDERER.Base;
 const r=Object.assign(Object.create(R.prototype),{T,scene:new T.Scene(),mats:{matte:new T.MeshStandardMaterial({vertexColors:true,side:T.DoubleSide})},cache:new Map(),geometryRefs:new Map(),indexByArray:new Map(),recordMap:new Map(),packs:new Map(),records:[],objects:[],signObjects:[],residentBytes:0,uploads:0,evictions:0,quality:'balanced',timeUniform:{value:0},engine:{shadowMap:{},renderLists:{dispose(){}}}});
 const terrain=overview.meshes.filter(m=>caps.some(c=>c.terrainSource===m.id));r.addRecords([...terrain,...caps],'overview');let cases=0,reentries=0;const variants=new Set();
 for(const quality of ['low','balanced','high'])for(const ready of [false,true])for(const mode of ['focus','atlas'])for(const distance of [30,2000]){r.quality=quality;if(ready)r.packs.set('trail',{id:'trail'});else r.packs.delete('trail');const rig={eye:distance===30?[852,43.2,203]:[867,1800,191],planes:[]},opts={space:'surface',focus:'trail',displayMode:mode};let visible=0;for(const cap of caps){const record=r.recordMap.get(cap.id),source=r.recordMap.get(cap.terrainSource),expected=Base.prototype.wanted.call(r,source,rig,opts,distance);assert.equal(r.wanted(record,rig,opts,distance),expected,'Cap chose its small bound instead of the actual tile');if(expected){visible++;variants.add((ready?'native':'proxy')+':'+(cap.globalFar?'far':'near'));assert.equal(r.levelFor(record,999),0);}}assert.equal(visible,1);cases++;}
 assert.equal(variants.size,4);r.packs.clear();r.quality='balanced';const near=r.recordMap.get(caps[0].id),far=r.recordMap.get(caps[1].id);r.ensure(near,0);r.ensure(far,0);const publicBytes=caps.reduce((n,m)=>n+m.vertices.byteLength,0);assert.equal(r.residentBytes,publicBytes);
 for(let i=0;i<3;i++){const fresh={...native,vertices:native.vertices.slice(),farVertices:native.farVertices.slice()};r.attachPack({id:'trail',meshes:[fresh],signs:[]});const rec=r.recordMap.get(fresh.id);r.ensure(rec,0);r.ensure(rec,1);assert.equal(r.residentBytes,publicBytes+fresh.farVertices.byteLength);r.dropPack('trail');assert.equal(r.residentBytes,publicBytes,'Drop released permanent approach or retained detail');assert(!r.geometryRefs.has(fresh.vertices)&&!r.geometryRefs.has(fresh.farVertices));assert(caps.every(m=>r.recordMap.has(m.id)));reentries++;}
 const lowBridge={...native,id:'check-trail-low',vertices:native.vertices.slice(),farVertices:native.farVertices.slice()};r.attachPack({id:'check-trail-low',meshes:[lowBridge],signs:[]});const lowRecord=r.recordMap.get(lowBridge.id);r.quality='low';const lowLevels=[];for(const distance of [30,200,30]){lowRecord.distance=distance;r.ensure(lowRecord,1);const expected=distance===200?1:0;assert.equal(lowRecord.level,expected,'Low lost original near-board detail');assert.equal(lowRecord.array,expected?lowBridge.farVertices:lowBridge.vertices);assert.equal(r.residentBytes,publicBytes+lowRecord.array.byteLength);lowLevels.push({distance,level:lowRecord.level});}lowRecord.distance=NaN;r.ensure(lowRecord,1);assert.equal(lowRecord.level,1,'Non-finite distance should retain caller LOD');r.dropPack('check-trail-low');assert.equal(r.residentBytes,publicBytes);assert(!r.geometryRefs.has(lowBridge.vertices)&&!r.geometryRefs.has(lowBridge.farVertices));r.quality='balanced';
 const removed=r.recordMap.get(caps[0].terrainSource);r.recordMap.delete(caps[0].terrainSource);assert(!r.wanted(near,{eye:[852,43,203],planes:[]},{space:'surface',focus:'trail',displayMode:'focus'},30));r.recordMap.set(caps[0].terrainSource,removed);
 for(const record of r.records)r.evict(record);assert.equal(r.residentBytes,0);assert.equal(r.geometryRefs.size,0);assert.equal(r.cache.size,0);r.mats.matte.dispose();
 return{visibilityCases:cases,lowBridgeLevels:lowLevels,nonfiniteDistanceKeepsCallerLOD:true,nativeProxyTerrainPairs:[...variants].sort(),reentries,publicAttributeBytes:publicBytes,addedCustomAttributeBytes:0,addedMaterials:0,addedProgramVariants:0,missingTerrainHidesCap:true,finalResidentBytes:r.residentBytes};
}

export async function checkTrail(G,atlas,characters,read,options={}){
 for(const [p,sha]of Object.entries(unchanged))assert.equal(hash(read(p)),sha,'Protected source changed: '+p);
 const U=G.TRAIL_UPGRADE;assert(U&&U.revision===3);const route=G.routes.find(r=>r.id==='route-shrine');assert.equal(JSON.stringify(route.points),JSON.stringify(routePoints));assert.equal(route.width,5);
 boundaryRayNudges=0;const source=gunzipSync(read('assets/packs/overview.pack.gz')),overview=G.decodePack(source.buffer.slice(source.byteOffset,source.byteOffset+source.byteLength)),runtimeTerrain=new G.Terrain(atlas);if(G.LANDSCAPE)G.LANDSCAPE.apply(overview,runtimeTerrain);if(G.applyHighlandGround)G.applyHighlandGround(overview,runtimeTerrain);const routes=JSON.stringify(G.routes),presets=JSON.stringify(G.PRESETS),beforeOverview=overview.meshes.map(m=>({m,vertices:hash(raw(m.vertices)),index:m.index?hash(raw(m.index)):null,metadata:JSON.stringify([m.id,m.owner,m.center,m.radius,m.material])}));
 const prepareStart=performance.now();U.prepare(atlas,overview);const prepareObservedMs=performance.now()-prepareStart,contacts=atlas.surfaceContacts[U.contactId],cloneStart=performance.now(),clone=structuredClone({surfaceContacts:{[U.contactId]:contacts},trailUpgrade:atlas.trailUpgrade}),cloneMs=performance.now()-cloneStart;assert.equal(clone.trailUpgrade.roadTriangles.byteLength,atlas.trailUpgrade.roadTriangles.byteLength);
 const {roadTriangles:contactRoad,...contactMetadata}=atlas.trailUpgrade,cloneMetadataJSONBytes=Buffer.byteLength(JSON.stringify({surfaceContacts:{[U.contactId]:{bounds:contacts.bounds}},trailUpgrade:contactMetadata}));
 const publicStart=performance.now(),caps=U.publicEnvironment(atlas,overview),publicMs=performance.now()-publicStart;assert.equal(caps.length,2);for(const cap of caps)assert.equal(JSON.stringify(cap.terrainTile),'[768,0,256]');const headSelection=bridgeHeadSelection(U,atlas,overview,caps),headFinish=bridgeHeadFinish(G,caps);
 for(const old of beforeOverview)if(old.m.id!==U.proxyId){const now=overview.meshes.find(m=>m.id===old.m.id);assert.equal(now,old.m);assert.equal(hash(raw(now.vertices)),old.vertices);assert.equal(now.index?hash(raw(now.index)):null,old.index);assert.equal(JSON.stringify([now.id,now.owner,now.center,now.radius,now.material]),old.metadata);}
 const t=new G.Terrain(atlas),sourceStart=performance.now(),a=U.originalBuildTrail(t),b=U.originalBuildMystia(t),originalMs=performance.now()-sourceStart,original={id:'trail',meshes:[...a.meshes,...b.meshes],signs:b.signs,meta:{trail:a.meta,mystia:b.meta},atlas};for(const m of original.meshes){m.owner='trail';m.region='trail';m.space='surface';}
 const upgradeStart=performance.now(),candidate=U.upgradeDetail(original,atlas),upgradeMs=performance.now()-upgradeStart;assert.equal(candidate.meshes.length,35);let unchangedRecords=0;
 for(const old of original.meshes){const now=candidate.meshes.find(m=>m.id===old.id);if(![U.bridgeId,U.houseId].includes(old.id)){assert.equal(now,old,'Unrelated authored record replaced');unchangedRecords++;}}
 const oldBridge=original.meshes.find(m=>m.id===U.bridgeId),bridge=candidate.meshes.find(m=>m.id===U.bridgeId),oldHouse=original.meshes.find(m=>m.id===U.houseId),house=candidate.meshes.find(m=>m.id===U.houseId);assert(raw(oldBridge.vertices.subarray(0,504*27)).equals(raw(bridge.vertices)));assert.equal(bridge.vertices.length/27,504);assert.equal(bridge.farVertices.length/27,216);assert.equal(hash(raw(bridge.farVertices)),'f232762dff0dcc4827916f32ccc9edaa77adae8706f65136bc9428bcd3e4c0dc','V1 far bridge changed');assert.equal(hash(raw(house.vertices)),'2a94edfa96da39b21fd6bde6054f3538485b039433b2023472d34f12dacaf0cf','Reviewed continuous kitchen shell changed');assert(!house.farVertices,'Mixed props were simplified for a far budget');const retainedHouseTriangles=replaySegments(oldHouse.vertices,house.vertices,house.trailRepairs);
 assert.equal(a.plantSites.length,604);assert.equal(b.plantSites.length,14);assert.equal(JSON.stringify(a.meta.cart),JSON.stringify({x:1092,z:291,y:41.89137209208756,yaw:.18,kind:'移动屋台的本作展示位置'}));assert.equal(JSON.stringify(b.meta.position),'[1072,41.89137209208756,274]');assert.equal(b.meta.tables,5);assert.equal(b.meta.counterSeats,8);assert.equal(b.meta.kind,'同人氛围参考下的本作屋台式食堂；非原作固定住宅');assert.equal(JSON.stringify(G.routes),routes);assert.equal(JSON.stringify(G.PRESETS),presets);
 const semantic={...structuralRays(G,U,original,candidate,caps,overview),headSelection,headFinish,retainedBeamClearance:retainedBeamClearance(bridge,caps),kitchenShell:kitchenShell(G,house,original.meta.mystia.position)},resources=rendererChecks(G,U,caps,overview,bridge,read),authoredTriangles=candidate.meshes.reduce((n,m)=>n+m.vertices.length/27*(m.instances?.length/16||1),0),publicTriangles=caps.map(m=>m.vertices.length/27),houseTriangles=house.vertices.length/27;
 assert(authoredTriangles<=41000);assert(candidate.bytes<=3*1048576);assert(houseTriangles<=4500);assert(bridge.vertices.length/27+publicTriangles[0]<=750);assert(bridge.farVertices.length/27+publicTriangles[1]<=350);for(const m of [...candidate.meshes,...caps])assert(m.vertices.every(Number.isFinite));
 // Keep this fixture scoped to the structural layer. The landscape checker
 // independently validates final buildRegion output, including its shrubs.
 const structureBuild=G.TRAIL_LANDSCAPE?G.TRAIL_LANDSCAPE.originalBuildRegion:G.buildRegion;
 assert.equal(typeof structureBuild,'function','Missing retained trail structure builder');
 const actual=await structureBuild(atlas,'trail');assert.equal(geometryDigest(actual),geometryDigest(candidate),'Integration differs from bounded author-body upgrade');
 const fixture={revision:3,sourceBaseline:'040e5369b1ef0d5f45242ff4e1193ab0874e2f2b',geometrySHA:geometryDigest(actual),originalGeometrySHA:geometryDigest(original),bridgeNearSHA:hash(raw(bridge.vertices)),bridgeFarSHA:hash(raw(bridge.farVertices)),houseSHA:hash(raw(house.vertices)),publicNearSHA:hash(raw(caps[0].vertices)),publicFarSHA:hash(raw(caps[1].vertices)),retainedHouseTriangles,housePatches:JSON.parse(JSON.stringify(house.trailRepairs))};
 if(!options.draft){const expected=JSON.parse(read('tools/trail-baseline.json'));assert.deepEqual(fixture,expected,'Trail candidate differs from explicitly reviewed fixture');}
 return{revision:3,fixture,authored:{records:35,unchangedRecords,sourceBytes:candidate.bytes,originalSourceBytes:U.bytes(original.meshes),expandedTriangles:authoredTriangles,houseTriangles,retainedHouseTriangles,bridgeNearTriangles:504,bridgeFarTriangles:216},public:{records:2,triangles:publicTriangles,sourceBytes:U.bytes(caps),unchangedOverviewRecords:beforeOverview.length-1,pureBridgeProxyOnly:true},contacts:{positionBytes:atlas.trailUpgrade.sourceBytes,nearTerrainBytes:contacts.near.byteLength,farTerrainBytes:contacts.far.byteLength,roadBytes:atlas.trailUpgrade.roadTriangles.byteLength,prepareRecordedMs:atlas.trailUpgrade.prepareMs,prepareObservedMs,cloneMs,clonePositionArrays:3,cloneMetadataJSONBytes,scope:'CPU positions and small metadata cloned with existing Worker atlas; not GPU memory'},timings:{originalAuthoredBuildMs:originalMs,upgradeMs,publicBuildMs:publicMs,scope:'Node CPU only; excludes WebGL, complete world and browser frame cost'},semantic,resources,charactersSourceSHA:hash(read('data/characters.json')),newTextures:0,newLights:0,newTargets:0,verification:'CPU structure, exact source preservation and inherited residency dispatch only; visual/GPU acceptance pending'};
}

// A kitchen-only repair does not depend on rebuilding trail/bridge geometry.
// This bounded entry checks one Mystia author body and exports its full source.
export async function checkTrailKitchen(G,atlas,characters,read){
 for(const [p,sha]of Object.entries(unchanged))assert.equal(hash(read(p)),sha,'Protected source changed: '+p);
 const U=G.TRAIL_UPGRADE;assert.equal(U.revision,3);const start=performance.now(),body=U.originalBuildMystia(new G.Terrain(atlas)),position=body.meta.position,old=body.meshes.find(m=>m.id===U.houseId);assert.equal(hash(raw(old.vertices)),'41a631f9d3b243b6abff7fd7709edf9179fb6945bbb6966c0c68a3f9d6b00817','Original author body differs from the exact Chrome baseline');
 const segment=fn=>{const g=new G.Geometry().place(...position,Math.PI);fn(g);return Float32Array.from(g.a);},kitchen=segment(g=>U.kitchen(g,true)),patches=[{name:'kitchen',before:segment(g=>U.kitchen(g)),after:kitchen},{name:'awning',before:segment(g=>U.awning(g)),after:segment(g=>U.awning(g,true))}],result=U.replaceSegments(old.vertices,patches),house={...old,vertices:result.vertices,trailRepairs:result.patches,owner:'trail',region:'trail',space:'surface'};
 const lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(let i=0;i<house.vertices.length;i+=9)for(let k=0;k<3;k++){lo[k]=Math.min(lo[k],house.vertices[i+k]);hi[k]=Math.max(hi[k],house.vertices[i+k]);}house.center=lo.map((v,k)=>(v+hi[k])/2);house.radius=G.length(G.sub(hi,lo))/2;
 assert.equal(hash(raw(house.vertices)),'2a94edfa96da39b21fd6bde6054f3538485b039433b2023472d34f12dacaf0cf');assert.equal(JSON.stringify(house.center),JSON.stringify(old.center));assert.equal(house.radius,old.radius);const retainedHouseTriangles=replaySegments(old.vertices,house.vertices,house.trailRepairs);assert.equal(retainedHouseTriangles,3499);
 const oldPlaster=segment(g=>{for(const p of plasterReference)g.box(...p,G.C.plaster);}),oldKitchen=new Float32Array(oldPlaster.length+kitchen.length-60*27);oldKitchen.set(oldPlaster);oldKitchen.set(kitchen.subarray(60*27),oldPlaster.length);assert.equal(hash(raw(oldKitchen)),'eac3b2a9536ef92bdfa00cd109780ca1dca57367df14c40ff356e247c96d78bf');const previous=U.replaceSegments(old.vertices,[{...patches[0],after:oldKitchen},patches[1]]);assert.equal(hash(raw(previous.vertices)),'8381aefda9dfe329404ecba2a4621117bc54487f944bfb4ca9d7d520e9657fc6','Restoring only plaster did not restore the exact prior Chrome body');
 const shell=kitchenShell(G,house,position),windows=kitchenWindowRays(old,house,position),source=String(read('src/trail-upgrade.js')),prefix=source.slice(0,source.indexOf('function kitchen(')),suffix=source.slice(source.indexOf('const awningY=')),prefixSHA=hash(Buffer.from(prefix)),suffixSHA=hash(Buffer.from(suffix));assert.equal(prefixSHA,'aa8c7251042b30412ad140c7eeccc7fb030cc4dd528df27dc0d25f1a5d612a2a','Bridge/cap dependency source changed');assert.equal(suffixSHA,'2d3d3ee954cb3d7a06a0be79acdeb6af4189f472bd41dd49a85626a7629f2afd','Non-kitchen source changed');
 const fields=['id','group','material','owner','region','space','component','locationId','overview','globalSurface','center','radius','lod','lodDistance','maxDetailDistance','forestPart','basis'],record={};for(const k of fields)record[k]=house[k]??null;record.arrays={};record.metadata={};for(const k of Object.keys(house).sort())if(ArrayBuffer.isView(house[k]))record.arrays[k]={type:house[k].constructor.name,length:house[k].length,bytes:house[k].byteLength,sha256:hash(raw(house[k]))};else if(house[k]!==undefined&&typeof house[k]!=='function')record.metadata[k]=JSON.parse(JSON.stringify(house[k]));
 const sourceSHA={'src/trail-upgrade.js':hash(read('src/trail-upgrade.js')),'tools/check-trail.mjs':hash(read('tools/check-trail.mjs'))},fixtureUpdate={houseSHA:record.arrays.vertices.sha256,housePatches:record.metadata.trailRepairs,retainedHouseTriangles};
 return{scope:'One original Mystia author body and its two local repair segments; no trail region, bridge suite, Worker, WebGL or browser',revision:3,sourceSHA,sourceBaseline:'040e5369b1ef0d5f45242ff4e1193ab0874e2f2b',sourceBinding:{originalHouseSHA:hash(raw(old.vertices)),previousHouseSHA:hash(raw(previous.vertices)),candidateHouseSHA:record.arrays.vertices.sha256,restoringOnlyPlasterRestoresPriorChromeBody:true},semantic:{shell,windowRays:windows},preservation:{retainedOriginalMixedTriangles:retainedHouseTriangles,retainedFromPreviousRepairTriangles:house.vertices.length/27-shell.plasterTriangles,kitchenWindowWoodFloats:kitchen.length-60*27,bridgeCapSourcePrefixSHA:prefixSHA,nonKitchenSourceSuffixSHA:suffixSHA,capsProofSHA256:'44458ef0c3a59cbb75460dd74c916c508fbba8feefe5750f48b1b62e295dda45'},resources:{houseTriangles:house.vertices.length/27,houseSourceBytes:house.vertices.byteLength,sourceByteDeltaFromPrevious:house.vertices.byteLength-previous.vertices.byteLength,newRecords:0,newMaterials:0,newAttributes:0,newTextures:0,newLights:0,newTargets:0},sourceIntegrity:{revision:3,sourceSHA,records:[record],completeSourceGeometry:true,completeMetadata:true,hashAlgorithm:'SHA-256 of exact typed-array view bytes'},fixtureUpdate,authorGeometrySHARequiresRootBuild:true,CPUms:performance.now()-start,verification:'Bounded kitchen source/surface semantics only; same-camera visual acceptance pending'};
}

if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){
 assert.equal(Number(process.versions.node.split('.')[0]),22,'Use Node 22 for stable geometry');const root=resolve(new URL('../',import.meta.url).pathname),read=p=>fs.readFileSync(resolve(root,p)),context=vm.createContext({performance,TextDecoder,TextEncoder}),project=JSON.parse(read('project.json'));for(const p of project.worldBuilders)vm.runInContext(String(read(p)),context,{filename:p});const atlas=JSON.parse(read('data/atlas.json')),characters=JSON.parse(read('data/characters.json')),report=process.argv.includes('--kitchen-draft')?await checkTrailKitchen(context.GA,atlas,characters,read):await checkTrail(context.GA,atlas,characters,read,{draft:process.argv.includes('--draft')});console.log(JSON.stringify(report,null,2));
}
