/* v0.15 runtime: continuous island, natural weather, independent overview load, cancellable regional builders,
   logical coordinates separated from display mode and exhibition transforms. */
(function(G){'use strict';const $=id=>document.getElementById(id),data=JSON.parse($('atlas-data').textContent),bootAt=performance.now();
const DEFAULTS=G.REGION_DEFAULTS={lunar:'moonOverview',tranquility:'moonSeaInner',kaian:'dreamPassage',kishinjou:'needleExterior',oldhell:'hellOverview',connections:'transitionForest',village:'riverside',hakurei:'shrineDiorama',trail:'trailCart',scarlet:'scarlet',myouren:'myouren',mausoleum:'mausoleumCorridor',senkai:'senkai',bamboo:'bamboo',forest:'forest',sunflower:'sunflowerPath',nameless:'lilyClose',mountain:'moriya',genbu:'genbu',muenzuka:'muenzuka'};
for(const b of G.DIORAMA.blocks){if(!G.PRESETS[DEFAULTS[b.id]]){let [x,y,z]=b.center;G.PRESETS[DEFAULTS[b.id]]={label:b.name,region:b.id,eye:[x+90,y+86,z+126],target:[x,y,z]};}}
const state={ready:false,version:'{{VERSION}}',space:'surface',logicalSpace:'surface',era:'地表选集',displayMode:'atlas',focus:null,view:'diorama',aligned:true,lighting:'neutral',weather:'clear',cutaway:false,quality:'balanced',bloom:true,ao:true,vegetation:true,motion:true,labels:false,characters:false,bambooHaze:true,flowerEvent:false,reflections:true,ceiling:true,animationFPS:30,uiHidden:false,diagnostic:false,firstFrameMs:null,clock:0,drawnFrames:0,changed:()=>wake()};
let world,renderer,rig,stream,characters,raf=0,lastTime=0,lastDraw=0,lastPose='',dirty=true,placeFilter='placed',labelEls=[],downloadCount=0;
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),4200);}
function wake(){dirty=true;if(!raf&&!document.hidden&&!globalThis.ATLAS_TEST_PAUSE)raf=requestAnimationFrame(tick);}
function opts(){return {...state,time:state.clock};}
function newLabel(text,id,subtitle){let b=document.createElement('button');b.className='place-label'+(subtitle?' independent':'');b.textContent=text;if(subtitle){let s=document.createElement('small');s.textContent=subtitle;b.append(s);}b.onclick=()=>setView(DEFAULTS[id],true);$('labels').append(b);return b;}
const hellLabelEls=[];
 function updateHellLabels(){if(!rig)return;for(const h of hellLabelEls){const p=rig.project(h.p);h.el.hidden=!(state.space==='oldhell'&&state.hellSection&&state.labels&&!state.uiHidden&&p.visible);if(!h.el.hidden){h.el.style.left=p.x*innerWidth+'px';h.el.style.top=p.y*innerHeight+'px';}}}
 function initLabels(){
 for(const [text,view,p]of [['旧都','hellStreet',[0,-268,480]],['地灵殿','hellPalace',[0,-211,-100]],['灼热地狱','hellBlazing',[195,-573,-365]],['旧血池','hellBlood',[-338,-750,-725]]]){const el=newLabel(text,view,'');el.onclick=()=>setView(view,true);el.hidden=true;hellLabelEls.push({el,p});}
for(const b of G.DIORAMA.blocks){labelEls.push({block:b,el:newLabel(b.name,b.id,b.id==='mausoleum'?'TH13 历史 / 原位剖切':b.id==='senkai'?'独立空间 / 迁址后':null)});}}
function updateLabels(){const atlas=state.displayMode==='atlas';for(const {block:b,el} of labelEls){let show=state.labels&&!state.uiHidden&&((atlas&&!b.space)||(state.cutaway&&b.id==='mausoleum')||(state.displayMode==='continuous'&&!b.space));const p=G.DIORAMA.point(b.center,b.id,atlas?'atlas':'focus',state.aligned);p[1]+=b.id==='mountain'?150:15;const q=rig.project(p);show=show&&q.visible;el.hidden=!show;if(show){el.style.left=q.x*innerWidth+'px';el.style.top=q.y*innerHeight+'px';}}
 const show=false;$('layer-lines').style.display=show?'block':'none';if(!show)$('layer-line').setAttribute('d','');if(show){let a=rig.project([307,138,516]),b=rig.project(G.DIORAMA.point([307,-25,498],'mausoleum','atlas',false));$('layer-line').setAttribute('d',a.visible&&b.visible?`M${a.x*innerWidth},${a.y*innerHeight} Q${(a.x+b.x)*innerWidth*.5},${a.y*innerHeight+90} ${b.x*innerWidth},${b.y*innerHeight}`:'');}
 updateHellLabels();characters?.update();}
function diagnostic(){if(!state.diagnostic)return;let r=renderer.stats,s=stream.info();$('diagnostic').textContent=[`THREE r185 / ${state.displayMode} / ${state.space}`,`detail cache: ${s.cached.join(', ')||'none'}`,`worker: ${s.building||'idle'}`,`overview source ${world.overviewBytes/1048576|0} MiB + detail ${s.detailSourceMiB.toFixed(1)} MiB`,`model GPU attributes ${r.residentAttributeMiB?.toFixed(1)} MiB (not VRAM)`,`scene incl. shadow: ${r.calls} calls / ${r.triangles?.toLocaleString()} tris`,`whole frame: ${r.totalCalls} calls / ${r.totalTriangles?.toLocaleString()} tris`,`reflections ${r.reflectionCalls} calls / post ${r.postPasses} passes`,`drawn ${state.drawnFrames} / uploads ${r.uploads} / evictions ${r.evictions}`,`CPU evictions ${s.evictions} / cancelled ${s.cancelled}`,`first frame ${state.firstFrameMs?.toFixed(0)} ms`].join('\n');}
function draw(){renderer.render(rig,opts());state.drawnFrames++;updateLabels();diagnostic();dirty=false;lastDraw=performance.now();}
function tick(t){raf=0;if(!state.ready||document.hidden)return;let dt=Math.max(0,Math.min(.1,(t-lastTime)/1000||.016));lastTime=t;rig.update(dt);autoFocus();const pose=[...rig.eye,...rig.target].map(v=>v.toFixed(5)).join(',');const moved=pose!==lastPose;lastPose=pose;const animated=state.motion&&renderer.hasVisibleAnimation;
 if(animated)state.clock+=dt;if(dirty||moved||animated&&t-lastDraw>=1000/(state.displayMode==='atlas'?Math.min(15,state.animationFPS):state.animationFPS)-1)draw();else updateLabels();if(rig.transition||rig.pointers.size||rig.mode==='fly'&&rig.keys.size||animated)if(!raf&&!globalThis.ATLAS_TEST_PAUSE)raf=requestAnimationFrame(tick);}
function formatTitle(id,p){
 const moon=G.LUNAR.spaces.includes(state.space);$('lunar-nav').hidden=!moon;$('btn-lunar').classList.toggle('active',moon);document.body.classList.toggle('in-lunar',moon);

 $('btn-needle').classList.toggle('active',state.focus==='kishinjou');
 const isHell=state.space==='oldhell';document.body.classList.toggle('in-oldhell',isHell);$('hell-nav').hidden=!isHell;
 $('btn-hell').classList.toggle('active',isHell);
 if(moon){
  $('scene-index').textContent=state.space==='dream'?'TH15 / DREAM FRAGMENT':'月世界 / '+(state.lunarSealed?'TH15 封存事件示意':state.lunarFace==='outer'?'表月荒原':'儚月抄选集 · P布局');
  $('scene-title').textContent=p.label;
  $('scene-subtitle').textContent=state.space==='dream'?'仅展示第四槐安通道片段，不代表完整梦都。':state.lunarSealed?'冻结与撤离的艺术示意；不是月都的永久冬季。':state.space==='lunarsea'?'表月荒原与内侧海水互斥；不按天文远侧位置解释。':'碧瓦朱柱、桃岸长廊；原作关系与本作布局分开记录。';
  $('mode-note').textContent='独立空间 · 导览切换不代表常开物理通路 · 尺寸与建筑背面为P';return;
 }
 if(isHell){$('scene-index').textContent='地底风物志 / '+(id==='hellOverview'?'全域剖览':id.startsWith('hellH')||id==='hellGallery'?'地灵殿':'旧地狱');
 $('scene-title').textContent=({hellReactor:'核聚变炉',hellOverview:'旧地狱 · 地底全域',hellBlazing:'灼热地狱遗址',hellDescent:'地灵殿下 · 深渊'})[id]||p.label;$('scene-subtitle').textContent=({hellOverview:'灯火旧都之下，宫殿与地火层叠。',hellStreet:'青瓦连檐，灯笼照见石板长街。',hellRoofs:'街巷、水渠与背院，共处深远洞窟。',hellPalace:'蔷薇前庭与西洋洋馆，地火隐在石阶之下。',hellHall:'拱廊深处，彩绘地砖与灯火相映。',hellGallery:'细柱、回廊与彩窗，通往寂静的大堂。',hellSpa:'泉水沿石池流淌，蒸汽漫过木廊。',hellBridge:'风穴深处，跨越幽谷，向旧都而行。',hellDescent:'循维护栈道下行，地灵殿下的热光渐近。',hellBlazing:'岩壳破裂，熔流在遗址间缓缓涌动。',hellReactor:'星形栈桥环绕地底太阳。',hellBlood:'更深处，幽暗油海映着岸边微光。'})[id]||'';
 $('mode-note').textContent='旧地狱 · 几何与路线为本作补完 · 可自由旋转及飞行';return;}

 if(state.focus==='kishinjou'){
 $('scene-index').textContent='幻想乡上空 / '+(state.castleStorm?'TH14 事件示意':'TH145 外形 · P 三维补完');
 $('scene-title').textContent=p.label;
 $('scene-subtitle').textContent=state.castleSection?'仅展开大殿；切换外观机位恢复完整城体。':id==='needleHall'?'榻榻米在头顶，梁顶在脚下；窗外仍是同一片幻想乡。':state.castleStorm?'局部魔力风暴示意；返回外观机位关闭，不改变全岛天气。':'石垣向天，三重瓦檐沉向群山。';
 $('mode-note').textContent='空中地标 · 方位与高度为本作配置 · 飞行来路，不设地面道路';return;}
 $('scene-index').textContent=state.cutaway?'LOCAL SECTION / TH13':state.displayMode==='atlas'?'GENSOKYO / ONE CONNECTED WORLD':'GENSOKYO / '+(state.focus||'').toUpperCase();
 $('scene-title').textContent=id==='diorama'?'幻想乡 · 云上大地':p.label;
 const subtitles={muenzuka:'再思之道尽头的林中墓地 · 紫樱与彼岸花为景观选集。',genbu:'玄武岩柱、溪涧木桥与河童作业口 · 尺度和设施布置为本作补完。',forest:'香霖堂、两座住居与幽深林径，和人里共处一块大地。',hakurei:'兽道、山坡与神社庭院连续相接。',mausoleum:'墓地下的历史旧址；维持原工程坐标。',senkai:'迁址后的独立仙界，不悬置在地表上空。',connections:'田野、林缘和缓坡，不再以虚空间隔。'};
 $('scene-subtitle').textContent=state.cutaway?'只剖开命莲寺后山；其他地表仍为同一空岛。':state.displayMode==='atlas'||state.displayMode==='continuous'?'一整块空岛，山川林野彼此相连；虚空只在外围。':subtitles[state.focus]||'近处加载细节，远处仍有连续地形与相邻区域。';
 $('mode-note').textContent=state.cutaway?'TH13 历史剖切 · 未更改地下坐标':state.space==='surface'?'连续地表 · 左键旋转 / 右键平移 / 滚轮缩放':'独立空间 · 可返回全岛';
}
let autoCandidate=null,autoSince=0,autoOrigin=null,autoTimer=0;
function autoFocus(){if(!stream||state.space!=='surface'||state.cutaway||rig.transition)return;if(autoOrigin&&G.length(G.sub(rig.eye,autoOrigin.eye))<4&&G.length(G.sub(rig.target,autoOrigin.target))<4)return;const dist=G.length(G.sub(rig.eye,rig.target));if(dist>1550){autoCandidate=null;return;}const next=G.KISHINJOU.contains(rig.target)?'kishinjou':G.DIORAMA.owner(rig.target[0],rig.target[2])||'connections';if(next===state.focus){autoCandidate=null;return;}if(next!==autoCandidate){autoCandidate=next;autoSince=performance.now();clearTimeout(autoTimer);autoTimer=setTimeout(()=>{autoTimer=0;wake();},550);return;}if(performance.now()-autoSince<500)return;
 state.focus=next;state.displayMode='focus';rig.displayMode='focus';state.labels=false;$('opt-labels').checked=false;state.detailNeighbors=[];state.castleSection=false;state.castleStorm=false;stream.focus(next==='connections'?[]:[next]);$('layer-bar').hidden=true;updateDock();formatTitle('auto',{label:G.REGION_LABELS[next]||'区域之间'});autoCandidate=null;clearTimeout(autoTimer);autoTimer=0;autoOrigin={eye:rig.eye.slice(),target:rig.target.slice()};dirty=true;}
function updateDock(){const sel=$('region-select'),r=state.displayMode==='atlas'||state.displayMode==='continuous'?'world':state.space==='section'?'section':state.focus;sel.value=r;const wrap=$('view-buttons');wrap.replaceChildren();let entries=Object.entries(G.PRESETS).filter(([id,p])=>{if(['overview','atlasCutaway','atlasCave','atlasWindow'].includes(id))return false;if(r==='world')return['diorama','continuous','islandEdge'].includes(id);if(r==='section')return id==='templeSection';return G.DIORAMA.regionOf(id)===r&&id!=='continuous'&&p.region!=='world';});if(r==='hakurei')entries.sort(([a],[b])=>(a==='shrineDiorama'?-1:b==='shrineDiorama'?1:0));for(const [id,p] of entries){let b=document.createElement('button');b.className='view-button'+(id===state.view?' active':'');b.dataset.view=id;b.textContent=p.label;b.onclick=()=>setView(id,true);wrap.append(b);}}
function setView(id,animate=true){if(!rig)return;let p=G.PRESETS[id];if(!p)return;const oldSpace=state.space,oldMode=state.displayMode;autoOrigin={eye:p.eye.slice(),target:p.target.slice()};autoCandidate=null;clearTimeout(autoTimer);autoTimer=0;state.view=id;state.displayMode=['diorama','dioramaLayers','overview','atlasCutaway','atlasCave'].includes(id)?'atlas':['continuous','islandEdge'].includes(id)?'atlas':'focus';state.cutaway=id==='dioramaLayers';state.detailNeighbors=({transitionForest:['forest'],transitionBamboo:['bamboo'],transitionFlowers:['sunflower'],transitionLake:['scarlet']})[id]||[];state.space=p.space||'surface';state.lunarFace=p.lunarFace||'inner';state.lunarSealed=!!p.lunarSealed;state.hellSection=!!p.section;state.castleSection=!!p.castleSection;state.castleStorm=!!p.castleStorm;if(state.displayMode==='atlas'||state.displayMode==='continuous')state.space='surface';state.logicalSpace=state.space;state.era=p.era|| (p.aerial?(p.castleStorm?'TH14事件示意':'TH145外形／TH14室内构造参考'):state.space==='mausoleum'?'TH13历史旧址':state.space==='senkai'?'迁址后':state.space==='section'?'TH13历史关系':'地表选集');state.focus=state.displayMode==='atlas'||id==='continuous'?null:G.DIORAMA.regionOf(id);if(state.space==='section'||state.cutaway)state.focus='myouren';state.labels=state.displayMode==='atlas'||id==='continuous'||state.hellSection;$('opt-labels').checked=state.labels;
 rig.displayMode=state.displayMode;rig.fov=p.fov|| (state.displayMode==='atlas'?42:id.startsWith('shrineDiorama')?37:49);rig.setView({...p,space:state.space},animate&&oldSpace===state.space&&oldMode===state.displayMode&&state.space!=='oldhell');rig.updateMatrices();
 if(id==='sunflowerStage'){state.flowerEvent=true;$('opt-flower-event').checked=true;}
 $('btn-overview').classList.toggle('active',state.displayMode==='atlas');$('btn-fly').classList.remove('active');$('layer-bar').hidden=!state.cutaway;$('space-nav').hidden=state.displayMode==='atlas'||!['myouren','mausoleum','senkai'].includes(state.focus);$('btn-cave-roof').hidden=!['mausoleum','section'].includes(state.space);updateDock();formatTitle(id,p);
 if(stream){const ids=state.space==='section'||state.cutaway?['myouren','mausoleum']:state.focus&&state.focus!=='connections'?[state.focus]:state.detailNeighbors;stream.focus(ids);$('build-status').textContent=ids.length?(stream.cache.has(ids[0])?'精细模型就绪':'近景生成中…'):'整岛已就绪';}
 wake();}
function targetFor(loc){const imp=G.IMPLEMENTED?.[loc.id];if(typeof imp==='string'&&G.PRESETS[imp])return imp;if(imp?.view&&G.PRESETS[imp.view])return imp.view;if(G.PRESETS[loc.id])return loc.id;const p=world.placementMap.get(loc.id);if(!p)return null;return DEFAULTS[G.DIORAMA.owner(p.x,p.z)];}
function selectLocation(id){const l=data.locations.find(x=>x.id===id);if(!l)return;$('detail').classList.remove('hidden');$('detail-name').textContent=id==='nazrin_home'?'娜兹玲临时小屋':l.name;$('detail-tag').textContent=l.world+' / '+l.kind;let view=targetFor(l);$('detail-state').textContent=view?'可浏览 · 当前工程呈现':'已登记，尚无定位或实体';$('detail-fact').textContent=l.verified_fact||'';$('detail-design').textContent=(l.project_treatment||'')+'。具体模型、路径及展示边界均为本作设计。'+(l.id==='forest'?'本轮是补建，不是找回 v0.10 原代码。':'');if(G.HELL_NOTES?.[id])$('detail-design').textContent=G.HELL_NOTES[id];if(G.WEST_INFO?.[id]){$('detail-fact').textContent=G.WEST_INFO[id].fact;$('detail-design').textContent=G.WEST_INFO[id].design;} $('detail-sources').replaceChildren();for(const u of (G.WEST_INFO?.[id]?.sources||[])){let a=document.createElement('a');a.textContent='↗ 本轮核对出处';a.href=u;a.target='_blank';a.rel='noopener noreferrer';$('detail-sources').append(a);}for(const sid of l.source_ids||[]){const s=data.sources.find(x=>x.id===sid);if(s){const a=document.createElement('a');a.textContent='↗ '+s.title;a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';$('detail-sources').append(a);}}
 $('detail-relations').replaceChildren();for(const e of (data.relationships||[]).filter(e=>e.from===id||e.to===id).slice(0,8)){let other=e.from===id?e.to:e.from,ol=data.locations.find(l=>l.id===other);if(ol){let b=document.createElement('button');b.className='full-button';b.textContent='↗ '+ol.name;b.onclick=()=>selectLocation(other);$('detail-relations').append(b);}}
 if(view)setView(view,true);else toast('此地点未定位，保持当前镜头与空间。');if(innerWidth<800)$('drawer').classList.add('hidden');}
function renderList(){const q=$('search').value.trim().toLowerCase(),rows=data.locations.filter(l=>(placeFilter==='all'||placeFilter==='placed'&&targetFor(l)||placeFilter==='other'&&l.world!=='surface')&&[l.name,l.id,...(l.aliases||[]),...(l.id==='muenzuka'?['无缘冢']:[])].join('|').toLowerCase().includes(q));$('results').replaceChildren();$('result-count').textContent=rows.length+' / '+data.locations.length+' 条';for(const l of rows){let b=document.createElement('button');b.className='result';b.dataset.id=l.id;let s=document.createElement('span'),n=document.createElement('strong'),sub=document.createElement('small');n.textContent=l.name;sub.textContent=l.group+' · '+l.kind;s.append(n,sub);let em=document.createElement('em');em.textContent=targetFor(l)?'定位 ↗':'待建';b.append(s,em);b.onclick=()=>selectLocation(l.id);$('results').append(b);}}
function download(blob,name){let a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),8000);downloadCount++;}
function exportState(){return{version:'{{VERSION}}',sourceBaseline:'0.16.0',undergroundModule:'0.17.0',aerialModule:'0.18.0',lunarModule:G.LUNAR.version,lunarFace:state.lunarFace,lunarSealed:!!state.lunarSealed,castleSection:!!state.castleSection,castleStorm:!!state.castleStorm,castleAnchor:G.KISHINJOU.anchor.slice(),forestOrigin:'reconstructed_from_agreed_scope',space:state.space,logicalSpace:state.logicalSpace,era:state.era,displayMode:state.displayMode,displayTransforms:Object.fromEntries(G.DIORAMA.blocks.filter(b=>b.space).map(b=>[b.id,G.DIORAMA.transform(b.id,state.displayMode,state.aligned)])),view:state.view,focus:state.focus,lighting:state.lighting,weather:state.weather,cutaway:state.cutaway,surfaceComponents:1,clock:state.clock,camera:{eye:rig.eye.slice(),target:rig.target.slice()},renderer:renderer.info(),overviewSourceMiB:world.overviewBytes/1048576,streaming:stream.info(),characters:characters.stats(),firstFrameMs:state.firstFrameMs,downloads:downloadCount};}
function setupUI(){
 $('btn-lunar').onclick=()=>setView('moonOverview',false);document.querySelectorAll('[data-lunar-view]').forEach(b=>b.onclick=()=>setView(b.dataset.lunarView,false));
 $('btn-needle').onclick=()=>setView('needleExterior',true);
 $('btn-hell').onclick=()=>setView('hellOverview',false);
 $('hell-home').onclick=()=>setView('hellOverview',true);$('hell-return').onclick=()=>setView('diorama',false);
 document.querySelectorAll('[data-hell-view]').forEach(b=>b.onclick=()=>setView(b.dataset.hellView,true));
 $('hell-roof').onclick=()=>{state.ceiling=!state.ceiling;$('hell-roof').textContent=state.ceiling?'隐藏顶盖':'恢复顶盖';wake();};
for(const [id,name] of [['world','全岛总览'],['connections','区域之间 · 过渡地带'],...G.DIORAMA.blocks.map(b=>[b.id,b.name]),['section','历史上下关系']]){let o=document.createElement('option');o.value=id;o.textContent=name;$('region-select').append(o);}$('region-select').onchange=e=>setView(e.target.value==='world'?'diorama':e.target.value==='section'?'templeSection':DEFAULTS[e.target.value],true);
 $('btn-overview').onclick=$('brand-home').onclick=()=>setView('diorama',true);$('btn-layers').onclick=()=>setView('dioramaLayers',true);$('btn-align').onclick=()=>setView('diorama',true);$('btn-layer-underground').onclick=()=>setView('mausoleumCorridor',false);$('btn-layer-senkai').onclick=()=>setView('senkai',false);document.querySelectorAll('#space-nav [data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view,true));$('btn-cave-roof').onclick=()=>{state.ceiling=!state.ceiling;$('btn-cave-roof').textContent=state.ceiling?'隐藏洞顶与廊顶':'恢复洞顶与廊顶';wake();};
 $('btn-settings').onclick=()=>$('settings').classList.toggle('hidden');$('close-settings').onclick=()=>$('settings').classList.add('hidden');$('btn-search').onclick=()=>{$('drawer').classList.toggle('hidden');renderList();$('search').focus();};$('close-drawer').onclick=()=>$('drawer').classList.add('hidden');$('close-detail').onclick=()=>$('detail').classList.add('hidden');$('search').oninput=renderList;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{placeFilter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderList();});
 document.querySelectorAll('[data-weather]').forEach(b=>b.onclick=()=>{state.weather=b.dataset.weather;document.querySelectorAll('[data-weather]').forEach(x=>x.classList.toggle('active',x===b));renderer.lastRainAnchor=null;wake();});
 for(const [button,light] of [['light-dusk','dusk'],['light-neutral','neutral']])$(button).onclick=()=>{state.lighting=light;$('light-dusk').classList.toggle('active',light==='dusk');$('light-neutral').classList.toggle('active',light==='neutral');wake();};
 for(const [id,key] of [['opt-ao','ao'],['opt-bloom','bloom'],['opt-plants','vegetation'],['opt-motion','motion'],['opt-labels','labels'],['opt-reflections','reflections'],['opt-flower-event','flowerEvent']])$(id).onchange=e=>{state[key]=e.target.checked;lastTime=performance.now();wake();};$('animation-fps').onchange=e=>{state.animationFPS=+e.target.value;wake();};$('quality').onchange=e=>{state.quality=e.target.value;renderer.setQuality(state.quality);stream.budget=({low:125,balanced:220,high:280}[state.quality])*1048576;stream.trim();wake();};$('btn-fly').onclick=()=>{$('btn-fly').classList.toggle('active',rig.toggleFly()==='fly');wake();};$('btn-continuous').onclick=()=>{setView('continuous',false);$('settings').classList.add('hidden');};$('btn-clear-cache').onclick=()=>{stream.trim(true);toast('已释放非当前区域的源数据和离屏图形缓存。');wake();};$('btn-export').onclick=()=>download(new Blob([JSON.stringify(exportState(),null,2)],{type:'application/json'}),'{{EXPORT_PREFIX}}-state.json');$('btn-photo').onclick=()=>{draw();$('scene').toBlob(b=>b&&download(b,'{{EXPORT_PREFIX}}-'+state.view+'.png'),'image/png');};
 window.addEventListener('resize',()=>{if(!rig)return;rig.aspect=innerWidth/innerHeight;rig.updateMatrices();renderer.setSize(innerWidth,innerHeight,devicePixelRatio);wake();});document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;}else{lastTime=performance.now();wake();}});document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.code==='KeyH')setView('diorama',true);if(e.key==='/'){e.preventDefault();$('drawer').classList.remove('hidden');renderList();$('search').focus();}if(e.key==='Escape')document.querySelectorAll('.drawer,.detail,.popup').forEach(x=>x.classList.add('hidden'));if(e.key==='Tab'){e.preventDefault();state.uiHidden=!state.uiHidden;document.body.classList.toggle('ui-hidden',state.uiHidden);wake();}if(e.key==='F2'){e.preventDefault();state.diagnostic=!state.diagnostic;$('diagnostic').classList.toggle('hidden',!state.diagnostic);wake();}if(rig.mode==='fly')wake();});
 $('scene').addEventListener('pointermove',()=>{if(rig.pointers.size)wake();});$('scene').addEventListener('wheel',wake,{passive:true});}
async function boot(){try{const packed=$('overview-pack').textContent.trim();const [decoded,T]=await Promise.all([G.inflatePack(packed),G.loadThree()]);$('load-progress').style.width='60%';$('load-status').textContent='连续地形已就绪，准备日光与天空…';const castleOverview=G.buildKishinjouOverview();decoded.meshes.push(...castleOverview.meshes);for(const p of G.buildLunarOverviews())decoded.meshes.push(...p.meshes);
 world={meshes:decoded.meshes,data,terrain:new G.Terrain(data),placementMap:new Map(data.placements.map(p=>[p.id,p])),expansion:JSON.parse($('expansion-data').textContent),hlod:{clusters:[],sourceCount:decoded.meshes.length},signs:[],overviewBytes:decoded.meshes.reduce((s,m)=>s,0)};const bufs=new Set();for(const m of decoded.meshes)for(const k of ['vertices','farVertices','instances','instanceColors','index'])if(m[k])bufs.add(m[k].buffer);world.overviewBytes=[...bufs].reduce((s,b)=>s+b.byteLength,0);renderer=new G.DioramaRenderer(T,$('scene'),world);rig=new G.CameraRig($('scene'),world.terrain,wake);rig.aspect=innerWidth/innerHeight;renderer.setSize(innerWidth,innerHeight,devicePixelRatio);renderer.setQuality(state.quality);setupUI();const requested=new URLSearchParams(location.hash.slice(1)).get('view')||'diorama';setView(G.PRESETS[requested]?requested:'diorama',false);characters=new G.DisplayCharacters(world,rig,state,setView,toast);initLabels();state.ready=true;rig.update(0);draw();state.firstFrameMs=performance.now()-bootAt;lastTime=performance.now();$('loader').classList.add('done');setTimeout(()=>$('loader').hidden=true,450);$('engine-label').textContent='THREE.JS r{{THREE_REVISION}} · {{RELEASE_TAG}}';
 stream=new G.RegionStreaming(data,renderer,$('world-builder').textContent,$('legacy-pack').textContent.trim(),msg=>{if(msg.error){$('build-status').textContent='构建失败';toast(msg.error);}else if(msg.loading)$('build-status').textContent='近景生成中…';else if(msg.ready)$('build-status').textContent=[...stream.required].every(id=>stream.cache.has(id))?'精细模型就绪':'近景生成中…';wake();});
 globalThis.ATLAS={state,data,world,rig,renderer,stream,characters,setView,selectLocation,exportState,renderOnce:()=>{rig.updateMatrices();draw();},stats:()=>renderer.info(),wake};renderList();if(state.cutaway)stream.focus(['myouren','mausoleum']);else if(state.focus&&state.focus!=='connections')stream.focus([state.focus]);else if(state.detailNeighbors?.length)stream.focus(state.detailNeighbors);if(!globalThis.ATLAS_TEST_PAUSE)wake();
 }catch(e){console.error(e);globalThis.ATLAS_BOOT_ERROR=e.message;$('load-status').textContent='无法初始化：'+e.message;$('load-progress').style.width='100%';}}
boot();
})(globalThis.GA);
