(function(G){'use strict';
class CameraRig{
 constructor(canvas,terrain,onChange=()=>{}){this.space='surface';this.canvas=canvas;this.terrain=terrain;this.changed=onChange;this.aspect=1;this.fov=49;this.target=[0,30,0];this.eye=[269,184,309];this.radius=480;this.yaw=.7;this.phi=1.1;this.mode='orbit';this.keys=new Set();this.pointers=new Map();this.flySpeed=18;this.transition=null;this.setView(G.PRESETS.riverside,false);this.bind();}
 setView(view,animate=true){const space=view.space||'surface';if(space!==this.space)animate=false;this.space=space;this.mode='orbit';let eye=view.eye.slice(),target=view.target.slice();if(animate)this.transition={fromEye:this.eye.slice(),fromTarget:this.target.slice(),eye,target,started:performance.now(),duration:1400};else{this.transition=null;this.eye=eye;this.target=target;this.fromEye();this.updateMatrices();}this.changed();}
 fromEye(){const v=G.sub(this.eye,this.target);this.radius=G.length(v);this.yaw=Math.atan2(v[0],v[2]);this.phi=Math.acos(G.clamp(v[1]/this.radius,-1,1));}
 toggleFly(){this.transition=null;if(this.mode==='orbit'){this.mode='fly';const d=G.norm(G.sub(this.target,this.eye));this.flyYaw=Math.atan2(d[0],d[2]);this.flyPitch=Math.asin(d[1]);}else{this.mode='orbit';this.target=G.add(this.eye,G.mul(this.direction(),Math.max(15,this.radius*.15)));this.fromEye();}this.changed();return this.mode;}
 direction(){return[Math.sin(this.flyYaw)*Math.cos(this.flyPitch),Math.sin(this.flyPitch),Math.cos(this.flyYaw)*Math.cos(this.flyPitch)];}
 rotate(dx,dy){this.transition=null;if(this.mode==='fly'){this.flyYaw-=dx*.004;this.flyPitch=G.clamp(this.flyPitch-dy*.003,-1.4,1.4);}else{this.yaw-=dx*.004;this.phi=G.clamp(this.phi-dy*.003,.07,1.548);}this.changed();}
 pan(dx,dy){this.transition=null;let s=this.radius*.00105,right=[Math.cos(this.yaw),0,-Math.sin(this.yaw)],up=[Math.sin(this.yaw),0,Math.cos(this.yaw)];this.target=G.add(this.target,G.add(G.mul(right,-dx*s),G.mul(up,-dy*s)));this.target[0]=G.clamp(this.target[0],-5100,5100);this.target[2]=G.clamp(this.target[2],-5100,5100);this.target[1]=Math.max(this.floorAt(this.target[0],this.target[2])+.3,Math.min(this.target[1],1800));this.changed();}
 zoom(delta){this.transition=null;if(this.mode==='fly')this.flySpeed=G.clamp(this.flySpeed*Math.exp(-delta*.001),3,150);else this.radius=G.clamp(this.radius*Math.exp(delta*.001),7,8500);this.changed();}
 bind(){const el=this.canvas;el.addEventListener('contextmenu',e=>e.preventDefault());el.addEventListener('pointerdown',e=>{this.transition=null;el.setPointerCapture(e.pointerId);this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,button:e.button});el.focus({preventScroll:true});});
 el.addEventListener('pointermove',e=>{let p=this.pointers.get(e.pointerId);if(!p)return;let dx=e.clientX-p.x,dy=e.clientY-p.y;if(this.pointers.size===2){const other=[...this.pointers].find(([id])=>id!==e.pointerId)[1];let before=Math.hypot(p.x-other.x,p.y-other.y),after=Math.hypot(e.clientX-other.x,e.clientY-other.y);if(before>1&&after>1)this.zoom(Math.log(before/after)*1000);this.pan(dx*.5,dy*.5);}else if(p.button===2||e.shiftKey)this.pan(dx,dy);else this.rotate(dx,dy);p.x=e.clientX;p.y=e.clientY;});
 for(let ev of['pointerup','pointercancel','lostpointercapture'])el.addEventListener(ev,e=>this.pointers.delete(e.pointerId));el.addEventListener('wheel',e=>{e.preventDefault();this.zoom(e.deltaY);},{passive:false});
 window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;this.keys.add(e.code);if(this.mode==='fly'&&['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();});window.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>this.keys.clear());}
 update(dt){if(this.transition){const t=G.clamp((performance.now()-this.transition.started)/this.transition.duration,0,1),s=t*t*(3-2*t);this.eye=this.transition.eye.map((x,i)=>G.mix(this.transition.fromEye[i],x,s));this.target=this.transition.target.map((x,i)=>G.mix(this.transition.fromTarget[i],x,s));this.fromEye();if(t===1)this.transition=null;this.changed();}
 else if(this.mode==='orbit'){const sp=Math.sin(this.phi);this.eye=[this.target[0]+this.radius*sp*Math.sin(this.yaw),this.target[1]+this.radius*Math.cos(this.phi),this.target[2]+this.radius*sp*Math.cos(this.yaw)];}
 else{let forward=[Math.sin(this.flyYaw),0,Math.cos(this.flyYaw)],right=[-Math.cos(this.flyYaw),0,Math.sin(this.flyYaw)],vel=[0,0,0],k=this.keys;for(let[a,b,v]of[['KeyW','ArrowUp',forward],['KeyS','ArrowDown',G.mul(forward,-1)],['KeyD','ArrowRight',right],['KeyA','ArrowLeft',G.mul(right,-1)]])if(k.has(a)||k.has(b))vel=G.add(vel,v);if(k.has('KeyE')||k.has('Space'))vel[1]++;if(k.has('KeyQ'))vel[1]--;this.eye=G.add(this.eye,G.mul(G.norm(vel),dt*this.flySpeed*(k.has('ShiftLeft')?4:1)));this.eye[0]=G.clamp(this.eye[0],-5100,5100);this.eye[2]=G.clamp(this.eye[2],-5100,5100);this.target=G.add(this.eye,G.mul(this.direction(),50));}
 const h=this.floorAt(this.eye[0],this.eye[2])+1.2;if(this.eye[1]<h){this.eye[1]=h;if(this.mode==='fly')this.target=G.add(this.eye,G.mul(this.direction(),50));}this.updateMatrices();}
 floorAt(x,z){if(this.displayMode==='atlas'||this.displayMode==='focus')return -850;if(this.space==='mausoleum')return -44;if(this.space==='senkai')return 0;if(this.space==='section')return -56;if(this.space==='atlas')return -65;return this.terrain.height(x,z);}
 updateMatrices(){this.view=G.lookAt(this.eye,this.target);this.projection=G.perspective(this.fov,this.aspect,.20,18000);this.vp=G.matmul(this.projection,this.view);this.planes=G.planeFrustum(this.vp);}
 project(p){let a=G.transform(this.vp,p);return{x:(a[0]/a[3]+1)*.5,y:(1-a[1]/a[3])*.5,visible:a[3]>0&&Math.abs(a[0])<a[3]&&Math.abs(a[1])<a[3]};}
}
Object.assign(G,{CameraRig});})(globalThis.GA);
