/* Forest homes, 2026-10-03. Existing v0.14 footprints, paths and signs remain.
 * The two exterior shells and their foundations are authored P refinements.
 * Contact triangles are prepared from the same rendered terrain used at boot;
 * there is no analytic-ground fallback, new location, interior or tree planting.
 */
(function(G){'use strict';
const IDS=['alice','marisa'],TAU=Math.PI*2;
const scopes={alice:{id:'forest-alice-home',bounds:[-1175,-292,-1103,-228]},marisa:{id:'forest-marisa-home',bounds:[-1027,113,-975,167]},boardwalk:{id:'forest-boardwalk',bounds:[-1041,-45,-881,93]}};
const palette={
 alice:{wall:'#d8d5c9',stone:'#a5ab9c',stoneDark:'#858e81',trim:'#7b8b91',shutter:'#516d7e',roof:'#3d596b',ridge:'#344e5d',wood:'#938166',dark:'#655c50',window:'#a0aa9e',iron:'#5e6e6d',soil:'#79845f',flower:'#baa2b0'},
 marisa:{wall:'#afa48b',stone:'#939a87',stoneDark:'#78836f',trim:'#766853',shutter:'#796b59',roof:'#655b65',ridge:'#544d58',wood:'#857157',dark:'#5f5447',window:'#a4a78d',iron:'#536763',soil:'#72845c',flower:'#a89879'}
};
for(const p of Object.values(palette))for(const k of Object.keys(p))p[k]=G.rgb(p[k]);
function bytes(meshes){const seen=new Set();let n=0;for(const m of meshes)for(const k of ['vertices','farVertices','instances','instanceColors','index'])if(m[k]&&!seen.has(m[k].buffer)){seen.add(m[k].buffer);n+=m[k].buffer.byteLength;}return n;}
function prepare(data,pack){for(const s of Object.values(scopes))G.SurfaceContact.prepare(data,pack,s.id,s.bounds);const b=scopes.boardwalk.bounds;
 // Scalars only: these identifiers link public paving to its rendered tile.
 // Never retain a terrain mesh/vertex array in Worker preparation metadata.
 data.forestBoardwalkTerrain=pack.meshes.filter(m=>m.component==='island-terrain'&&!m.cutOnly&&m.index&&m.tile[0]<=b[2]&&m.tile[0]+m.tile[2]>=b[0]&&m.tile[1]<=b[3]&&m.tile[1]+m.tile[2]>=b[1]).map(m=>({id:m.id,center:Array.from(m.center),radius:m.radius,tile:Array.from(m.tile),far:!!m.globalFar}));
 if(!data.forestBoardwalkTerrain.length)throw Error('Forest boardwalk terrain tiles not prepared');return data.surfaceContacts;}
function ground(data,id,far=false){const scope=scopes[id];if(!scope)throw Error('Unknown forest contact scope: '+id);return G.SurfaceContact.sampler(data,scope.id,far?'far':'near');}
function bound(mesh,arrays=[mesh.vertices,mesh.farVertices]){const lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(const a of arrays.filter(Boolean))for(let i=0;i<a.length;i+=9)for(let k=0;k<3;k++){lo[k]=Math.min(lo[k],a[i+k]);hi[k]=Math.max(hi[k],a[i+k]);}mesh.center=lo.map((v,k)=>(v+hi[k])/2);mesh.radius=G.length(G.sub(hi,lo))/2+.03;return mesh;}
function bank(id,far){const p=G.FOREST.pads.find(p=>p.id===id),C=palette[id],bins=new Map();return{p,C,far,
 get(material,part='structure'){const key=material+':'+part;if(!bins.has(key))bins.set(key,{g:new G.Geometry(),material,part});return bins.get(key).g.place(p.x,p.y,p.z);},
 reset(){for(const b of bins.values())b.g.place(p.x,p.y,p.z);},
 finish(meta){const meshes=[];for(const [key,b]of bins)if(b.g.a.length)meshes.push(b.g.mesh('forest:upgrade:'+id+':'+(far?'far:':'near:')+key,'architecture',{owner:'forest',region:'forest',space:'surface',component:id,locationId:id,overview:far,material:'forest'+b.material,forestPart:b.part,basis:'P',...(b.part==='props'?{lod:'props',maxDetailDistance:120}:{})}));return{meshes,bytes:bytes(meshes),meta,signs:[]};}
 };}
function beam(g,a,b,r,c,sides=4){if(G.length(G.sub(a,b))>1e-6)g.tube(a,b,r,c,sides,r);}
function stone(g,x,y,z,w,h,d,c,e=.07,coarse=false){if(coarse){g.box(x,y,z,w,h,d,c);return;}const ps=[[-w/2+e,-d/2],[w/2-e,-d/2],[w/2,-d/2+e],[w/2,d/2-e],[w/2-e,d/2],[-w/2+e,d/2],[-w/2,d/2-e],[-w/2,-d/2+e]],A=ps.map(([a,b])=>[x+a,y,z+b]),B=ps.map(([a,b])=>[x+a,y+h-.04,z+b]),T=ps.map(([a,b])=>[x+a*.985,y+h,z+b*.985]);for(let i=0;i<8;i++){let j=(i+1)%8;g.quad(A[i],A[j],B[j],B[i],c);g.quad(B[i],B[j],T[j],T[i],c);}for(let i=1;i<7;i++){g.tri(T[0],T[i+1],T[i],c);g.tri(A[0],A[i],A[i+1],c);}}
function rect(g,x,y,z,w,h,c){g.quad([x-w/2,y,z],[x+w/2,y,z],[x+w/2,y+h,z],[x-w/2,y+h,z],c);}
function framePart(B,g,x,y,z,w,h,d,c){if(B.far)rect(g,x,y,z+d/2,w,h,c);else g.box(x,y,z,w,h,d,c);}
function safeQuad(g,a,b,c,d,col){for(const ps of[[a,b,c],[a,c,d]])if(G.length(G.cross(G.sub(ps[1],ps[0]),G.sub(ps[2],ps[0])))>1e-7)g.tri(...ps,col);}
function ellipsoid(g,x,y,z,rx,ry,rz,c,slices,rings){const p=(a,b)=>[x+rx*Math.sin(b)*Math.cos(a),y+ry*Math.cos(b),z+rz*Math.sin(b)*Math.sin(a)];for(let j=0;j<rings;j++)for(let i=0;i<slices;i++)safeQuad(g,p(i*TAU/slices,j*Math.PI/rings),p((i+1)*TAU/slices,j*Math.PI/rings),p((i+1)*TAU/slices,(j+1)*Math.PI/rings),p(i*TAU/slices,(j+1)*Math.PI/rings),c);}
function roundOpening(B,o,cx,cz,angle){const C=B.C,N=B.far?12:20,r=o.w/2,cy=o.y+o.h/2,wall=B.get('Plaster').place(B.p.x+cx,B.p.y,B.p.z+cz,angle),frame=B.get('WoodX','windows').place(B.p.x+cx,B.p.y,B.p.z+cz,angle),pane=B.get('Paper','windows').place(B.p.x+cx,B.p.y,B.p.z+cz,angle);const P=(a,rr,z)=>[o.x+Math.cos(a)*rr,cy+Math.sin(a)*rr,z];for(let i=0;i<N;i++){const a=i*TAU/N,b=(i+1)*TAU/N,ra=r/Math.max(Math.abs(Math.cos(a)),Math.abs(Math.sin(a))),rb=r/Math.max(Math.abs(Math.cos(b)),Math.abs(Math.sin(b)));safeQuad(wall,P(a,ra,.17),P(b,rb,.17),P(b,r,.17),P(a,r,.17),C.wall);safeQuad(wall,P(a,r,-.17),P(b,r,-.17),P(b,rb,-.17),P(a,ra,-.17),C.wall);wall.quad(P(a,r,.17),P(b,r,.17),P(b,r,-.17),P(a,r,-.17),C.stoneDark);frame.quad(P(a,r+.05,.195),P(b,r+.05,.195),P(b,r-.045,.195),P(a,r-.045,.195),C.trim);pane.tri([o.x,cy,-.15],P(a,r-.06,-.15),P(b,r-.06,-.15),C.window);}framePart(B,frame,o.x-.028,cy-r+.07,.05,.056,2*r-.14,.08,C.trim);framePart(B,frame,o.x,cy-.028,.05,2*r-.14,.056,.08,C.trim);B.reset();}
// Wall rectangles stop at openings. The pane/door sits behind a .34m reveal.
function facade(B,cx,cz,w,y,h,angle,holes,options={}){const C=B.C,g=B.get('Plaster').place(B.p.x+cx,B.p.y,B.p.z+cz,angle),xs=[...new Set([-w/2,w/2,...holes.flatMap(o=>[o.x-o.w/2,o.x+o.w/2])])].sort((a,b)=>a-b),ys=[...new Set([y,y+h,...holes.flatMap(o=>[o.y,o.y+o.h])])].sort((a,b)=>a-b);for(let i=0;i<xs.length-1;i++){const a=xs[i],b=xs[i+1];if(b-a<.002)continue;let start=null;for(let j=0;j<ys.length;j++){const c=ys[j],d=ys[j+1],open=d!==undefined&&holes.some(o=>(a+b)/2>o.x-o.w/2&&(a+b)/2<o.x+o.w/2&&(c+d)/2>o.y&&(c+d)/2<o.y+o.h);if((open||d===undefined)&&start!==null){rect(g,(a+b)/2,start,.17,b-a,c-start,C.wall);rect(g,(a+b)/2,start,-.17,b-a,c-start,C.wall);start=null;}if(!open&&d!==undefined&&start===null)start=c;}}
 const vx=B.get('WoodY','windows').place(B.p.x+cx,B.p.y,B.p.z+cz,angle),hx=B.get('WoodX','windows').place(B.p.x+cx,B.p.y,B.p.z+cz,angle);
 for(const o of holes){if(o.type==='round'){roundOpening(B,o,cx,cz,angle);g.place(B.p.x+cx,B.p.y,B.p.z+cz,angle);vx.place(B.p.x+cx,B.p.y,B.p.z+cz,angle);hx.place(B.p.x+cx,B.p.y,B.p.z+cz,angle);continue;}
  for(const s of[-1,1]){const xx=o.x+s*o.w/2;g.quad([xx,o.y,.17],[xx,o.y+o.h,.17],[xx,o.y+o.h,-.17],[xx,o.y,-.17],C.stoneDark);framePart(B,vx,o.x+s*(o.w/2+.065),o.y-.08,.22,.18,o.h+.16,.15,C.trim);}for(const yy of[o.y,o.y+o.h])g.quad([o.x-o.w/2,yy,.17],[o.x+o.w/2,yy,.17],[o.x+o.w/2,yy,-.17],[o.x-o.w/2,yy,-.17],C.stoneDark);for(const yy of[o.y-.09,o.y+o.h-.04])framePart(B,hx,o.x,yy,.22,o.w+.32,.13,.16,C.trim);
  if(o.type==='door')continue;
  const pane=B.get('Paper','windows').place(B.p.x+cx,B.p.y,B.p.z+cz,angle);rect(pane,o.x,o.y+.08,-.145,o.w-.18,o.h-.16,C.window);
  // A few readable panes replace the dense universal lattice.
  framePart(B,vx,o.x-.033,o.y+.07,.04,.066,o.h-.14,.09,C.trim);framePart(B,hx,o.x,o.y+o.h*.49,.04,o.w-.12,.066,.09,C.trim);
  if(!B.far&&o.h>2.0)hx.box(o.x,o.y+o.h*.77,.04,o.w-.12,.045,.09,C.trim);
  framePart(B,hx,o.x,o.y-.18,.12,o.w+.40,.14,.55,C.stone);
  if(options.shutters)for(const s of[-1,1]){const sh=B.get('WoodY','shutters').place(B.p.x+cx,B.p.y,B.p.z+cz,angle),xx=o.x+s*(o.w/2+.57);framePart(B,sh,xx,o.y-.04,.21,.68,o.h+.10,.16,C.shutter);if(!B.far)for(let yy=o.y+.15;yy<o.y+o.h-.06;yy+=.38)hx.box(xx,yy,.31,.60,.045,.03,C.trim);}
 }
 B.reset();}
function roof(B,cx,cz,w,d,y,rise,hip=false,part='roof',cut=null){const C=B.C,g=B.get('Roof',part),under=B.get('WoodZ','roofUnder'),edge=B.get('WoodX','eaves'),N=B.far?3:7,H=t=>y+rise*(1-t)+.23*t*t*t*t*t,W=t=>w*(hip?.60+.40*t:1),P=(xx,t,s,off=0)=>[cx+xx,H(t)+off,cz+s*d*.5*t];
 for(const s of[-1,1]){const rows=[...Array.from({length:N+1},(_,i)=>i/N),...(cut&&s===1?[cut.z0/(d*.5),cut.z1/(d*.5)]:[])].sort((a,b)=>a-b);for(let j=0;j<rows.length-1;j++){const t=rows[j],u=rows[j+1];if(u-t<1e-6)continue;const xs=cut&&s===1?[-w/2,cut.x0-cx,cut.x1-cx,w/2]:[-w/2,w/2];for(let k=0;k<xs.length-1;k++){if(cut&&s===1&&(t+u)*d*.25>=cut.z0&&(t+u)*d*.25<=cut.z1&&(xs[k]+xs[k+1])/2>=cut.x0-cx&&(xs[k]+xs[k+1])/2<=cut.x1-cx)continue;const a=xs[k]*(hip?.60+.40*t:1),b=xs[k+1]*(hip?.60+.40*t:1),e=xs[k+1]*(hip?.60+.40*u:1),f=xs[k]*(hip?.60+.40*u:1),A=P(a,t,s),D=P(b,t,s),E=P(e,u,s),F=P(f,u,s);if(s===1)g.quad(D,A,F,E,C.roof);else g.quad(A,D,E,F,C.roof);under.quad(P(a,t,s,-.25),P(b,t,s,-.25),P(e,u,s,-.25),P(f,u,s,-.25),C.dark);}}}
 if(hip)for(const s of[-1,1])for(let j=0;j<N;j++){const t=j/N,u=(j+1)/N,A=[cx+s*w*(.30+.20*t),H(t),cz-d*t/2],D=[cx+s*w*(.30+.20*t),H(t),cz+d*t/2],E=[cx+s*w*(.30+.20*u),H(u),cz+d*u/2],F=[cx+s*w*(.30+.20*u),H(u),cz-d*u/2];if(j===0)g.tri(A,E,F,C.roof);else g.quad(A,D,E,F,C.roof);if(j===0)under.tri([A[0],A[1]-.25,A[2]],[F[0],F[1]-.25,F[2]],[E[0],E[1]-.25,E[2]],C.dark);else under.quad([A[0],A[1]-.25,A[2]],[F[0],F[1]-.25,F[2]],[E[0],E[1]-.25,E[2]],[D[0],D[1]-.25,D[2]],C.dark);}
 else for(const s of[-1,1]){const x=cx+s*(w/2-.45),gable=B.get('WoodY','gable');gable.tri([x,y-.23,cz-d/2+.35],[x,y+rise-.23,cz],[x,y-.23,cz+d/2-.35],C.dark);for(const q of[-1,1])beam(edge,[cx+s*w/2,y+.12,cz+q*d/2],[cx+s*w/2,y+rise+.06,cz],.13,C.trim,B.far?3:4);}
 for(const s of[-1,1]){edge.box(cx,y-.10,cz+s*d/2,w,.32,.28,C.trim);g.box(cx,y+.18,cz+s*d/2,w,.11,.20,C.ridge);if(hip)edge.box(cx+s*w/2,y-.10,cz,.28,.32,d,C.trim);}
 g.box(cx,y+rise+.02,cz,w*(hip?.64:1.02),.22,.45,C.ridge);
 if(!B.far){const rows=4;for(const s of[-1,1])for(let j=1;j<rows;j++){const t=j/rows;if(cut&&s===1&&t*d/2>=cut.z0&&t*d/2<=cut.z1){beam(g,P(-W(t)/2,t,s,.018),P(cut.x0-cx,t,s,.018),.033,C.ridge,3);beam(g,P(cut.x1-cx,t,s,.018),P(W(t)/2,t,s,.018),.033,C.ridge,3);}else beam(g,P(-W(t)/2,t,s,.018),P(W(t)/2,t,s,.018),.033,C.ridge,3);}for(let xx=-w/2+.58;xx<w/2-.3;xx+=1.12){if(hip&&Math.abs(xx)>w*.29)continue;for(const s of[-1,1]){if(cut&&s===1&&cx+xx>cut.x0&&cx+xx<cut.x1)continue;for(let j=0;j<3;j++)beam(g,P(xx,j/3,s,.048),P(xx,(j+1)/3,s,.048),.044,G.blend(C.roof,C.ridge,.32),3);}}for(let xx=-w/2+.45;xx<w/2;xx+=1.1)for(const s of[-1,1])under.box(cx+xx,y-.38,cz+s*(d/2-.6),.12,.14,1.1,C.wood);}
}
function footing(B,terrain,x,z,w,d,top,contacts){const C=B.C,g=B.get('Stone','foundation'),points=[[-w/2,-d/2],[w/2,-d/2],[w/2,d/2],[-w/2,d/2],[0,0]],ys=points.map(([a,b])=>terrain.height(B.p.x+x+a,B.p.z+z+b)-B.p.y),bottom=Math.min(...ys)-.17;stone(g,x,bottom,z,w,top-bottom,d,C.stoneDark,Math.min(.12,w*.15,d*.15),B.far);contacts.push({x:B.p.x+x,z:B.p.z+z,bottom:B.p.y+bottom,top:B.p.y+top,w,d});}
function towerFooting(B,t,x,z,contacts){const {p,C}=B,r=4.06,ys=Array.from({length:8},(_,i)=>t.height(p.x+x+Math.cos(i*TAU/8)*r,p.z+z+Math.sin(i*TAU/8)*r)-p.y),bottom=Math.min(...ys)-.17,g=B.get('Stone','foundation');g.cone(x,bottom,z,r,3.98,.40-bottom,C.stoneDark,8);for(let i=0;i<8;i++)g.tri([x,bottom,z],[x+Math.cos((i+1)*TAU/8)*r,bottom,z+Math.sin((i+1)*TAU/8)*r],[x+Math.cos(i*TAU/8)*r,bottom,z+Math.sin(i*TAU/8)*r],C.stoneDark);contacts.push({x:p.x+x,z:p.z+z,bottom:p.y+bottom,top:p.y+.40,w:8.12,d:8.12});}
function pitchBottom(B,y,rise,d,offset){const N=B.far?3:7,q=Math.abs(offset)/(d/2),j=Math.min(N-1,Math.floor(q*N)),a=j/N,b=(j+1)/N,H=t=>y+rise*(1-t)+.23*t**5;return G.mix(H(a),H(b),(q-a)/(b-a))-.25+.02;}
function recessDoor(B,cx,cz,w,y,h,angle){const C=B.C,room=B.get('Recess','entry').place(B.p.x+cx,B.p.y,B.p.z+cz,angle),door=B.get('WoodY','entry').place(B.p.x+cx,B.p.y,B.p.z+cz,angle);room.box(0,y,-.78,w-.15,h,.15,C.dark);for(const s of[-1,1])room.box(s*(w/2-.08),y,-.46,.12,h,.72,C.dark);room.box(0,y+h-.08,-.45,w,.10,.77,C.dark);door.box(-w*.33,y+.06,-.36,w*.30,h-.12,.12,C.shutter);if(!B.far)for(let yy=y+.27;yy<y+h-.15;yy+=.48)door.box(-w*.33,yy,-.28,w*.24,.042,.03,C.trim);B.reset();}
function vessel(g,x,y,z,r,h,c,far=false){const N=far?6:9,rs=[.64,.90,1,.82,.48],P=(i,j)=>[x+Math.cos(i*TAU/N)*r*rs[j],y+h*j/4,z+Math.sin(i*TAU/N)*r*rs[j]];for(let j=0;j<4;j++)for(let i=0;i<N;i++)g.quad(P(i,j),P((i+1)%N,j),P((i+1)%N,j+1),P(i,j+1),c);for(let i=0;i<N;i++)g.tri([x,y+.88*h,z],P((i+1)%N,4),P(i,4),G.blend(c,palette.marisa.dark,.18));}
function garden(B,terrain,x,z,w,d,far){const C=B.C,g=B.get('Stone','garden'),leaf=B.get('Grass','garden'),R=G.rng(51221+Math.round(x*11));for(const s of[-1,1])if(far){const xx=x+s*w*.48,y=terrain.height(B.p.x+xx,B.p.z+z)-B.p.y-.035;g.box(xx,y,z,.26,.19,d*.94,C.stone);}else for(let i=0;i<5;i++){const xx=x+s*w*.48,zz=z-d*.38+i*d*.19,y=terrain.height(B.p.x+xx,B.p.z+zz)-B.p.y-.035;stone(g,xx,y,zz,.26,.19,d*.18,C.stone,.035);}for(let i=0;i<14;i++){const xx=x+(R()-.5)*w*.78,zz=z+(R()-.5)*d*.77,y=terrain.height(B.p.x+xx,B.p.z+zz)-B.p.y;ellipsoid(leaf,xx,y+.17,zz,.27,.23,.25,C.soil,far?5:7,far?2:3);if(i%3===0)ellipsoid(leaf,xx,y+.34,zz,.15,.08,.14,C.flower,far?5:7,2);}}
function yardBoundary(B,t){const {p,C}=B,base=B.get('Stone','foundation'),wood=B.get('WoodY'),rail=B.get('WoodX'),front=Array.from({length:22},(_,i)=>-26+i*2.5).filter(x=>Math.abs(x)>=4),sides=Array.from({length:23},(_,i)=>-28+i*2.5);if(!B.far){for(const x of front){const y=t.height(p.x+x,p.z+27.6)-p.y-.06;stone(base,x,y,27.6,2.4,.68,.55,C.stone,.055);wood.box(x,y+.68,27.6,.14,.80,.15,C.trim);rail.box(x,y+1.30,27.6,2.55,.14,.16,C.trim);}for(const z of sides)for(const s of[-1,1]){const y=t.height(p.x+s*29,p.z+z)-p.y-.06;stone(base,s*29,y,z,.55,.64,2.42,C.stone,.055);}return;}
 const groups=xs=>{const out=[];for(const x of xs){if(!out.length||out.at(-1).length===3||x-out.at(-1).at(-1)>2.51)out.push([]);out.at(-1).push(x);}return out;};for(const xs of groups(front)){const x=(xs[0]+xs.at(-1))/2,w=xs.at(-1)-xs[0]+2.4,y=Math.min(...xs.map(xx=>t.height(p.x+xx,p.z+27.6)))-p.y-.06;base.box(x,y,27.6,w,.68,.55,C.stone);rail.box(x,y+1.30,27.6,w+.15,.14,.16,C.trim);for(const xx of new Set([xs[0],xs.at(-1)]))wood.box(xx,y+.68,27.6,.14,.80,.15,C.trim);}for(const zs of groups(sides))for(const s of[-1,1]){const z=(zs[0]+zs.at(-1))/2,y=Math.min(...zs.map(zz=>t.height(p.x+s*29,p.z+zz)))-p.y-.06;base.box(s*29,y,z,.55,.64,zs.at(-1)-zs[0]+2.42,C.stone);}}
function buildArchitecture(id,far,data){if(!IDS.includes(id))throw Error('Unknown forest house: '+id);const B=bank(id,far),{p,C}=B,t=ground(data,id,far),contacts=[],wood=B.get('WoodY'),horiz=B.get('WoodX'),stoneG=B.get('Stone','foundation');
 if(id==='alice'){
  footing(B,t,0,0,21,16.7,.45,contacts);B.get('WoodZ','floor').box(0,.45,0,19.15,.16,15.02,C.wood);
  const front=[];for(const y of[1.7,6.0])for(const x of[-6.1,0,6.1])if(!(y<2&&x===0))front.push({x,y,w:2.8,h:2.35});front.push({x:0,y:.73,w:2.25,h:3.75,type:'door'});
  facade(B,0,7.7,19.5,.45,9.1,0,front,{shutters:true});facade(B,0,-7.7,19.5,.45,9.1,Math.PI,[{x:-5,y:6,w:2.8,h:2.4},{x:5,y:6,w:2.8,h:2.4}]);for(const s of[-1,1])facade(B,s*9.75,0,15.4,.45,9.1,s*Math.PI/2,[-4,2].flatMap(z=>[1.7,6].map(y=>({x:-s*z,y,w:2.3,h:2.4}))));
  for(const y of[.80,4.70,9.05])horiz.box(0,y,7.95,20.2,.21,.20,C.trim);
  for(const sx of[-1,1])for(const sz of[-1,1])if(far)stoneG.box(sx*9.73,.62,sz*7.7,.42,8.55,.42,C.stone);else for(let yy=.62;yy<9.3;yy+=.93)stoneG.box(sx*9.73,yy,sz*7.7,.42,.34,.42,C.stone);
  recessDoor(B,0,7.7,2.25,.73,3.75,0);roof(B,0,0,23.5,19,9.65,5.1,true);
  // Original octagonal tower radius/height. Windows occupy its existing front
  // quarter facets rather than a pane intersecting the polygon's corner.
  const tx=12.2,tz=-3,rad=3.9,towerH=12.7;towerFooting(B,t,tx,tz,contacts);
  for(let i=0;i<8;i++){const a=i*TAU/8,b=(i+1)*TAU/8,A=[tx+Math.cos(a)*rad,tz+Math.sin(a)*rad],E=[tx+Math.cos(b)*rad,tz+Math.sin(b)*rad],cx=(A[0]+E[0])/2,cz=(A[1]+E[1])/2,angle=Math.atan2(cx-tx,cz-tz),holes=i===1?[{x:0,y:8.8,w:1.5,h:2.3},{x:0,y:4.22,w:1.76,h:1.76,type:'round'}]:[];facade(B,cx,cz,Math.hypot(E[0]-A[0],E[1]-A[1]),.4,towerH,angle,holes);}
  const tower=B.get('Roof','tower');tower.cone(tx,12.7,tz,4.25,4.25,.37,C.trim,8);tower.cone(tx,13.05,tz,5,.20,6.2,C.roof,8);tower.cone(tx,19.1,tz,.24,.01,1.1,C.trim,8);if(!far)for(let i=0;i<8;i++){const a=i*TAU/8;beam(tower,[tx+Math.cos(a)*5,13.05,tz+Math.sin(a)*5],[tx+Math.cos(a)*.2,19.25,tz+Math.sin(a)*.2],.043,C.ridge,3);}
  footing(B,t,0,9.7,7.6,4.3,.50,contacts);B.get('WoodZ','porch').box(0,.50,9.7,7.6,.30,4.3,C.wood);for(const x of[-3,3]){footing(B,t,x,11.4,.72,.72,.73,contacts);const top=pitchBottom(B,4.05,2,6.3,1.4);wood.box(x,.73,11.4,.46,top-.73,.46,C.wall);horiz.box(x,top-.125,11.4,.72,.25,.72,C.trim);}roof(B,0,10,8.8,6.3,4.05,2);
  for(let i=0;i<4;i++)footing(B,t,0,13.3-i*.63,4.8,.72,.21+i*.20,contacts);
  for(const x of[-13.6,13.6])garden(B,t,x,16,6.2,5,far);
  // Same yard boundary and entrance width; individual segments follow terrain.
  yardBoundary(B,t);
  for(let z=14;z<28;z+=1.8){const y=t.height(p.x,p.z+z)-p.y-.04;stone(stoneG,0,y,z,3.6,.14,1.45,C.stone,.06,far);}
  // Preserve the little outdoor doll-making corner; miniatures are P props.
  for(const x of[-24.2,-17.8]){footing(B,t,x,-9,.53,.53,.10,contacts);wood.box(x,.10,-9,.21,pitchBottom(B,3.6,1.25,5,0)-.10,.21,C.wood);}roof(B,-21,-9,8,5,3.6,1.25);wood.box(-21,.01,-9,4.5,1.3,2.1,C.wood);B.get('WoodX','props').box(-21,1.30,-9,5,.14,2.4,C.wood);for(let i=0;i<3;i++){const g=B.get('Clay','props'),x=-22.3+i*1.3;g.cone(x,1.46,-9,.22,.13,.38,C.shutter,far?5:7);ellipsoid(g,x,2.01,-9,.13,.15,.13,C.window,far?5:7,3);}
 }else{
  footing(B,t,0,0,18.7,16,.45,contacts);B.get('WoodZ','floor').box(0,.45,0,17.25,.16,14.25,C.wood);
  facade(B,0,7.3,17.6,.45,7.25,0,[{x:-5.8,y:1.9,w:3,h:2},{x:5.8,y:1.9,w:3,h:2},{x:-5.8,y:4.8,w:2.4,h:1.9},{x:5.8,y:4.8,w:2.4,h:1.9},{x:0,y:.65,w:2.4,h:3,type:'door'}]);facade(B,0,-7.3,17.6,.45,7.25,Math.PI,[{x:-4.6,y:2.1,w:2.3,h:2},{x:4.6,y:2.1,w:2.3,h:2}]);for(const s of[-1,1])facade(B,s*8.8,0,14.6,.45,7.25,s*Math.PI/2,[-3.6,3.6].map(z=>({x:z,y:2.1,w:2.3,h:2})));
  for(const x of[-8.45,8.45])wood.box(x,.43,7.52,.32,7.3,.32,C.dark);for(const y of[.7,3.9,7.38])horiz.box(0,y,7.53,17.6,.27,.25,C.dark);recessDoor(B,0,7.3,2.4,.65,3,0);roof(B,0,0,21,18.5,7.76,7,false,'roof',{x0:-5.9,x1:-.7,z0:2.45,z1:6.8});
  // An actual dormer shell meets the steep main roof. Its round window is inset.
  facade(B,-3.3,6.0,5.2,9,2.8,0,[{x:0,y:9.78,w:1.74,h:1.74,type:'round'}]);for(const s of[-1,1])facade(B,-3.3+s*2.6,4,4,9,2.8,s*Math.PI/2,[]);roof(B,-3.3,4,6.7,5.6,11.7,2.6);
  const chim=B.get('Stone','chimney');chim.box(5.9,6.9,-3.9,2.1,11.1,2.2,C.stoneDark);chim.box(5.9,17.7,-3.9,2.65,.55,2.8,C.stone);for(const s of[-1,1]){chim.box(5.9+s*.82,18.0,-3.9,.44,.32,2.2,C.stoneDark);chim.box(5.9,18.0,-3.9+s*.9,1.2,.32,.4,C.stoneDark);}B.get('Recess','chimney').box(5.9,18.03,-3.9,1.2,.035,1.2,C.dark);
  footing(B,t,0,10.2,17,4.4,.20,contacts);B.get('WoodZ','porch').box(0,.20,10.2,17,.42,4.4,C.wood);for(const x of[-7.3,7.3]){footing(B,t,x,11.8,.56,.56,.60,contacts);const top=pitchBottom(B,4,1,6.5,2.4);wood.box(x,.60,11.8,.26,top-.60,.26,C.wood);beam(wood,[x,3.1,11.8],[x+(x<0?.70:-.70),top,11.8],.063,C.trim);}roof(B,0,9.4,20,6.5,4,1);
  // Open work shed, its shelf groups and cauldron keep the original footprint.
  for(const x of[12,21])for(const z of[-4,4]){footing(B,t,x,z,.55,.55,.08,contacts);wood.box(x,.08,z,.26,pitchBottom(B,3,1.3,12,z)-.08,.26,C.wood);}for(const z of[-4,4])horiz.box(16.5,pitchBottom(B,3,1.3,12,z)-.18,z,9.3,.23,.27,C.trim);roof(B,16.5,0,12,12,3,1.3,true);
  for(let j=0;j<3;j++){horiz.box(18,.45+j*.75,-3.6,4.9,.14,1.4,C.wood);if(!far||j===1)for(let i=0;i<5;i++)vessel(B.get('Clay','props'),16.2+i*.84,.60+j*.75,-3.6,.19,.45,G.blend(C.iron,C.wood,(i%3)*.27),far);}for(const x of[15.7,20.4])wood.box(x,.34,-3.6,.16,2.05,.16,C.trim);
  const pot=B.get('Iron','props');ellipsoid(pot,13.7,.68,2,1.1,.72,1.02,C.iron,far?8:12,far?3:5);pot.cone(13.7,1.23,2,1,1.06,.22,C.iron,far?8:12);for(const s of[-1,1])wood.box(13.7+s*.85,.0,2,.21,.54,.24,C.dark);
  for(let i=0;i<5;i++){const x=-6+i*2;beam(B.get('WoodY','props'),[x,.5,12.8],[x-.7,2.4,13.3],.045,C.wood);B.get('Grass','props').cone(x-.7,1.8,13.3,.20,.02,.58,C.soil,5);}for(let i=0;i<6;i++)B.get('WoodX','props').box(-13.6+(i%3)*1.1,.2+Math.floor(i/3)*.63,6.8,.98,.58,.90,C.wood);
 }
 // The existing porch-to-path stones stay in place and gain buried bearing faces.
 for(let i=0;i<10;i++){const z=(id==='alice'?16:14)+i*1.1,x=(i%2-.5)*.15;if(id==='alice'&&z<28)continue;const y=t.height(p.x+x,p.z+z)-p.y-.045;stone(stoneG,x,y,z,2.65,.14,.87,G.blend(C.stone,C.wall,.15),.065,far);}
 const out=B.finish({id,visualRevision:1,basis:'P',origin:[p.x,p.y,p.z],footprint:{...p},contacts,fullInterior:false,terrainMutation:false,door:{x:p.x,z:p.z+(id==='alice'?7.7:7.3),y:p.y+(id==='alice'?.73:.65),width:id==='alice'?2.25:2.4,depth:.72},towerWindowFacet:id==='alice'?1:null,dormer:id==='marisa'?{roofCut:{x0:-5.9,x1:-.7,z0:2.45,z1:6.8},windowCentre:[-3.3,10.65,6],windowRaised:.25}:null});
 return out;
}
// The enclosing house/yard sphere is shared by structural material batches.
// It is independent of mesh order and LOD, so a whole shell changes precision
// together. These rounded spheres enclose the unchanged v2 geometry at both LODs.
function homeSphere(id){const p=G.FOREST.pads.find(p=>p.id===id);return id==='alice'?{center:[p.x,p.y+9,p.z],radius:46}:{center:[p.x+6,p.y+9,p.z+7.5],radius:29};}
function batchArchitecture(pack,id){const groups=new Map();for(const m of pack.meshes){const key=JSON.stringify([m.material,m.lod,m.maxDetailDistance,m.lodDistance]);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(m);}
 const sphere=homeSphere(id),meshes=[];for(const group of groups.values()){const first=group[0],n=group.reduce((s,m)=>s+m.vertices.length,0),f=group.reduce((s,m)=>s+(m.farVertices?.length||0),0),vertices=group.length===1?first.vertices:new Float32Array(n),farVertices=f?(group.length===1?first.farVertices:new Float32Array(f)):null,partRanges={};let start=0,farStart=0;
  for(const m of group){const length=m.vertices.length,farLength=m.farVertices?.length||0;if(group.length>1){vertices.set(m.vertices,start);if(farLength)farVertices.set(m.farVertices,farStart);}partRanges[m.forestPart]=[start,length,farStart,farLength];start+=length;farStart+=farLength;}
  const m={...first,id:group.length===1?first.id:first.id.slice(0,first.id.lastIndexOf(':')+1)+'home',vertices,forestPart:group.length===1?first.forestPart:'home',partRanges};if(farVertices)m.farVertices=farVertices;
  // Props keep their original per-material centre, radius, max distance and LOD.
  if(first.forestPart!=='props'){m.center=sphere.center.slice();m.radius=sphere.radius;m.forestHomeBatch=true;}meshes.push(m);
 }return{...pack,meshes,bytes:bytes(meshes)};
}
// Four numeric offsets/lengths per original part address the current vertices
// and farVertices arrays. Checks may create short-lived views; meshes/metadata
// do not cache those views or keep any discarded unbatched ArrayBuffer alive.
function partMeshes(meshes,parts,useFar=false){const names=new Set(parts),out=[];for(const m of meshes){const ranges=m.partRanges||{[m.forestPart]:[0,m.vertices.length,0,m.farVertices?.length||0]},a=useFar?m.farVertices:m.vertices;if(!a)continue;for(const [part,r]of Object.entries(ranges))if(names.has(part)&&r[useFar?3:1])out.push({...m,id:m.id+':part:'+part,forestPart:part,vertices:a.subarray(r[useFar?2:0],r[useFar?2:0]+r[useFar?3:1]),farVertices:undefined});}return out;}
function architecture(id,far=false,data){const out=buildArchitecture(id,far,data);if(!far){const coarse=buildArchitecture(id,true,data),key=m=>m.material+':'+m.forestPart;for(const m of out.meshes){const other=coarse.meshes.find(n=>key(n)===key(m));if(other){m.farVertices=other.vertices;m.lodDistance=165;bound(m);}}}return batchArchitecture(out,id);}
// Reproduce only the legacy boardwalk prefix, then retain every later mushroom,
// stone and fallen-wood vertex unchanged. A changed source fails before replacement.
function legacyBoardwalk(t){const g=new G.Geometry(),path=G.FOREST.paths.find(p=>p.id==='forest-boardwalk');for(let i=0;i<path.samples.length;i++){const p=path.samples[i],next=path.samples[Math.min(i+1,path.samples.length-1)],ang=Math.atan2(next[0]-p[0],next[1]-p[1]);g.place(p[0],t.height(...p)+.25,p[1],ang);g.box(0,0,0,2.4,.16,3.9,G.rgb('#867861'));if(i%3===0)for(const s of[-1,1])g.box(s*1.1,-.36,0,.16,.70,.18,G.C.woodDark);}return g.mesh('legacy-boardwalk').vertices;}
function triangleHeight(A,D,E,x,z){const det=(D[2]-E[2])*(A[0]-E[0])+(E[0]-D[0])*(A[2]-E[2]);if(Math.abs(det)<1e-9)return null;const u=((D[2]-E[2])*(x-E[0])+(E[0]-D[0])*(z-E[2]))/det,v=((E[2]-A[2])*(x-E[0])+(A[0]-E[0])*(z-E[2]))/det,w=1-u-v;return Math.min(u,v,w)<-1e-5?null:u*A[1]+v*D[1]+w*E[1];}
// Sutherland-Hodgman clipping of positions; support faces and vertical deck sides
// use the same tile planes as the top, so no triangle belongs to two LOD tiles.
function tilePolygon(ps,tile,snap=null){let out=ps;for(const [axis,value,greater]of[[0,tile[0],true],[0,tile[0]+tile[2],false],[2,tile[1],true],[2,tile[1]+tile[2],false]]){const next=[];for(let i=0;i<out.length;i++){const a=out[i],b=out[(i+1)%out.length],inside=p=>greater?p[axis]>=value:p[axis]<=value,ia=inside(a),ib=inside(b);if(ia)next.push(a);if(ia!==ib){const u=(value-a[axis])/(b[axis]-a[axis]),p=a.map((v,k)=>G.mix(v,b[k],u));p[axis]=value;if(snap)p[1]=snap(p);next.push(p);}}out=next;if(out.length<3)return [];}
 return out.filter((p,i)=>G.length(G.sub(p.slice(0,3),out[(i+out.length-1)%out.length].slice(0,3)))>1e-8);
}
function boardwalk(data,far=false){const terrain=ground(data,'boardwalk',far),C=palette.marisa,feet=new G.Geometry(),path=G.FOREST.paths.find(p=>p.id==='forest-boardwalk'),samples=path.samples,contacts=[],sections=[],surfaceTriangles=[],batches=new Map(),tiles=data.forestBoardwalkTerrain?.filter(m=>m.far===far);
 if(!tiles?.length)throw Error('Forest boardwalk terrain tiles not prepared');
 const batch=(tile,material)=>{const key=tile.id+':'+material;if(!batches.has(key))batches.set(key,{tile,material,g:new G.Geometry()});return batches.get(key).g;},triangle=(tile,material,a,b,c,col)=>{a=a.slice(0,3);b=b.slice(0,3);c=c.slice(0,3);if(G.length(G.cross(G.sub(b,a),G.sub(c,a)))<=1e-7)return;batch(tile,material).tri(a,b,c,col);};
 const clippedFace=(ps,col,snap=false)=>{for(const tile of tiles){const q=tilePolygon(ps,tile.tile,snap?p=>terrain.height(p[0],p[2])+p[3]:null);for(let i=1;i<q.length-1;i++)triangle(tile,'forestWoodZ',q[0],q[i],q[i+1],col);}};
 // Shared cross-sections avoid gaps/overlap at every existing path bend.
 const edge=(i,s)=>{const p=samples[i],a=samples[Math.max(0,i-1)],b=samples[Math.min(i+1,samples.length-1)],dx=b[0]-a[0],dz=b[1]-a[1],L=Math.hypot(dx,dz),x=p[0]-dz/L*1.2*s,z=p[1]+dx/L*1.2*s;return[x,terrain.height(x,z)+.29,z];};
 const refine=(i,j,A,D,E,F,depth=0)=>{let ok=true;for(const u of[.25,.5,.75])for(const v of[.10,.50,.90]){const x=(A[0]*(1-v)+D[0]*v)*(1-u)+(F[0]*(1-v)+E[0]*v)*u,z=(A[2]*(1-v)+D[2]*v)*(1-u)+(F[2]*(1-v)+E[2]*v)*u,y=triangleHeight(A,D,E,x,z)??triangleHeight(A,E,F,x,z),gap=y-terrain.height(x,z);if(gap<.14||gap>.48)ok=false;}if(ok){sections.push({indices:[i,j],corners:[A,D,E,F]});return;}if(depth===4)throw Error('Forest boardwalk terrain contact needs review');const mid=(a,b)=>{const x=(a[0]+b[0])/2,z=(a[2]+b[2])/2;return[x,terrain.height(x,z)+.29,z];},L=mid(A,F),R=mid(D,E),k=(i+j)/2;refine(i,k,A,D,R,L,depth+1);refine(k,j,L,R,E,F,depth+1);};
 const rows=new Set([0,samples.length-1]);for(let i=0;i<samples.length;i+=far?2:1)rows.add(i);
 // A far chord must not change the footprint at a mixed-LOD tile seam. Keep
 // the original adjacent rows on both sides of every tile-plane crossing.
 for(let i=0;i<samples.length-1;i++){const ps=[edge(i,-1),edge(i,1),edge(i+1,1),edge(i+1,-1)];if([0,2].some(axis=>Math.floor((Math.min(...ps.map(p=>p[axis]))+1e-7)/256)!==Math.floor((Math.max(...ps.map(p=>p[axis]))-1e-7)/256))){rows.add(i);rows.add(i+1);}}
 const ordered=[...rows].sort((a,b)=>a-b);for(let i=1;i<ordered.length;i++){const a=ordered[i-1],b=ordered[i];refine(a,b,edge(a,-1),edge(a,1),edge(b,1),edge(b,-1));}
 const topFace=ps=>{for(const tile of tiles){let q=tilePolygon(ps.map(p=>[...p,.29]),tile.tile,p=>terrain.height(p[0],p[2])+.29);if(q.length<3||Math.abs(q.reduce((s,a,i)=>{const b=q[(i+1)%q.length];return s+a[0]*b[2]-b[0]*a[2];},0))<1e-7)continue;
   // Near/far terrain share 4m boundary samples. Preserve those knots on the
   // paving edge too, rather than interpolating an independent long chord.
   const refined=[];for(let i=0;i<q.length;i++){const a=q[i],b=q[(i+1)%q.length];refined.push(a);for(const axis of[0,2])if(Math.abs(a[axis]-b[axis])<1e-7&&[tile.tile[axis===0?0:1],tile.tile[axis===0?0:1]+tile.tile[2]].some(v=>Math.abs(a[axis]-v)<1e-7)){const other=axis===0?2:0,ts=[];for(let v=Math.ceil(Math.min(a[other],b[other])/4)*4;v<Math.max(a[other],b[other]);v+=4){const u=(v-a[other])/(b[other]-a[other]);if(u>1e-7&&u<1-1e-7)ts.push(u);}for(const u of ts.sort((a,b)=>a-b)){const p=a.map((v,k)=>G.mix(v,b[k],u));p[1]=terrain.height(p[0],p[2])+.29;refined.push(p);}}}q=refined;
   const unchanged=q.length===4&&q.every((p,i)=>p[0]===ps[i][0]&&p[2]===ps[i][2]),centre=q.reduce((v,p)=>v.map((n,k)=>n+p[k]/q.length),[0,0,0]);centre[1]=terrain.height(centre[0],centre[2])+.29;const tris=unchanged?[[q[0],q[1],q[2]],[q[0],q[2],q[3]]]:q.map((p,i)=>[centre,p,q[(i+1)%q.length]]);
   for(const tri of tris){triangle(tile,'forestWoodZ',...tri,C.wood);triangle(tile,'forestWoodZ',...tri.slice().reverse().map(p=>[p[0],p[1]-.16,p[2]]),C.dark);surfaceTriangles.push({terrainSource:tile.id,points:tri.map(p=>p.slice(0,3))});}
  }};
 for(const section of sections){const [i,j]=section.indices,[A,D,E,F]=section.corners;
  topFace([A,D,E,F]);for(const [u,v]of[[A,F],[D,E]])clippedFace([[...u,.29],[...v,.29],[v[0],v[1]-.16,v[2],.13],[u[0],u[1]-.16,u[2],.13]],C.dark,true);
  if(!far&&i%3===0){const a=[(A[0]+D[0])/2,(A[2]+D[2])/2],b=[(F[0]+E[0])/2,(F[2]+E[2])/2],dx=b[0]-a[0],dz=b[1]-a[1],L=Math.hypot(dx,dz),nx=-dz/L,nz=dx/L;for(const s of[-1,1]){const x=(a[0]+b[0])/2+nx*.92*s,z=(a[1]+b[1])/2+nz*.92*s,y=terrain.height(x,z)-.12,top=(triangleHeight(A,D,E,x,z)??triangleHeight(A,E,F,x,z))-.13;feet.box(x,y,z,.19,top-y,.19,C.stoneDark);contacts.push({x,z,bottom:y,top,deckTop:top+.13});}}
 }
 for(const i of[0,samples.length-1]){const p=samples[i],next=samples[i===0?1:i-1],angle=Math.atan2(next[0]-p[0],next[1]-p[1]),y=terrain.height(...p)-.065;feet.place(p[0],y,p[1],angle);feet.box(0,0,0,2.45,.31,.42,C.stoneDark);feet.place();contacts.push({x:p[0],z:p[1],bottom:y,top:y+.31,endpoint:true});const A=edge(i,-1),D=edge(i,1);clippedFace([[...A,.29],[...D,.29],[D[0],D[1]-.16,D[2],.13],[A[0],A[1]-.16,A[2],.13]],C.dark,true);}
 for(let i=0;i<feet.a.length;i+=27){const ps=[0,9,18].map(k=>feet.a.slice(i+k,i+k+3)),col=feet.a.slice(i+6,i+9);for(const tile of tiles){const q=tilePolygon(ps,tile.tile);for(let j=1;j<q.length-1;j++)triangle(tile,'forestStone',q[0],q[j],q[j+1],col);}}
 const meshes=[...batches.values()].map(({g,tile,material})=>g.mesh('forest:public:boardwalk:'+tile.id+':'+(material==='forestWoodZ'?'deck':'feet'),'architecture',{material,owner:'island',region:'island',space:'surface',globalSurface:true,overview:true,component:'forest-boardwalk',basis:'P',forestPart:'boardwalk',globalNear:!far,globalFar:far,terrainSource:tile.id,terrainLodRadius:tile.radius,terrainCenter:tile.center.slice(),terrainTile:tile.tile.slice()}));
 for(const q of contacts){const tile=tiles.find(m=>q.x>=m.tile[0]&&q.x<m.tile[0]+m.tile[2]&&q.z>=m.tile[1]&&q.z<m.tile[1]+m.tile[2]);if(!tile)throw Error('Forest boardwalk bearing has no terrain tile');q.terrainSource=tile.id;}
 return{meshes,contacts,sections,surfaceTriangles,bytes:bytes(meshes)};}
function publicEnvironment(data,pack){prepare(data,pack);const old=pack.meshes.filter(m=>m.owner==='forest'&&IDS.includes(m.component));if(old.length!==8||IDS.some(id=>old.filter(m=>m.component===id).length!==4))throw Error('Forest home proxies changed; review replacement');pack.meshes.splice(0,pack.meshes.length,...pack.meshes.filter(m=>!old.includes(m)));const near=boardwalk(data),far=boardwalk(data,true);data.forestUpgrade={publicContacts:{near:near.contacts,far:far.contacts},replacedProxyIds:old.map(m=>m.id)};return [...near.meshes,...far.meshes];}
const previous=G.buildRegion;
G.buildRegion=async function(data,id,legacy){if(id!=='forest')return previous(data,id,legacy);const start=performance.now(),pack=await previous(data,id,legacy),homes=IDS.flatMap(id=>architecture(id,false,data).meshes),old=pack.meshes.filter(m=>IDS.includes(m.component));if(old.length!==10||IDS.some(id=>old.filter(m=>m.component===id).length!==5))throw Error('Forest home details changed; review replacement');const source=pack.meshes.find(m=>m.id==='forest:understorey');if(!source)throw Error('Forest understorey missing');const prefix=legacyBoardwalk(new G.Terrain(data));if(source.vertices.length<=prefix.length||prefix.some((v,i)=>source.vertices[i]!==v))throw Error('Forest boardwalk prefix changed; review targeted replacement');const retained={...source,vertices:source.vertices.slice(prefix.length)};bound(retained);pack.meshes=pack.meshes.filter(m=>!old.includes(m)&&m!==source).concat(retained,homes);pack.bytes=bytes(pack.meshes);pack.builtMs=performance.now()-start;pack.meta={...pack.meta,forestUpgrade:{revision:1,homeIds:IDS.slice(),retainedUnderstoreyVertices:retained.vertices.length,removedBoardwalkTriangles:prefix.length/27}};return pack;};
G.extraOverviewBuilders=[...(G.extraOverviewBuilders||[]),(data,pack)=>[...publicEnvironment(data,pack),...IDS.flatMap(id=>architecture(id,true,data).meshes)]];
Object.assign(G.PRESETS,{aliceRear:{label:'爱丽丝 · 背墙与侧塔',eye:[-1094,102,-308],target:[-1134,93,-263],fov:55,region:'forest'},aliceFoot:{label:'爱丽丝 · 门廊与塔基',eye:[-1113,88,-247],target:[-1128,88,-261],fov:58,region:'forest'},marisaRear:{label:'雾雨邸 · 背墙与工作棚',eye:[-969,84,104],target:[-993,77,138],fov:56,region:'forest'},marisaFoot:{label:'雾雨邸 · 廊脚与工作棚',eye:[-969,72,153],target:[-983,72.5,140],fov:58,region:'forest'}});
G.FOREST_UPGRADE={ids:IDS,version:3,scopes,prepare,architecture,partMeshes,boardwalk,legacyBoardwalk,publicEnvironment,bytes};
})(globalThis.GA);
